/**
 * generated by Enhanced EcoreGen
 */
package edu.rideshare;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EOperation;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see edu.rideshare.RideshareFactory
 * @model kind="package"
 *        annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen requirement='The Rideshare System is designed to manage trip bookings and customer rewards. The system allows customers to book trips with specific drivers, where each trip includes details such as departure and arrival stations, times, dates, number of available seats, and price. Customers can have different membership packages that include various awards like cashback, discounts, or points, which are computed based on their bookings. Drivers can post trips, and the system checks for any conflicts with their existing trips. Bookings can be made for a specific number of seats, and the system updates the available seats accordingly. The system also checks for eligibility and overlapping trips. Customers can view their bookings, and drivers can manage their trips. The system calculates discounted prices for customers based on their membership and booking time, as well as monthly reward points. The overall functionality is to facilitate ride sharing by connecting customers with drivers through trip bookings while managing rewards and trip logistics.'"
 * @generated
 */
public class RidesharePackage extends EPackageImpl
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final String eNAME = "rideshare";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final String eNS_URI = "http://www.example.org/rideshare";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final String eNS_PREFIX = "rideshare";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final RidesharePackage eINSTANCE = edu.rideshare.RidesharePackage.init();

  /**
   * The meta object id for the '{@link edu.rideshare.User <em>User</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.rideshare.User
   * @see edu.rideshare.RidesharePackage#getUser()
   * @generated
   */
  public static final int USER = 0;

  /**
   * The feature id for the '<em><b>ID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int USER__ID = 0;

  /**
   * The feature id for the '<em><b>Email</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int USER__EMAIL = 1;

  /**
   * The feature id for the '<em><b>Phone Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int USER__PHONE_NUMBER = 2;

  /**
   * The number of structural features of the '<em>User</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int USER_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link edu.rideshare.Driver <em>Driver</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.rideshare.Driver
   * @see edu.rideshare.RidesharePackage#getDriver()
   * @generated
   */
  public static final int DRIVER = 1;

  /**
   * The feature id for the '<em><b>ID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int DRIVER__ID = USER__ID;

  /**
   * The feature id for the '<em><b>Email</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int DRIVER__EMAIL = USER__EMAIL;

  /**
   * The feature id for the '<em><b>Phone Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int DRIVER__PHONE_NUMBER = USER__PHONE_NUMBER;

  /**
   * The feature id for the '<em><b>Trips</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int DRIVER__TRIPS = USER_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Driver</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int DRIVER_FEATURE_COUNT = USER_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.rideshare.Customer <em>Customer</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.rideshare.Customer
   * @see edu.rideshare.RidesharePackage#getCustomer()
   * @generated
   */
  public static final int CUSTOMER = 2;

  /**
   * The feature id for the '<em><b>ID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int CUSTOMER__ID = USER__ID;

  /**
   * The feature id for the '<em><b>Email</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int CUSTOMER__EMAIL = USER__EMAIL;

  /**
   * The feature id for the '<em><b>Phone Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int CUSTOMER__PHONE_NUMBER = USER__PHONE_NUMBER;

  /**
   * The feature id for the '<em><b>Membership Package</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int CUSTOMER__MEMBERSHIP_PACKAGE = USER_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Bookings</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int CUSTOMER__BOOKINGS = USER_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Customer</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int CUSTOMER_FEATURE_COUNT = USER_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link edu.rideshare.Trip <em>Trip</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.rideshare.Trip
   * @see edu.rideshare.RidesharePackage#getTrip()
   * @generated
   */
  public static final int TRIP = 3;

  /**
   * The feature id for the '<em><b>Departure Station</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int TRIP__DEPARTURE_STATION = 0;

  /**
   * The feature id for the '<em><b>Arrival Station</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int TRIP__ARRIVAL_STATION = 1;

  /**
   * The feature id for the '<em><b>Departure Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int TRIP__DEPARTURE_TIME = 2;

  /**
   * The feature id for the '<em><b>Arrival Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int TRIP__ARRIVAL_TIME = 3;

  /**
   * The feature id for the '<em><b>Number Of Seats</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int TRIP__NUMBER_OF_SEATS = 4;

  /**
   * The feature id for the '<em><b>Departure Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int TRIP__DEPARTURE_DATE = 5;

  /**
   * The feature id for the '<em><b>Price</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int TRIP__PRICE = 6;

  /**
   * The feature id for the '<em><b>Bookings</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int TRIP__BOOKINGS = 7;

  /**
   * The feature id for the '<em><b>Stops</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int TRIP__STOPS = 8;

  /**
   * The feature id for the '<em><b>Driver</b></em>' container reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int TRIP__DRIVER = 9;

  /**
   * The number of structural features of the '<em>Trip</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int TRIP_FEATURE_COUNT = 10;

  /**
   * The meta object id for the '{@link edu.rideshare.Booking <em>Booking</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.rideshare.Booking
   * @see edu.rideshare.RidesharePackage#getBooking()
   * @generated
   */
  public static final int BOOKING = 4;

  /**
   * The feature id for the '<em><b>Number Of Seats</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int BOOKING__NUMBER_OF_SEATS = 0;

  /**
   * The feature id for the '<em><b>Booking Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int BOOKING__BOOKING_DATE = 1;

  /**
   * The feature id for the '<em><b>Customer</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int BOOKING__CUSTOMER = 2;

  /**
   * The feature id for the '<em><b>Trip</b></em>' container reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int BOOKING__TRIP = 3;

  /**
   * The number of structural features of the '<em>Booking</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int BOOKING_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link edu.rideshare.Stop <em>Stop</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.rideshare.Stop
   * @see edu.rideshare.RidesharePackage#getStop()
   * @generated
   */
  public static final int STOP = 5;

  /**
   * The feature id for the '<em><b>Stop Station</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int STOP__STOP_STATION = 0;

  /**
   * The feature id for the '<em><b>Trip</b></em>' container reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int STOP__TRIP = 1;

  /**
   * The number of structural features of the '<em>Stop</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int STOP_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link edu.rideshare.MembershipPackage <em>Membership Package</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.rideshare.MembershipPackage
   * @see edu.rideshare.RidesharePackage#getMembershipPackage()
   * @generated
   */
  public static final int MEMBERSHIP_PACKAGE = 6;

  /**
   * The feature id for the '<em><b>Awards</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int MEMBERSHIP_PACKAGE__AWARDS = 0;

  /**
   * The feature id for the '<em><b>Customer</b></em>' container reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int MEMBERSHIP_PACKAGE__CUSTOMER = 1;

  /**
   * The number of structural features of the '<em>Membership Package</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int MEMBERSHIP_PACKAGE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link edu.rideshare.Award <em>Award</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.rideshare.Award
   * @see edu.rideshare.RidesharePackage#getAward()
   * @generated
   */
  public static final int AWARD = 7;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass userEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass driverEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass customerEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass tripEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass bookingEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass stopEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass membershipPackageEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum awardEEnum = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see edu.rideshare.RidesharePackage#eNS_URI
   * @see #init()
   * @generated
   */
  private RidesharePackage()
  {
    super(eNS_URI, RideshareFactory.eINSTANCE);
  }
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link RidesharePackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static RidesharePackage init()
  {
    if (isInited) return (RidesharePackage)EPackage.Registry.INSTANCE.getEPackage(RidesharePackage.eNS_URI);

    // Obtain or create and register package
    Object registeredRidesharePackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    RidesharePackage theRidesharePackage = registeredRidesharePackage instanceof RidesharePackage ? (RidesharePackage)registeredRidesharePackage : new RidesharePackage();

    isInited = true;

    // Create package meta-data objects
    theRidesharePackage.createPackageContents();

    // Initialize created meta-data
    theRidesharePackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theRidesharePackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(RidesharePackage.eNS_URI, theRidesharePackage);
    return theRidesharePackage;
  }


  /**
   * Returns the meta object for class '{@link edu.rideshare.User <em>User</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>User</em>'.
   * @see edu.rideshare.User
   * @generated
   */
  public EClass getUser()
  {
    return userEClass;
  }

  /**
   * Returns the meta object for the attribute '{@link edu.rideshare.User#getID <em>ID</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>ID</em>'.
   * @see edu.rideshare.User#getID()
   * @see #getUser()
   * @generated
   */
  public EAttribute getUser_ID()
  {
    return (EAttribute)userEClass.getEStructuralFeatures().get(0);
  }

  /**
   * Returns the meta object for the attribute '{@link edu.rideshare.User#getEmail <em>Email</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Email</em>'.
   * @see edu.rideshare.User#getEmail()
   * @see #getUser()
   * @generated
   */
  public EAttribute getUser_Email()
  {
    return (EAttribute)userEClass.getEStructuralFeatures().get(1);
  }

  /**
   * Returns the meta object for the attribute '{@link edu.rideshare.User#getPhoneNumber <em>Phone Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Phone Number</em>'.
   * @see edu.rideshare.User#getPhoneNumber()
   * @see #getUser()
   * @generated
   */
  public EAttribute getUser_PhoneNumber()
  {
    return (EAttribute)userEClass.getEStructuralFeatures().get(2);
  }

  /**
   * Returns the meta object for class '{@link edu.rideshare.Driver <em>Driver</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Driver</em>'.
   * @see edu.rideshare.Driver
   * @generated
   */
  public EClass getDriver()
  {
    return driverEClass;
  }

  /**
   * Returns the meta object for the containment reference list '{@link edu.rideshare.Driver#getTrips <em>Trips</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Trips</em>'.
   * @see edu.rideshare.Driver#getTrips()
   * @see #getDriver()
   * @generated
   */
  public EReference getDriver_Trips()
  {
    return (EReference)driverEClass.getEStructuralFeatures().get(0);
  }

  /**
   * Returns the meta object for class '{@link edu.rideshare.Customer <em>Customer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Customer</em>'.
   * @see edu.rideshare.Customer
   * @generated
   */
  public EClass getCustomer()
  {
    return customerEClass;
  }

  /**
   * Returns the meta object for the containment reference '{@link edu.rideshare.Customer#getMembershipPackage <em>Membership Package</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Membership Package</em>'.
   * @see edu.rideshare.Customer#getMembershipPackage()
   * @see #getCustomer()
   * @generated
   */
  public EReference getCustomer_MembershipPackage()
  {
    return (EReference)customerEClass.getEStructuralFeatures().get(0);
  }

  /**
   * Returns the meta object for the reference list '{@link edu.rideshare.Customer#getBookings <em>Bookings</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Bookings</em>'.
   * @see edu.rideshare.Customer#getBookings()
   * @see #getCustomer()
   * @generated
   */
  public EReference getCustomer_Bookings()
  {
    return (EReference)customerEClass.getEStructuralFeatures().get(1);
  }

  /**
   * Returns the meta object for class '{@link edu.rideshare.Trip <em>Trip</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Trip</em>'.
   * @see edu.rideshare.Trip
   * @generated
   */
  public EClass getTrip()
  {
    return tripEClass;
  }

  /**
   * Returns the meta object for the attribute '{@link edu.rideshare.Trip#getDepartureStation <em>Departure Station</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Departure Station</em>'.
   * @see edu.rideshare.Trip#getDepartureStation()
   * @see #getTrip()
   * @generated
   */
  public EAttribute getTrip_DepartureStation()
  {
    return (EAttribute)tripEClass.getEStructuralFeatures().get(0);
  }

  /**
   * Returns the meta object for the attribute '{@link edu.rideshare.Trip#getArrivalStation <em>Arrival Station</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Arrival Station</em>'.
   * @see edu.rideshare.Trip#getArrivalStation()
   * @see #getTrip()
   * @generated
   */
  public EAttribute getTrip_ArrivalStation()
  {
    return (EAttribute)tripEClass.getEStructuralFeatures().get(1);
  }

  /**
   * Returns the meta object for the attribute '{@link edu.rideshare.Trip#getDepartureTime <em>Departure Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Departure Time</em>'.
   * @see edu.rideshare.Trip#getDepartureTime()
   * @see #getTrip()
   * @generated
   */
  public EAttribute getTrip_DepartureTime()
  {
    return (EAttribute)tripEClass.getEStructuralFeatures().get(2);
  }

  /**
   * Returns the meta object for the attribute '{@link edu.rideshare.Trip#getArrivalTime <em>Arrival Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Arrival Time</em>'.
   * @see edu.rideshare.Trip#getArrivalTime()
   * @see #getTrip()
   * @generated
   */
  public EAttribute getTrip_ArrivalTime()
  {
    return (EAttribute)tripEClass.getEStructuralFeatures().get(3);
  }

  /**
   * Returns the meta object for the attribute '{@link edu.rideshare.Trip#getNumberOfSeats <em>Number Of Seats</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Number Of Seats</em>'.
   * @see edu.rideshare.Trip#getNumberOfSeats()
   * @see #getTrip()
   * @generated
   */
  public EAttribute getTrip_NumberOfSeats()
  {
    return (EAttribute)tripEClass.getEStructuralFeatures().get(4);
  }

  /**
   * Returns the meta object for the attribute '{@link edu.rideshare.Trip#getDepartureDate <em>Departure Date</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Departure Date</em>'.
   * @see edu.rideshare.Trip#getDepartureDate()
   * @see #getTrip()
   * @generated
   */
  public EAttribute getTrip_DepartureDate()
  {
    return (EAttribute)tripEClass.getEStructuralFeatures().get(5);
  }

  /**
   * Returns the meta object for the attribute '{@link edu.rideshare.Trip#getPrice <em>Price</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Price</em>'.
   * @see edu.rideshare.Trip#getPrice()
   * @see #getTrip()
   * @generated
   */
  public EAttribute getTrip_Price()
  {
    return (EAttribute)tripEClass.getEStructuralFeatures().get(6);
  }

  /**
   * Returns the meta object for the containment reference list '{@link edu.rideshare.Trip#getBookings <em>Bookings</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Bookings</em>'.
   * @see edu.rideshare.Trip#getBookings()
   * @see #getTrip()
   * @generated
   */
  public EReference getTrip_Bookings()
  {
    return (EReference)tripEClass.getEStructuralFeatures().get(7);
  }

  /**
   * Returns the meta object for the containment reference list '{@link edu.rideshare.Trip#getStops <em>Stops</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Stops</em>'.
   * @see edu.rideshare.Trip#getStops()
   * @see #getTrip()
   * @generated
   */
  public EReference getTrip_Stops()
  {
    return (EReference)tripEClass.getEStructuralFeatures().get(8);
  }

  /**
   * Returns the meta object for the container reference '{@link edu.rideshare.Trip#getDriver <em>Driver</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the container reference '<em>Driver</em>'.
   * @see edu.rideshare.Trip#getDriver()
   * @see #getTrip()
   * @generated
   */
  public EReference getTrip_Driver()
  {
    return (EReference)tripEClass.getEStructuralFeatures().get(9);
  }

  /**
   * Returns the meta object for class '{@link edu.rideshare.Booking <em>Booking</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Booking</em>'.
   * @see edu.rideshare.Booking
   * @generated
   */
  public EClass getBooking()
  {
    return bookingEClass;
  }

  /**
   * Returns the meta object for the attribute '{@link edu.rideshare.Booking#getNumberOfSeats <em>Number Of Seats</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Number Of Seats</em>'.
   * @see edu.rideshare.Booking#getNumberOfSeats()
   * @see #getBooking()
   * @generated
   */
  public EAttribute getBooking_NumberOfSeats()
  {
    return (EAttribute)bookingEClass.getEStructuralFeatures().get(0);
  }

  /**
   * Returns the meta object for the attribute '{@link edu.rideshare.Booking#getBookingDate <em>Booking Date</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Booking Date</em>'.
   * @see edu.rideshare.Booking#getBookingDate()
   * @see #getBooking()
   * @generated
   */
  public EAttribute getBooking_BookingDate()
  {
    return (EAttribute)bookingEClass.getEStructuralFeatures().get(1);
  }

  /**
   * Returns the meta object for the reference '{@link edu.rideshare.Booking#getCustomer <em>Customer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Customer</em>'.
   * @see edu.rideshare.Booking#getCustomer()
   * @see #getBooking()
   * @generated
   */
  public EReference getBooking_Customer()
  {
    return (EReference)bookingEClass.getEStructuralFeatures().get(2);
  }

  /**
   * Returns the meta object for the container reference '{@link edu.rideshare.Booking#getTrip <em>Trip</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the container reference '<em>Trip</em>'.
   * @see edu.rideshare.Booking#getTrip()
   * @see #getBooking()
   * @generated
   */
  public EReference getBooking_Trip()
  {
    return (EReference)bookingEClass.getEStructuralFeatures().get(3);
  }

  /**
   * Returns the meta object for class '{@link edu.rideshare.Stop <em>Stop</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Stop</em>'.
   * @see edu.rideshare.Stop
   * @generated
   */
  public EClass getStop()
  {
    return stopEClass;
  }

  /**
   * Returns the meta object for the attribute '{@link edu.rideshare.Stop#getStopStation <em>Stop Station</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Stop Station</em>'.
   * @see edu.rideshare.Stop#getStopStation()
   * @see #getStop()
   * @generated
   */
  public EAttribute getStop_StopStation()
  {
    return (EAttribute)stopEClass.getEStructuralFeatures().get(0);
  }

  /**
   * Returns the meta object for the container reference '{@link edu.rideshare.Stop#getTrip <em>Trip</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the container reference '<em>Trip</em>'.
   * @see edu.rideshare.Stop#getTrip()
   * @see #getStop()
   * @generated
   */
  public EReference getStop_Trip()
  {
    return (EReference)stopEClass.getEStructuralFeatures().get(1);
  }

  /**
   * Returns the meta object for class '{@link edu.rideshare.MembershipPackage <em>Membership Package</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Membership Package</em>'.
   * @see edu.rideshare.MembershipPackage
   * @generated
   */
  public EClass getMembershipPackage()
  {
    return membershipPackageEClass;
  }

  /**
   * Returns the meta object for the attribute list '{@link edu.rideshare.MembershipPackage#getAwards <em>Awards</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Awards</em>'.
   * @see edu.rideshare.MembershipPackage#getAwards()
   * @see #getMembershipPackage()
   * @generated
   */
  public EAttribute getMembershipPackage_Awards()
  {
    return (EAttribute)membershipPackageEClass.getEStructuralFeatures().get(0);
  }

  /**
   * Returns the meta object for the container reference '{@link edu.rideshare.MembershipPackage#getCustomer <em>Customer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the container reference '<em>Customer</em>'.
   * @see edu.rideshare.MembershipPackage#getCustomer()
   * @see #getMembershipPackage()
   * @generated
   */
  public EReference getMembershipPackage_Customer()
  {
    return (EReference)membershipPackageEClass.getEStructuralFeatures().get(1);
  }

  /**
   * Returns the meta object for enum '{@link edu.rideshare.Award <em>Award</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Award</em>'.
   * @see edu.rideshare.Award
   * @generated
   */
  public EEnum getAward()
  {
    return awardEEnum;
  }

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  public RideshareFactory getRideshareFactory()
  {
    return (RideshareFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    userEClass = createEClass(USER);
    createEAttribute(userEClass, USER__ID);
    createEAttribute(userEClass, USER__EMAIL);
    createEAttribute(userEClass, USER__PHONE_NUMBER);

    driverEClass = createEClass(DRIVER);
    createEReference(driverEClass, DRIVER__TRIPS);

    customerEClass = createEClass(CUSTOMER);
    createEReference(customerEClass, CUSTOMER__MEMBERSHIP_PACKAGE);
    createEReference(customerEClass, CUSTOMER__BOOKINGS);

    tripEClass = createEClass(TRIP);
    createEAttribute(tripEClass, TRIP__DEPARTURE_STATION);
    createEAttribute(tripEClass, TRIP__ARRIVAL_STATION);
    createEAttribute(tripEClass, TRIP__DEPARTURE_TIME);
    createEAttribute(tripEClass, TRIP__ARRIVAL_TIME);
    createEAttribute(tripEClass, TRIP__NUMBER_OF_SEATS);
    createEAttribute(tripEClass, TRIP__DEPARTURE_DATE);
    createEAttribute(tripEClass, TRIP__PRICE);
    createEReference(tripEClass, TRIP__BOOKINGS);
    createEReference(tripEClass, TRIP__STOPS);
    createEReference(tripEClass, TRIP__DRIVER);

    bookingEClass = createEClass(BOOKING);
    createEAttribute(bookingEClass, BOOKING__NUMBER_OF_SEATS);
    createEAttribute(bookingEClass, BOOKING__BOOKING_DATE);
    createEReference(bookingEClass, BOOKING__CUSTOMER);
    createEReference(bookingEClass, BOOKING__TRIP);

    stopEClass = createEClass(STOP);
    createEAttribute(stopEClass, STOP__STOP_STATION);
    createEReference(stopEClass, STOP__TRIP);

    membershipPackageEClass = createEClass(MEMBERSHIP_PACKAGE);
    createEAttribute(membershipPackageEClass, MEMBERSHIP_PACKAGE__AWARDS);
    createEReference(membershipPackageEClass, MEMBERSHIP_PACKAGE__CUSTOMER);

    // Create enums
    awardEEnum = createEEnum(AWARD);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    driverEClass.getESuperTypes().add(this.getUser());
    customerEClass.getESuperTypes().add(this.getUser());

    // Initialize classes and features; add operations and parameters
    initEClass(userEClass, User.class, "User", IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getUser_ID(), ecorePackage.getEString(), "ID", null, 0, 1, User.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUser_Email(), ecorePackage.getEString(), "email", null, 0, 1, User.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUser_PhoneNumber(), ecorePackage.getEString(), "phoneNumber", null, 0, 1, User.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(driverEClass, Driver.class, "Driver", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getDriver_Trips(), this.getTrip(), this.getTrip_Driver(), "trips", null, 0, -1, Driver.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    EOperation op = addEOperation(driverEClass, ecorePackage.getEBoolean(), "checkStopOverlap", 0, 1, IS_UNIQUE, IS_ORDERED);
    addEParameter(op, this.getTrip(), "trip1", 0, 1, IS_UNIQUE, IS_ORDERED);
    addEParameter(op, this.getTrip(), "trip2", 0, 1, IS_UNIQUE, IS_ORDERED);

    op = addEOperation(driverEClass, ecorePackage.getEBoolean(), "canPostTrip", 0, 1, IS_UNIQUE, IS_ORDERED);
    addEParameter(op, this.getTrip(), "newtrip", 0, 1, IS_UNIQUE, IS_ORDERED);

    initEClass(customerEClass, Customer.class, "Customer", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getCustomer_MembershipPackage(), this.getMembershipPackage(), this.getMembershipPackage_Customer(), "membershipPackage", null, 0, 1, Customer.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getCustomer_Bookings(), this.getBooking(), this.getBooking_Customer(), "bookings", null, 0, -1, Customer.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    op = addEOperation(customerEClass, ecorePackage.getEInt(), "computeMonthlyRewardPoints", 0, 1, IS_UNIQUE, IS_ORDERED);
    addEParameter(op, ecorePackage.getEString(), "currentMonth", 0, 1, IS_UNIQUE, IS_ORDERED);

    op = addEOperation(customerEClass, null, "bookTrip", 0, 1, IS_UNIQUE, IS_ORDERED);
    addEParameter(op, this.getTrip(), "trip", 0, 1, IS_UNIQUE, IS_ORDERED);
    addEParameter(op, ecorePackage.getEInt(), "numberOfSeats", 0, 1, IS_UNIQUE, IS_ORDERED);

    initEClass(tripEClass, Trip.class, "Trip", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getTrip_DepartureStation(), ecorePackage.getEString(), "departureStation", null, 0, 1, Trip.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getTrip_ArrivalStation(), ecorePackage.getEString(), "arrivalStation", null, 0, 1, Trip.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getTrip_DepartureTime(), ecorePackage.getEString(), "departureTime", null, 0, 1, Trip.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getTrip_ArrivalTime(), ecorePackage.getEString(), "arrivalTime", null, 0, 1, Trip.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getTrip_NumberOfSeats(), ecorePackage.getEInt(), "numberOfSeats", null, 0, 1, Trip.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getTrip_DepartureDate(), ecorePackage.getEDate(), "departureDate", null, 0, 1, Trip.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getTrip_Price(), ecorePackage.getEDouble(), "price", null, 0, 1, Trip.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getTrip_Bookings(), this.getBooking(), this.getBooking_Trip(), "bookings", null, 0, -1, Trip.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getTrip_Stops(), this.getStop(), this.getStop_Trip(), "stops", null, 0, -1, Trip.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getTrip_Driver(), this.getDriver(), this.getDriver_Trips(), "driver", null, 1, 1, Trip.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    op = addEOperation(tripEClass, ecorePackage.getEDouble(), "calculateDiscountedPrice", 0, 1, IS_UNIQUE, IS_ORDERED);
    addEParameter(op, this.getCustomer(), "customer", 0, 1, IS_UNIQUE, IS_ORDERED);
    addEParameter(op, ecorePackage.getEString(), "bookingTime", 0, 1, IS_UNIQUE, IS_ORDERED);

    op = addEOperation(tripEClass, ecorePackage.getEInt(), "calculateMonthlyPoints", 0, 1, IS_UNIQUE, IS_ORDERED);
    addEParameter(op, this.getCustomer(), "customer", 0, 1, IS_UNIQUE, IS_ORDERED);
    addEParameter(op, ecorePackage.getEString(), "currentMonth", 0, 1, IS_UNIQUE, IS_ORDERED);

    op = addEOperation(tripEClass, ecorePackage.getEBoolean(), "bookSeats", 0, 1, IS_UNIQUE, IS_ORDERED);
    addEParameter(op, ecorePackage.getEInt(), "num", 0, 1, IS_UNIQUE, IS_ORDERED);

    op = addEOperation(tripEClass, ecorePackage.getEBoolean(), "confirmBooking", 0, 1, IS_UNIQUE, IS_ORDERED);
    addEParameter(op, ecorePackage.getEInt(), "seats", 0, 1, IS_UNIQUE, IS_ORDERED);

    addEOperation(tripEClass, ecorePackage.getEString(), "getStopStations", 0, -1, IS_UNIQUE, IS_ORDERED);

    op = addEOperation(tripEClass, ecorePackage.getEBoolean(), "isTimeConflicting", 0, 1, IS_UNIQUE, IS_ORDERED);
    addEParameter(op, ecorePackage.getEString(), "newDepartureTime", 0, 1, IS_UNIQUE, IS_ORDERED);
    addEParameter(op, ecorePackage.getEString(), "newArrivalTime", 0, 1, IS_UNIQUE, IS_ORDERED);

    initEClass(bookingEClass, Booking.class, "Booking", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getBooking_NumberOfSeats(), ecorePackage.getEInt(), "numberOfSeats", null, 0, 1, Booking.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getBooking_BookingDate(), ecorePackage.getEDate(), "bookingDate", null, 0, 1, Booking.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getBooking_Customer(), this.getCustomer(), this.getCustomer_Bookings(), "customer", null, 1, 1, Booking.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getBooking_Trip(), this.getTrip(), this.getTrip_Bookings(), "trip", null, 0, 1, Booking.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    addEOperation(bookingEClass, ecorePackage.getEBoolean(), "isBookingEligible", 0, 1, IS_UNIQUE, IS_ORDERED);

    addEOperation(bookingEClass, null, "updateTripSeats", 0, 1, IS_UNIQUE, IS_ORDERED);

    op = addEOperation(bookingEClass, ecorePackage.getEBoolean(), "overlapsWith", 0, 1, IS_UNIQUE, IS_ORDERED);
    addEParameter(op, this.getTrip(), "trip", 0, 1, IS_UNIQUE, IS_ORDERED);

    initEClass(stopEClass, Stop.class, "Stop", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getStop_StopStation(), ecorePackage.getEString(), "stopStation", null, 0, 1, Stop.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getStop_Trip(), this.getTrip(), this.getTrip_Stops(), "trip", null, 0, 1, Stop.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(membershipPackageEClass, MembershipPackage.class, "MembershipPackage", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getMembershipPackage_Awards(), this.getAward(), "awards", null, 0, -1, MembershipPackage.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getMembershipPackage_Customer(), this.getCustomer(), this.getCustomer_MembershipPackage(), "customer", null, 0, 1, MembershipPackage.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    op = addEOperation(membershipPackageEClass, ecorePackage.getEBoolean(), "hasAward", 0, 1, IS_UNIQUE, IS_ORDERED);
    addEParameter(op, this.getAward(), "award", 0, 1, IS_UNIQUE, IS_ORDERED);

    // Initialize enums and add enum literals
    initEEnum(awardEEnum, Award.class, "Award");
    addEEnumLiteral(awardEEnum, Award.CASHBACK);
    addEEnumLiteral(awardEEnum, Award.DISCOUNTS);
    addEEnumLiteral(awardEEnum, Award.POINTS);

    // Create resource
    createResource(eNS_URI);

    // Create annotations
    // http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen
    createEnhancedCodeGenAnnotations();
  }

  /**
   * Initializes the annotations for <b>http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen</b>.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected void createEnhancedCodeGenAnnotations()
  {
    String source = "http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen";
    addAnnotation
      (this,
       source,
       new String[]
       {
         "requirement", "The Rideshare System is designed to manage trip bookings and customer rewards. The system allows customers to book trips with specific drivers, where each trip includes details such as departure and arrival stations, times, dates, number of available seats, and price. Customers can have different membership packages that include various awards like cashback, discounts, or points, which are computed based on their bookings. Drivers can post trips, and the system checks for any conflicts with their existing trips. Bookings can be made for a specific number of seats, and the system updates the available seats accordingly. The system also checks for eligibility and overlapping trips. Customers can view their bookings, and drivers can manage their trips. The system calculates discounted prices for customers based on their membership and booking time, as well as monthly reward points. The overall functionality is to facilitate ride sharing by connecting customers with drivers through trip bookings while managing rewards and trip logistics."
       });
    addAnnotation
      (driverEClass.getEOperations().get(0),
       source,
       new String[]
       {
         "generated", "true"
       });
    addAnnotation
      (driverEClass.getEOperations().get(1),
       source,
       new String[]
       {
         "generated", "true"
       });
    addAnnotation
      (customerEClass.getEOperations().get(0),
       source,
       new String[]
       {
         "generated", "true"
       });
    addAnnotation
      (customerEClass.getEOperations().get(1),
       source,
       new String[]
       {
         "generated", "true"
       });
    addAnnotation
      (tripEClass.getEOperations().get(0),
       source,
       new String[]
       {
         "generated", "true"
       });
    addAnnotation
      (tripEClass.getEOperations().get(1),
       source,
       new String[]
       {
         "generated", "true"
       });
    addAnnotation
      (tripEClass.getEOperations().get(2),
       source,
       new String[]
       {
         "generated", "true"
       });
    addAnnotation
      (tripEClass.getEOperations().get(3),
       source,
       new String[]
       {
         "generated", "true"
       });
    addAnnotation
      (tripEClass.getEOperations().get(4),
       source,
       new String[]
       {
         "generated", "true"
       });
    addAnnotation
      (tripEClass.getEOperations().get(5),
       source,
       new String[]
       {
         "generated", "true"
       });
    addAnnotation
      (bookingEClass.getEOperations().get(0),
       source,
       new String[]
       {
         "generated", "true"
       });
    addAnnotation
      (bookingEClass.getEOperations().get(1),
       source,
       new String[]
       {
         "generated", "true"
       });
    addAnnotation
      (bookingEClass.getEOperations().get(2),
       source,
       new String[]
       {
         "generated", "true"
       });
    addAnnotation
      (membershipPackageEClass.getEOperations().get(0),
       source,
       new String[]
       {
         "generated", "true"
       });
  }

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  public interface Literals
  {
    /**
     * The meta object literal for the '{@link edu.rideshare.User <em>User</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.rideshare.User
     * @see edu.rideshare.RidesharePackage#getUser()
     * @generated
     */
    public static final EClass USER = eINSTANCE.getUser();

    /**
     * The meta object literal for the '<em><b>ID</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EAttribute USER__ID = eINSTANCE.getUser_ID();

    /**
     * The meta object literal for the '<em><b>Email</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EAttribute USER__EMAIL = eINSTANCE.getUser_Email();

    /**
     * The meta object literal for the '<em><b>Phone Number</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EAttribute USER__PHONE_NUMBER = eINSTANCE.getUser_PhoneNumber();

    /**
     * The meta object literal for the '{@link edu.rideshare.Driver <em>Driver</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.rideshare.Driver
     * @see edu.rideshare.RidesharePackage#getDriver()
     * @generated
     */
    public static final EClass DRIVER = eINSTANCE.getDriver();

    /**
     * The meta object literal for the '<em><b>Trips</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EReference DRIVER__TRIPS = eINSTANCE.getDriver_Trips();

    /**
     * The meta object literal for the '{@link edu.rideshare.Customer <em>Customer</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.rideshare.Customer
     * @see edu.rideshare.RidesharePackage#getCustomer()
     * @generated
     */
    public static final EClass CUSTOMER = eINSTANCE.getCustomer();

    /**
     * The meta object literal for the '<em><b>Membership Package</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EReference CUSTOMER__MEMBERSHIP_PACKAGE = eINSTANCE.getCustomer_MembershipPackage();

    /**
     * The meta object literal for the '<em><b>Bookings</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EReference CUSTOMER__BOOKINGS = eINSTANCE.getCustomer_Bookings();

    /**
     * The meta object literal for the '{@link edu.rideshare.Trip <em>Trip</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.rideshare.Trip
     * @see edu.rideshare.RidesharePackage#getTrip()
     * @generated
     */
    public static final EClass TRIP = eINSTANCE.getTrip();

    /**
     * The meta object literal for the '<em><b>Departure Station</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EAttribute TRIP__DEPARTURE_STATION = eINSTANCE.getTrip_DepartureStation();

    /**
     * The meta object literal for the '<em><b>Arrival Station</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EAttribute TRIP__ARRIVAL_STATION = eINSTANCE.getTrip_ArrivalStation();

    /**
     * The meta object literal for the '<em><b>Departure Time</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EAttribute TRIP__DEPARTURE_TIME = eINSTANCE.getTrip_DepartureTime();

    /**
     * The meta object literal for the '<em><b>Arrival Time</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EAttribute TRIP__ARRIVAL_TIME = eINSTANCE.getTrip_ArrivalTime();

    /**
     * The meta object literal for the '<em><b>Number Of Seats</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EAttribute TRIP__NUMBER_OF_SEATS = eINSTANCE.getTrip_NumberOfSeats();

    /**
     * The meta object literal for the '<em><b>Departure Date</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EAttribute TRIP__DEPARTURE_DATE = eINSTANCE.getTrip_DepartureDate();

    /**
     * The meta object literal for the '<em><b>Price</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EAttribute TRIP__PRICE = eINSTANCE.getTrip_Price();

    /**
     * The meta object literal for the '<em><b>Bookings</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EReference TRIP__BOOKINGS = eINSTANCE.getTrip_Bookings();

    /**
     * The meta object literal for the '<em><b>Stops</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EReference TRIP__STOPS = eINSTANCE.getTrip_Stops();

    /**
     * The meta object literal for the '<em><b>Driver</b></em>' container reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EReference TRIP__DRIVER = eINSTANCE.getTrip_Driver();

    /**
     * The meta object literal for the '{@link edu.rideshare.Booking <em>Booking</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.rideshare.Booking
     * @see edu.rideshare.RidesharePackage#getBooking()
     * @generated
     */
    public static final EClass BOOKING = eINSTANCE.getBooking();

    /**
     * The meta object literal for the '<em><b>Number Of Seats</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EAttribute BOOKING__NUMBER_OF_SEATS = eINSTANCE.getBooking_NumberOfSeats();

    /**
     * The meta object literal for the '<em><b>Booking Date</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EAttribute BOOKING__BOOKING_DATE = eINSTANCE.getBooking_BookingDate();

    /**
     * The meta object literal for the '<em><b>Customer</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EReference BOOKING__CUSTOMER = eINSTANCE.getBooking_Customer();

    /**
     * The meta object literal for the '<em><b>Trip</b></em>' container reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EReference BOOKING__TRIP = eINSTANCE.getBooking_Trip();

    /**
     * The meta object literal for the '{@link edu.rideshare.Stop <em>Stop</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.rideshare.Stop
     * @see edu.rideshare.RidesharePackage#getStop()
     * @generated
     */
    public static final EClass STOP = eINSTANCE.getStop();

    /**
     * The meta object literal for the '<em><b>Stop Station</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EAttribute STOP__STOP_STATION = eINSTANCE.getStop_StopStation();

    /**
     * The meta object literal for the '<em><b>Trip</b></em>' container reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EReference STOP__TRIP = eINSTANCE.getStop_Trip();

    /**
     * The meta object literal for the '{@link edu.rideshare.MembershipPackage <em>Membership Package</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.rideshare.MembershipPackage
     * @see edu.rideshare.RidesharePackage#getMembershipPackage()
     * @generated
     */
    public static final EClass MEMBERSHIP_PACKAGE = eINSTANCE.getMembershipPackage();

    /**
     * The meta object literal for the '<em><b>Awards</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EAttribute MEMBERSHIP_PACKAGE__AWARDS = eINSTANCE.getMembershipPackage_Awards();

    /**
     * The meta object literal for the '<em><b>Customer</b></em>' container reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EReference MEMBERSHIP_PACKAGE__CUSTOMER = eINSTANCE.getMembershipPackage_Customer();

    /**
     * The meta object literal for the '{@link edu.rideshare.Award <em>Award</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.rideshare.Award
     * @see edu.rideshare.RidesharePackage#getAward()
     * @generated
     */
    public static final EEnum AWARD = eINSTANCE.getAward();

  }

} //RidesharePackage
