/**
 * generated by Enhanced EcoreGen
 */
package edu.bank;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.util.EObjectContainmentWithInverseEList;
import org.eclipse.emf.ecore.util.InternalEList;
import edu.bank.BankFactory;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Investment Account</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.bank.InvestmentAccount#getTransactions <em>Transactions</em>}</li>
 * </ul>
 *
 * @see edu.bank.BankPackage#getInvestmentAccount()
 * @model kind="class"
 * @generated
 */
public class InvestmentAccount extends Account
{
  /**
   * The cached value of the '{@link #getTransactions() <em>Transactions</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTransactions()
   * @generated
   * @ordered
   */
  protected EList<StockTransaction> transactions;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected InvestmentAccount()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BankPackage.Literals.INVESTMENT_ACCOUNT;
  }

  /**
   * Returns the value of the '<em><b>Transactions</b></em>' containment reference list.
   * The list contents are of type {@link edu.bank.StockTransaction}.
   * It is bidirectional and its opposite is '{@link edu.bank.StockTransaction#getAccount <em>Account</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Transactions</em>' containment reference list.
   * @see edu.bank.BankPackage#getInvestmentAccount_Transactions()
   * @see edu.bank.StockTransaction#getAccount
   * @model opposite="account" containment="true"
   * @generated
   */
  public EList<StockTransaction> getTransactions()
  {
    if (transactions == null)
    {
      transactions = new EObjectContainmentWithInverseEList<StockTransaction>(StockTransaction.class, this, BankPackage.INVESTMENT_ACCOUNT__TRANSACTIONS, BankPackage.STOCK_TRANSACTION__ACCOUNT);
    }
    return transactions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary:
   *   Purchase a stock, deducting the stock cost and a 10 % commission from the account
   *   balance, and record the transaction.
   * Algorithm:
   *   1. IF quantity ≤ 0 OR price ≤ 0 THEN return false.
   *   2. stockCost ← quantity * price.
   *   3. commission ← stockCost * COMMISSION_RATE (0.10).
   *   4. totalDeduction ← stockCost + commission.
   *   5. IF balance < totalDeduction THEN return false.   // insufficient funds.
   *   6. balance ← balance - totalDeduction.
   *   7. Create new StockTransaction tx:
   *        tx.stock ← stockSymbol
   *        tx.quantity ← quantity
   *        tx.price ← price
   *        tx.commission ← commission
   *        tx.account ← this
   *   8. transactions.add(tx).
   *   9. RETURN true.
   * Input:
   *   stockSymbol : String – ticker symbol of the stock (e.g., "AAPL").
   *   quantity    : int    – number of shares to buy; must be > 0.
   *   price       : double – purchase price per share; must be > 0.
   * Output:
   *   boolean – true if the purchase and recording succeeded, false otherwise.
   * Pre‑condition:
   *   InvestmentAccount.balance is a non‑negative finite double.
   *   transactions list is initialized.
   * Post‑condition:
   *   If true, balance = old_balance – (quantity*price)*(1 + 0.10).
   *   A new StockTransaction reflecting the purchase is appended to transactions.
   * <!-- end-model-doc -->
   * @model stockSymbolRequired="true" quantityRequired="true" priceRequired="true"
   *        annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public boolean buyStock(final String stockSymbol, final int quantity, final double price)
  {
    // Preconditions check
    if (quantity <= 0 || price <= 0) {
      return false;
    }

    final double stockCost = quantity * price;
    final double commission = stockCost * 0.10; // COMMISSION_RATE = 0.10
    final double totalDeduction = stockCost + commission;

    // Check sufficient balance
    if (getBalance() < totalDeduction) {
      return false;
    }

    // Deduct from balance
    setBalance(getBalance() - totalDeduction);

    // Create and populate a new StockTransaction
    StockTransaction tx = BankFactory.eINSTANCE.createStockTransaction();
    tx.setStock(stockSymbol);
    tx.setQuantity(quantity);
    tx.setPrice(price);
    tx.setCommission(commission);
    tx.setAccount(this);

    // Record the transaction
    if (transactions == null) {
      // Defensive: ensure the list is initialized (should be per pre‑condition)
      // The actual initialization logic is handled elsewhere; here we just guard against NPE.
      // If still null, we cannot record the transaction, so we return false.
      return false;
    }
    transactions.add(tx);

    return true;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary:
   *   Compute the total value of an investment account as the sum of the cash balance
   *   and the market value of all owned stocks (market price = 1.1 × purchase price).
   * Algorithm:
   *   1. total ← balance.
   *   2. FOR each tx in transactions DO
   *        marketPrice ← tx.price * MARKET_MULTIPLIER (1.10)
   *        total ← total + (tx.quantity * marketPrice)
   *   3. RETURN total.
   * Input:
   *   (none)
   * Output:
   *   double – total account value; if there are no transactions, this equals balance.
   * Pre‑condition:
   *   balance ≥ 0; each transaction’s price and quantity are non‑negative.
   * Post‑condition:
   *   No mutation of account state; returns a deterministic numeric value.
   * <!-- end-model-doc -->
   * @model required="true"
   *        annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public double calculateValue()
  {
    double total = getBalance();

    if (transactions != null) {
      for (StockTransaction tx : transactions) {
        double marketPrice = tx.getPrice() * 1.10; // MARKET_MULTIPLIER = 1.10
        total += tx.getQuantity() * marketPrice;
      }
    }

    return total;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public NotificationChain eInverseAdd(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case BankPackage.INVESTMENT_ACCOUNT__TRANSACTIONS:
        return ((InternalEList<InternalEObject>)(InternalEList<?>)getTransactions()).basicAdd(otherEnd, msgs);
    }
    return super.eInverseAdd(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case BankPackage.INVESTMENT_ACCOUNT__TRANSACTIONS:
        return ((InternalEList<?>)getTransactions()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case BankPackage.INVESTMENT_ACCOUNT__TRANSACTIONS:
        return getTransactions();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case BankPackage.INVESTMENT_ACCOUNT__TRANSACTIONS:
        getTransactions().clear();
        getTransactions().addAll((Collection<? extends StockTransaction>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case BankPackage.INVESTMENT_ACCOUNT__TRANSACTIONS:
        getTransactions().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case BankPackage.INVESTMENT_ACCOUNT__TRANSACTIONS:
        return transactions != null && !transactions.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} // InvestmentAccount
