/**
 * generated by Enhanced EcoreGen
 */
package edu.pets;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EcoreUtil;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Pet</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.pets.Pet#getName <em>Name</em>}</li>
 *   <li>{@link edu.pets.Pet#getHouse <em>House</em>}</li>
 * </ul>
 *
 * @see edu.pets.PetsPackage#getPet()
 * @model kind="class" abstract="true"
 * @generated
 */
public abstract class Pet extends MinimalEObjectImpl.Container implements EObject
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Pet()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PetsPackage.Literals.PET;
  }

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see edu.pets.PetsPackage#getPet_Name()
   * @model
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * Sets the value of the '{@link edu.pets.Pet#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param newName the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PetsPackage.PET__NAME, oldName, name));
  }

  /**
   * Returns the value of the '<em><b>House</b></em>' container reference.
   * It is bidirectional and its opposite is '{@link edu.pets.House#getLived <em>Lived</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>House</em>' container reference.
   * @see #setHouse(House)
   * @see edu.pets.PetsPackage#getPet_House()
   * @see edu.pets.House#getLived
   * @model opposite="lived" required="true" transient="false"
   * @generated
   */
  public House getHouse()
  {
    if (eContainerFeatureID() != PetsPackage.PET__HOUSE) return null;
    return (House)eInternalContainer();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetHouse(House newHouse, NotificationChain msgs)
  {
    msgs = eBasicSetContainer(newHouse, PetsPackage.PET__HOUSE, msgs);
    return msgs;
  }

  /**
   * Sets the value of the '{@link edu.pets.Pet#getHouse <em>House</em>}' container reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param newHouse the new value of the '<em>House</em>' container reference.
   * @see #getHouse()
   * @generated
   */
  public void setHouse(House newHouse)
  {
    if (newHouse != eInternalContainer() || (eContainerFeatureID() != PetsPackage.PET__HOUSE && newHouse != null))
    {
      if (EcoreUtil.isAncestor(this, newHouse))
        throw new IllegalArgumentException("Recursive containment not allowed for " + toString());
      NotificationChain msgs = null;
      if (eInternalContainer() != null)
        msgs = eBasicRemoveFromContainer(msgs);
      if (newHouse != null)
        msgs = newHouse.eInverseAdd(this, PetsPackage.HOUSE__LIVED, House.class, msgs);
      msgs = basicSetHouse(newHouse, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PetsPackage.PET__HOUSE, newHouse, newHouse));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary
   *   Produces the characteristic noise of the concrete animal.
   *   Sub‑classes (Dog and Cat) must override this method to emit the appropriate
   *   sound (e.g., "Woof!" for dogs, "Meow!" for cats).
   * Algorithm
   *   Abstract – concrete subclasses provide implementation:
   *     Dog.makeNoise() → print or log "Woof!"
   *     Cat.makeNoise() → print or log "Meow!"
   * Input
   *   - None.
   * Output
   *   - void (side‑effect: generates a noise, e.g., console output, audio event, etc.).
   * Pre‑condition
   *   - The pet instance has a non‑null, non‑empty name (name is not used here but
   *     expected to be valid from construction).
   * Post‑condition
   *   - The appropriate animal sound has been emitted; object state remains unchanged.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public void makeNoise()
  {
    // Verify pre‑condition: name must be non‑null and non‑empty
    if (name == null || name.isEmpty()) {
      throw new IllegalStateException("Pet name must be non‑null and non‑empty");
    }
    // Default implementation – subclasses should override to provide a specific sound.
    // Here we emit a generic placeholder message.
    System.out.println(name + " makes a sound.");
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseAdd(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PetsPackage.PET__HOUSE:
        if (eInternalContainer() != null)
          msgs = eBasicRemoveFromContainer(msgs);
        return basicSetHouse((House)otherEnd, msgs);
    }
    return super.eInverseAdd(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PetsPackage.PET__HOUSE:
        return basicSetHouse(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eBasicRemoveFromContainerFeature(NotificationChain msgs)
  {
    switch (eContainerFeatureID())
    {
      case PetsPackage.PET__HOUSE:
        return eInternalContainer().eInverseRemove(this, PetsPackage.HOUSE__LIVED, House.class, msgs);
    }
    return super.eBasicRemoveFromContainerFeature(msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PetsPackage.PET__NAME:
        return getName();
      case PetsPackage.PET__HOUSE:
        return getHouse();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PetsPackage.PET__NAME:
        setName((String)newValue);
        return;
      case PetsPackage.PET__HOUSE:
        setHouse((House)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PetsPackage.PET__NAME:
        setName(NAME_EDEFAULT);
        return;
      case PetsPackage.PET__HOUSE:
        setHouse((House)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PetsPackage.PET__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case PetsPackage.PET__HOUSE:
        return getHouse() != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} // Pet
