import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/**
 * Represents the car rental store. It stores the list of cars, rentals and overdue notices.
 * Provides business operations such as identifying available cars, calculating revenue,
 * finding overdue customers, determining average daily price and counting rentals per customer.
 */
 class Store {

    /** All cars that belong to the store */
    private List<Car> cars;

    /** All rentals performed in the store */
    private List<Rental> rentals;

    /** All overdue notices generated by the store */
    private List<OverdueNotice> notices;

    /** No‑argument constructor required for test instantiation */
    public Store() {
        this.cars = new ArrayList<>();
        this.rentals = new ArrayList<>();
        this.notices = new ArrayList<>();
    }

    // -------------------------------------------------------------------------
    // Getters and Setters
    // -------------------------------------------------------------------------

    public List<Car> getCars() {
        return cars;
    }

    public void setCars(List<Car> cars) {
        this.cars = cars;
    }

    public List<Rental> getRentals() {
        return rentals;
    }

    public void setRentals(List<Rental> rentals) {
        this.rentals = rentals;
    }

    public List<OverdueNotice> getNotices() {
        return notices;
    }

    public void setNotices(List<OverdueNotice> notices) {
        this.notices = notices;
    }

    // -------------------------------------------------------------------------
    // Business methods (implementation of functional requirements)
    // -------------------------------------------------------------------------

    /**
     * Identifies all cars that are currently not rented.
     * A car is considered unavailable if there exists a {@link Rental} whose
     * {@code backDate} is {@code null} (i.e., still rented) and that rental
     * references the car.
     *
     * @return a list of available {@link Car}s sorted by their daily price
     *         in ascending order. Returns an empty list if no cars are available.
     */
    public List<Car> identifyAvailableCars() {
        // Collect plates of cars that are currently rented (backDate == null)
        List<String> rentedPlates = new ArrayList<>();
        for (Rental rental : rentals) {
            if (rental.getBackDate() == null && rental.getCar() != null) {
                rentedPlates.add(rental.getCar().getPlate());
            }
        }

        // Filter cars that are not in the rented list
        List<Car> available = new ArrayList<>();
        for (Car car : cars) {
            if (!rentedPlates.contains(car.getPlate())) {
                available.add(car);
            }
        }

        // Sort by daily price (ascending)
        available.sort(Comparator.comparingDouble(Car::getDailyPrice));
        return available;
    }

    /**
     * Calculates the total revenue generated by all rentals stored in the store.
     *
     * @return the sum of {@code totalPrice} of each {@link Rental}. Returns 0.0
     *         if there are no rentals.
     */
    public double calculateTotalRevenue() {
        double total = 0.0;
        for (Rental rental : rentals) {
            total += rental.getTotalPrice();
        }
        return total;
    }

    /**
     * Finds all customers that have overdue rentals.
     * A rental is overdue when its {@code backDate} is {@code null} and the
     * supplied {@code currentDate} is after the rental's {@code dueDate}.
     *
     * @param currentDate the date against which overdue status is evaluated
     * @return a list of {@link Customer}s with overdue rentals. Returns an empty
     *         list if none are overdue.
     */
    public List<Customer> findCustomersWithOverdueRentals(Date currentDate) {
        List<Customer> overdueCustomers = new ArrayList<>();
        for (Rental rental : rentals) {
            if (rental.getBackDate() == null && rental.getDueDate() != null
                    && currentDate.after(rental.getDueDate())) {
                overdueCustomers.add(rental.getCustomer());
            }
        }
        return overdueCustomers;
    }

    /**
     * Determines the average daily price of all cars in the store.
     *
     * @return the arithmetic mean of the daily prices of the stored cars.
     *         Returns 0.0 when the store does not contain any cars.
     */
    public double determineAverageDailyPrice() {
        if (cars.isEmpty()) {
            return 0.0;
        }
        double sum = 0.0;
        for (Car car : cars) {
            sum += car.getDailyPrice();
        }
        return sum / cars.size();
    }

    /**
     * Counts how many cars each customer has rented.
     *
     * @return a map where the key is a {@link Customer} and the value is the
     *         number of rentals associated with that customer. Returns an empty
     *         map if there are no rentals.
     */
    public Map<Customer, Integer> countCarsRentedPerCustomer() {
        Map<Customer, Integer> countMap = new HashMap<>();
        for (Rental rental : rentals) {
            Customer cust = rental.getCustomer();
            countMap.put(cust, countMap.getOrDefault(cust, 0) + 1);
        }
        return countMap;
    }
}

/**
 * Represents a car in the gallery.
 */
class Car {

    private String plate;
    private String model;
    private double dailyPrice;

    /** No‑argument constructor */
    public Car() {
    }

    // Getters and Setters

    public String getPlate() {
        return plate;
    }

    public void setPlate(String plate) {
        this.plate = plate;
    }

    public String getModel() {
        return model;
    }

    public void setModel(String model) {
        this.model = model;
    }

    public double getDailyPrice() {
        return dailyPrice;
    }

    public void setDailyPrice(double dailyPrice) {
        this.dailyPrice = dailyPrice;
    }

    // Optional: equals and hashCode based on unique plate

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Car car = (Car) o;
        return Objects.equals(plate, car.plate);
    }

    @Override
    public int hashCode() {
        return Objects.hash(plate);
    }
}

/**
 * Represents a customer of the store.
 */
class Customer {

    private String name;
    private String surname;
    private String address;
    private String rentedCarPlate; // plate of the car currently rented (if any)

    /** No‑argument constructor */
    public Customer() {
    }

    // Getters and Setters

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSurname() {
        return surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getRentedCarPlate() {
        return rentedCarPlate;
    }

    public void setRentedCarPlate(String rentedCarPlate) {
        this.rentedCarPlate = rentedCarPlate;
    }

    // equals and hashCode based on name, surname and address (identifies a person)

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Customer customer = (Customer) o;
        return Objects.equals(name, customer.name) &&
               Objects.equals(surname, customer.surname) &&
               Objects.equals(address, customer.address);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, surname, address);
    }
}

/**
 * Represents a rental transaction linking a car and a customer.
 */
class Rental {

    private Date rentalDate;
    private Date dueDate;
    private Date backDate;          // null when the car has not been returned yet
    private double totalPrice;
    private String leasingTerms;
    private Car car;
    private Customer customer;

    /** No‑argument constructor */
    public Rental() {
    }

    // Getters and Setters

    public Date getRentalDate() {
        return rentalDate;
    }

    public void setRentalDate(Date rentalDate) {
        this.rentalDate = rentalDate;
    }

    public Date getDueDate() {
        return dueDate;
    }

    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }

    public Date getBackDate() {
        return backDate;
    }

    public void setBackDate(Date backDate) {
        this.backDate = backDate;
    }

    public double getTotalPrice() {
        return totalPrice;
    }

    public void setTotalPrice(double totalPrice) {
        this.totalPrice = totalPrice;
    }

    public String getLeasingTerms() {
        return leasingTerms;
    }

    public void setLeasingTerms(String leasingTerms) {
        this.leasingTerms = leasingTerms;
    }

    public Car getCar() {
        return car;
    }

    public void setCar(Car car) {
        this.car = car;
    }

    public Customer getCustomer() {
        return customer;
    }

    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
}

/**
 * Represents an overdue notice that can be sent to a customer.
 */
class OverdueNotice {

    private Customer customer;

    /** No‑argument constructor */
    public OverdueNotice() {
    }

    // Getter and Setter

    public Customer getCustomer() {
        return customer;
    }

    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    /**
     * Sends an overdue notice to the specified {@link Customer}.
     * In a real system this could send an email or a printed letter.
     *
     * @param customer the recipient of the notice
     */
    public void sendNoticeTo(Customer customer) {
        // Placeholder implementation – in production this would integrate with a messaging service.
        System.out.println("Overdue notice sent to: " + customer.getName() + " " + customer.getSurname());
    }
}