/**
 * generated by Enhanced EcoreGen
 */
package edu.conference;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Review Assignment</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.conference.ReviewAssignment#getFeedback <em>Feedback</em>}</li>
 *   <li>{@link edu.conference.ReviewAssignment#getGrade <em>Grade</em>}</li>
 *   <li>{@link edu.conference.ReviewAssignment#getPaper <em>Paper</em>}</li>
 * </ul>
 *
 * @see edu.conference.ConferencePackage#getReviewAssignment()
 * @model kind="class"
 * @generated
 */
public class ReviewAssignment extends MinimalEObjectImpl.Container implements EObject
{
  /**
   * The default value of the '{@link #getFeedback() <em>Feedback</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFeedback()
   * @generated
   * @ordered
   */
  protected static final String FEEDBACK_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getFeedback() <em>Feedback</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFeedback()
   * @generated
   * @ordered
   */
  protected String feedback = FEEDBACK_EDEFAULT;

  /**
   * The default value of the '{@link #getGrade() <em>Grade</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGrade()
   * @generated
   * @ordered
   */
  protected static final Grade GRADE_EDEFAULT = Grade.UNDECIDED;

  /**
   * The cached value of the '{@link #getGrade() <em>Grade</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGrade()
   * @generated
   * @ordered
   */
  protected Grade grade = GRADE_EDEFAULT;

  /**
   * The cached value of the '{@link #getPaper() <em>Paper</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPaper()
   * @generated
   * @ordered
   */
  protected Paper paper;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ReviewAssignment()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ConferencePackage.Literals.REVIEW_ASSIGNMENT;
  }

  /**
   * Returns the value of the '<em><b>Feedback</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Feedback</em>' attribute.
   * @see #setFeedback(String)
   * @see edu.conference.ConferencePackage#getReviewAssignment_Feedback()
   * @model
   * @generated
   */
  public String getFeedback()
  {
    return feedback;
  }

  /**
   * Sets the value of the '{@link edu.conference.ReviewAssignment#getFeedback <em>Feedback</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param newFeedback the new value of the '<em>Feedback</em>' attribute.
   * @see #getFeedback()
   * @generated
   */
  public void setFeedback(String newFeedback)
  {
    String oldFeedback = feedback;
    feedback = newFeedback;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ConferencePackage.REVIEW_ASSIGNMENT__FEEDBACK, oldFeedback, feedback));
  }

  /**
   * Returns the value of the '<em><b>Grade</b></em>' attribute.
   * The literals are from the enumeration {@link edu.conference.Grade}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Grade</em>' attribute.
   * @see edu.conference.Grade
   * @see #setGrade(Grade)
   * @see edu.conference.ConferencePackage#getReviewAssignment_Grade()
   * @model
   * @generated
   */
  public Grade getGrade()
  {
    return grade;
  }

  /**
   * Sets the value of the '{@link edu.conference.ReviewAssignment#getGrade <em>Grade</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param newGrade the new value of the '<em>Grade</em>' attribute.
   * @see edu.conference.Grade
   * @see #getGrade()
   * @generated
   */
  public void setGrade(Grade newGrade)
  {
    Grade oldGrade = grade;
    grade = newGrade == null ? GRADE_EDEFAULT : newGrade;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ConferencePackage.REVIEW_ASSIGNMENT__GRADE, oldGrade, grade));
  }

  /**
   * Returns the value of the '<em><b>Paper</b></em>' reference.
   * It is bidirectional and its opposite is '{@link edu.conference.Paper#getReviews <em>Reviews</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Paper</em>' reference.
   * @see #setPaper(Paper)
   * @see edu.conference.ConferencePackage#getReviewAssignment_Paper()
   * @see edu.conference.Paper#getReviews
   * @model opposite="reviews" required="true"
   * @generated
   */
  public Paper getPaper()
  {
    if (paper != null && paper.eIsProxy())
    {
      InternalEObject oldPaper = paper;
      paper = (Paper)eResolveProxy(oldPaper);
      if (paper != oldPaper)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, ConferencePackage.REVIEW_ASSIGNMENT__PAPER, oldPaper, paper));
      }
    }
    return paper;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Paper basicGetPaper()
  {
    return paper;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetPaper(Paper newPaper, NotificationChain msgs)
  {
    Paper oldPaper = paper;
    paper = newPaper;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ConferencePackage.REVIEW_ASSIGNMENT__PAPER, oldPaper, newPaper);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * Sets the value of the '{@link edu.conference.ReviewAssignment#getPaper <em>Paper</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param newPaper the new value of the '<em>Paper</em>' reference.
   * @see #getPaper()
   * @generated
   */
  public void setPaper(Paper newPaper)
  {
    if (newPaper != paper)
    {
      NotificationChain msgs = null;
      if (paper != null)
        msgs = paper.eInverseRemove(this, ConferencePackage.PAPER__REVIEWS, Paper.class, msgs);
      if (newPaper != null)
        msgs = newPaper.eInverseAdd(this, ConferencePackage.PAPER__REVIEWS, Paper.class, msgs);
      msgs = basicSetPaper(newPaper, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ConferencePackage.REVIEW_ASSIGNMENT__PAPER, newPaper, newPaper));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseAdd(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ConferencePackage.REVIEW_ASSIGNMENT__PAPER:
        if (paper != null)
          msgs = paper.eInverseRemove(this, ConferencePackage.PAPER__REVIEWS, Paper.class, msgs);
        return basicSetPaper((Paper)otherEnd, msgs);
    }
    return super.eInverseAdd(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ConferencePackage.REVIEW_ASSIGNMENT__PAPER:
        return basicSetPaper(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ConferencePackage.REVIEW_ASSIGNMENT__FEEDBACK:
        return getFeedback();
      case ConferencePackage.REVIEW_ASSIGNMENT__GRADE:
        return getGrade();
      case ConferencePackage.REVIEW_ASSIGNMENT__PAPER:
        if (resolve) return getPaper();
        return basicGetPaper();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ConferencePackage.REVIEW_ASSIGNMENT__FEEDBACK:
        setFeedback((String)newValue);
        return;
      case ConferencePackage.REVIEW_ASSIGNMENT__GRADE:
        setGrade((Grade)newValue);
        return;
      case ConferencePackage.REVIEW_ASSIGNMENT__PAPER:
        setPaper((Paper)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ConferencePackage.REVIEW_ASSIGNMENT__FEEDBACK:
        setFeedback(FEEDBACK_EDEFAULT);
        return;
      case ConferencePackage.REVIEW_ASSIGNMENT__GRADE:
        setGrade(GRADE_EDEFAULT);
        return;
      case ConferencePackage.REVIEW_ASSIGNMENT__PAPER:
        setPaper((Paper)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ConferencePackage.REVIEW_ASSIGNMENT__FEEDBACK:
        return FEEDBACK_EDEFAULT == null ? feedback != null : !FEEDBACK_EDEFAULT.equals(feedback);
      case ConferencePackage.REVIEW_ASSIGNMENT__GRADE:
        return grade != GRADE_EDEFAULT;
      case ConferencePackage.REVIEW_ASSIGNMENT__PAPER:
        return paper != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (feedback: ");
    result.append(feedback);
    result.append(", grade: ");
    result.append(grade);
    result.append(')');
    return result.toString();
  }

} // ReviewAssignment
