import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

class Store {
    private List<Car> carGallery;
    private List<Customer> customers;
    private List<Rental> rentals;

    public Store() {
        this.carGallery = new ArrayList<>();
        this.customers = new ArrayList<>();
        this.rentals = new ArrayList<>();
    }

    /**
     * Identifies available cars in the store.
     * A car is available if it is not currently rented.
     * Returns a list of available cars, sorted by daily price in ascending order.
     * If no available cars exist, returns an empty list.
     *
     * @return List of available cars sorted by daily price
     */
    public List<Car> getAvailableCars() {
        return carGallery.stream()
                .filter(car -> rentals.stream().noneMatch(rental -> rental.getCar().equals(car) && rental.getBackDate() == null))
                .sorted((car1, car2) -> Double.compare(car1.getDailyPrice(), car2.getDailyPrice()))
                .collect(Collectors.toList());
    }

    /**
     * Calculates the total revenue generated by all rentals in the store.
     *
     * @return Total revenue from all rentals
     */
    public double calculateTotalRevenue() {
        return rentals.stream()
                .filter(rental -> rental.getBackDate() != null)
                .mapToDouble(rental -> {
                    long daysRented = java.time.temporal.ChronoUnit.DAYS.between(rental.getRentDate(), rental.getBackDate());
                    return daysRented * rental.getCar().getDailyPrice();
                })
                .sum();
    }

    /**
     * Lists customers with overdue rentals.
     * For each rental, if the back date is null and the current date is past the due date,
     * marks it as overdue.
     * Returns an empty list if no overdue customers exist.
     *
     * @return List of customers with overdue rentals
     */
    public List<Customer> getOverdueCustomers() {
        LocalDate currentDate = LocalDate.now();
        return customers.stream()
                .filter(customer -> rentals.stream()
                        .anyMatch(rental -> rental.getCustomer().equals(customer)
                                && rental.getBackDate() == null
                                && rental.getDueDate().isBefore(currentDate)))
                .collect(Collectors.toList());
    }

    /**
     * Determines the average daily price of cars in the store.
     * Sums the daily prices of all cars and divides by the total number of cars.
     * If the store has no cars, returns 0.0.
     *
     * @return Average daily price of cars in the store
     */
    public double getAverageDailyPrice() {
        if (carGallery.isEmpty()) {
            return 0.0;
        }
        double totalPrice = carGallery.stream()
                .mapToDouble(Car::getDailyPrice)
                .sum();
        return totalPrice / carGallery.size();
    }

    /**
     * Counts the number of cars rented per customer.
     * Returns a map of customers and their respective rental counts, or an empty map if no customers have rented cars.
     *
     * @return Map of customers and their rental counts
     */
    public Map<Customer, Integer> getCarRentalCountsPerCustomer() {
        Map<Customer, Integer> rentalCounts = new HashMap<>();
        for (Rental rental : rentals) {
            rentalCounts.put(rental.getCustomer(), rentalCounts.getOrDefault(rental.getCustomer(), 0) + 1);
        }
        return rentalCounts;
    }

    // Getters and Setters
    public List<Car> getCarGallery() {
        return carGallery;
    }

    public void setCarGallery(List<Car> carGallery) {
        this.carGallery = carGallery;
    }

    public List<Customer> getCustomers() {
        return customers;
    }

    public void setCustomers(List<Customer> customers) {
        this.customers = customers;
    }

    public List<Rental> getRentals() {
        return rentals;
    }

    public void setRentals(List<Rental> rentals) {
        this.rentals = rentals;
    }
}

class Car {
    private String plate;
    private String model;
    private double dailyPrice;

    public Car() {
    }

    // Getters and Setters
    public String getPlate() {
        return plate;
    }

    public void setPlate(String plate) {
        this.plate = plate;
    }

    public String getModel() {
        return model;
    }

    public void setModel(String model) {
        this.model = model;
    }

    public double getDailyPrice() {
        return dailyPrice;
    }

    public void setDailyPrice(double dailyPrice) {
        this.dailyPrice = dailyPrice;
    }
}

class Customer {
    private String name;
    private String surname;
    private String address;

    public Customer() {
    }

    // Getters and Setters
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSurname() {
        return surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }
}

class Rental {
    private Customer customer;
    private Car car;
    private LocalDate rentDate;
    private LocalDate dueDate;
    private LocalDate backDate;

    public Rental() {
    }

    // Getters and Setters
    public Customer getCustomer() {
        return customer;
    }

    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    public Car getCar() {
        return car;
    }

    public void setCar(Car car) {
        this.car = car;
    }

    public LocalDate getRentDate() {
        return rentDate;
    }

    public void setRentDate(LocalDate rentDate) {
        this.rentDate = rentDate;
    }

    public LocalDate getDueDate() {
        return dueDate;
    }

    public void setDueDate(LocalDate dueDate) {
        this.dueDate = dueDate;
    }

    public LocalDate getBackDate() {
        return backDate;
    }

    public void setBackDate(LocalDate backDate) {
        this.backDate = backDate;
    }
}