/**
 * generated by Enhanced EcoreGen
 */
package edu.conference;

import java.util.Collection;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.util.EObjectResolvingEList;
import org.eclipse.emf.common.util.BasicEList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Author</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.conference.Author#getPapers <em>Papers</em>}</li>
 * </ul>
 *
 * @see edu.conference.ConferencePackage#getAuthor()
 * @model kind="class"
 * @generated
 */
public class Author extends UserRole
{
  /**
   * The cached value of the '{@link #getPapers() <em>Papers</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPapers()
   * @generated
   * @ordered
   */
  protected EList<Paper> papers;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Author()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ConferencePackage.Literals.AUTHOR;
  }

  /**
   * Returns the value of the '<em><b>Papers</b></em>' reference list.
   * The list contents are of type {@link edu.conference.Paper}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Papers</em>' reference list.
   * @see edu.conference.ConferencePackage#getAuthor_Papers()
   * @model
   * @generated
   */
  public EList<Paper> getPapers()
  {
    if (papers == null)
    {
      papers = new EObjectResolvingEList<Paper>(Paper.class, this, ConferencePackage.AUTHOR__PAPERS);
    }
    return papers;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @model
   * @generated NOT
   */
  public void submitPaper(Paper paper)
  {
    if (paper != null && !getPapers().contains(paper)) {
      getPapers().add(paper);
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Counts the total number of papers submitted by the author
   * Algorithm:
   *   1. Return the size of the papers list
   * Input: None
   * Output: Integer representing the total number of papers authored by this instance (> 0)
   * Pre-condition: The papers list is properly maintained with all submissions from the author
   * Post-condition: Returns the accurate count without modifying any object states
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public int countSubmittedPapers()
  {
    return getPapers().size();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Calculates the acceptance rate of the papers submitted by this author as ratio of accepted papers over total submitted papers
   * Algorithm:
   *   1. Let total = size of papers list
   *   2. If total == 0, return 0.0
   *   3. Count papers where decision == ACCEPT
   *   4. Compute rate = accept_count / total
   *   5. Round to two decimal places
   * Input: None
   * Output: Double between 0.0 and 1.0 inclusive representing the proportion of accepted papers
   * Pre-condition: All relevant papers have correct decision values set
   * Post-condition: The method executes without changing any internal state; returns computed acceptance rate
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public double calculateAcceptanceRate()
  {
    int total = getPapers().size();
    if (total == 0) {
      return 0.0;
    }
    
    int acceptCount = 0;
    for (Paper paper : getPapers()) {
      if (paper.getDecision() == Grade.ACCEPT) {
        acceptCount++;
      }
    }
    
    double rate = (double) acceptCount / total;
    return Math.round(rate * 100.0) / 100.0;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Identifies authors whose associated papers have received consistently positive initial reviews (all Accepts before final decision)
   * Algorithm:
   *   1. Traverse through all papers submitted by this author
   *   2. For each paper, check that all submitted reviewer grades equal ACCEPT using helper logic like that from isAllReviewsPositive()
   *   3. Collect authors meeting both criteria across their papers
   *   4. Return unique collection of such authors
   * Input: None
   * Output: List<Author>: Collection of distinct authors satisfying positive-review condition
   * Pre-condition: Papers and respective review structures are completely constructed and referentially consistent
   * Post-condition: Returned list accurately reflects qualifying authors without altering system state
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public EList<Author> findAuthorsWithPositiveReviews()
  {
    EList<Author> result = new BasicEList<Author>();
    
    for (Paper paper : getPapers()) {
      if (paper.isAllReviewsPositive()) {
        // Add this author to the result since at least one paper has all positive reviews
        if (!result.contains(this)) {
          result.add(this);
        }
        break; // Only need to add the author once
      }
    }
    
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ConferencePackage.AUTHOR__PAPERS:
        return getPapers();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ConferencePackage.AUTHOR__PAPERS:
        getPapers().clear();
        getPapers().addAll((Collection<? extends Paper>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ConferencePackage.AUTHOR__PAPERS:
        getPapers().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ConferencePackage.AUTHOR__PAPERS:
        return papers != null && !papers.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} // Author
