package com.turgutlu.football;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import java.util.Optional;

/**
 * Represents a football team of Turgutlu. It holds all players, the
 * starting eleven, the spare (reserve) team and the announcements that
 * are generated during matches.
 */
 class FootballTeam {

    /** The starting eleven players (maximum 11). */
    private List<Player> firstEleven;

    /** The spare (reserve) team players. */
    private List<Player> spareTeam;

    /** All players that belong to the team (includes firstEleven and spareTeam). */
    private List<Player> players;

    /** All announcements generated for the team. */
    private List<Announcement> announcements;

    /** Creates an empty FootballTeam instance with all internal collections initialised. */
    public FootballTeam() {
        this.firstEleven = new ArrayList<>();
        this.spareTeam = new ArrayList<>();
        this.players = new ArrayList<>();
        this.announcements = new ArrayList<>();
    }

    /* --------------------------------------------------------------------- */
    /* Getters and Setters                                                    */
    /* --------------------------------------------------------------------- */

    public List<Player> getFirstEleven() {
        return firstEleven;
    }

    public void setFirstEleven(List<Player> firstEleven) {
        this.firstEleven = firstEleven;
    }

    public List<Player> getSpareTeam() {
        return spareTeam;
    }

    public void setSpareTeam(List<Player> spareTeam) {
        this.spareTeam = spareTeam;
    }

    public List<Player> getPlayers() {
        return players;
    }

    public void setPlayers(List<Player> players) {
        this.players = players;
    }

    public List<Announcement> getAnnouncements() {
        return announcements;
    }

    public void setAnnouncements(List<Announcement> announcements) {
        this.announcements = announcements;
    }

    /* --------------------------------------------------------------------- */
    /* Helper methods to manipulate the collections                           */
    /* --------------------------------------------------------------------- */

    /**
     * Adds a player to the team’s master list.
     *
     * @param player the player to add
     */
    public void addPlayer(Player player) {
        if (player != null) {
            this.players.add(player);
        }
    }

    /**
     * Adds a player to the starting eleven. The method does **not**
     * enforce the 11‑player limit – it is the caller’s responsibility.
     *
     * @param player the player to add to the first eleven
     */
    public void addToFirstEleven(Player player) {
        if (player != null) {
            this.firstEleven.add(player);
            // Ensure the player is also present in the master list
            if (!this.players.contains(player)) {
                this.players.add(player);
            }
        }
    }

    /**
     * Adds a player to the spare (reserve) team.
     *
     * @param player the player to add to the spare team
     */
    public void addToSpareTeam(Player player) {
        if (player != null) {
            this.spareTeam.add(player);
            if (!this.players.contains(player)) {
                this.players.add(player);
            }
        }
    }

    /**
     * Adds an announcement to the team.
     *
     * @param announcement the announcement to store
     */
    public void addAnnouncement(Announcement announcement) {
        if (announcement != null) {
            this.announcements.add(announcement);
        }
    }

    /* --------------------------------------------------------------------- */
    /* Functional requirement implementations                                 */
    /* --------------------------------------------------------------------- */

    /**
     * Calculates the total number of goal‑scoring announcements generated by
     * the starting eleven players of this team. Only players whose position
     * is {@link Position#FORWARD} can generate a score announcement.
     *
     * @return the count of SCORE announcements belonging to forwards in the first eleven
     */
    public int calculateTotalGoalScoringAnnouncementsForFirstEleven() {
        int count = 0;
        for (Announcement ann : announcements) {
            if (ann.getType() == AnnouncementType.SCORE) {
                Player p = ann.getPlayer();
                if (p != null && p.getPosition() == Position.FORWARD && firstEleven.contains(p)) {
                    count++;
                }
            }
        }
        return count;
    }

    /**
     * Finds the midfielder with the highest jersey number among all players of the team.
     *
     * @return the {@link Player} instance with position {@link Position#MIDFIELD} that has the highest number,
     *         or {@code null} if no midfielder exists in the team
     */
    public Player findMidfielderWithHighestNumber() {
        Optional<Player> opt = players.stream()
                .filter(p -> p.getPosition() == Position.MIDFIELD)
                .max((p1, p2) -> Integer.compare(p1.getNumber(), p2.getNumber()));
        return opt.orElse(null);
    }

    /**
     * Calculates the average age of the spare (reserve) team players.
     *
     * @return the average age as a {@code double}; returns {@code 0.0} if the spare team is empty
     */
    public double calculateAverageAgeOfSpareTeam() {
        if (spareTeam.isEmpty()) {
            return 0.0;
        }
        int totalAge = 0;
        for (Player p : spareTeam) {
            totalAge += p.getAge();
        }
        return (double) totalAge / spareTeam.size();
    }

    /**
     * Counts the number of goal‑saving announcements generated by all goalkeepers on the team.
     *
     * @return the count of SAVE announcements belonging to players with position {@link Position#GOALKEEPER}
     */
    public int calculateGoalSavingAnnouncementsByGoalkeeper() {
        int count = 0;
        for (Announcement ann : announcements) {
            if (ann.getType() == AnnouncementType.SAVE) {
                Player p = ann.getPlayer();
                if (p != null && p.getPosition() == Position.GOALKEEPER) {
                    count++;
                }
            }
        }
        return count;
    }

    /**
     * Calculates the total number of announcements made by all forward players on the team,
     * regardless of the announcement type.
     *
     * @return the total number of announcements generated by players whose position is {@link Position#FORWARD}
     */
    public int calculateTotalAnnouncementsForForwardPlayers() {
        int count = 0;
        for (Announcement ann : announcements) {
            Player p = ann.getPlayer();
            if (p != null && p.getPosition() == Position.FORWARD) {
                count++;
            }
        }
        return count;
    }
}

/* ------------------------------------------------------------------------- */
/* Supporting domain classes                                                */
/* ------------------------------------------------------------------------- */

/**
 * Represents a football player.
 */
class Player {

    private String name;
    private int age;
    private int number;
    private Position position;

    /** Creates an empty Player instance. */
    public Player() {
        // default constructor
    }

    /* Getters and Setters */

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public int getNumber() {
        return number;
    }

    public void setNumber(int number) {
        this.number = number;
    }

    public Position getPosition() {
        return position;
    }

    public void setPosition(Position position) {
        this.position = position;
    }
}

/**
 * Enumerates the possible positions a player can have.
 */
enum Position {
    FORWARD,
    MIDFIELD,
    DEFENSE,
    GOALKEEPER
}

/**
 * Enumerates the types of announcements that can be generated during a match.
 */
enum AnnouncementType {
    SCORE,
    SAVE
}

/**
 * Represents an announcement (e.g., a goal scored or saved) generated during a match.
 */
class Announcement {

    private Date time;
    private AnnouncementType type;
    private Player player;

    /** Creates an empty Announcement instance. */
    public Announcement() {
        // default constructor
    }

    /* Getters and Setters */

    public Date getTime() {
        return time;
    }

    public void setTime(Date time) {
        this.time = time;
    }

    public AnnouncementType getType() {
        return type;
    }

    public void setType(AnnouncementType type) {
        this.type = type;
    }

    public Player getPlayer() {
        return player;
    }

    public void setPlayer(Player player) {
        this.player = player;
    }
}