/**
 * generated by Enhanced EcoreGen
 */
package edu.postal;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.EObjectResolvingEList;
import org.eclipse.emf.ecore.util.InternalEList;
import org.eclipse.emf.common.util.BasicEList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Geographical Area</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.postal.GeographicalArea#getMailmen <em>Mailmen</em>}</li>
 *   <li>{@link edu.postal.GeographicalArea#getInhabitants <em>Inhabitants</em>}</li>
 *   <li>{@link edu.postal.GeographicalArea#getAllMails <em>All Mails</em>}</li>
 * </ul>
 *
 * @see edu.postal.PostalPackage#getGeographicalArea()
 * @model kind="class"
 * @generated
 */
public class GeographicalArea extends MinimalEObjectImpl.Container implements EObject
{
  /**
   * The cached value of the '{@link #getMailmen() <em>Mailmen</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMailmen()
   * @generated
   * @ordered
   */
  protected EList<Mailman> mailmen;

  /**
   * The cached value of the '{@link #getInhabitants() <em>Inhabitants</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInhabitants()
   * @generated
   * @ordered
   */
  protected EList<Inhabitant> inhabitants;

  /**
   * The cached value of the '{@link #getAllMails() <em>All Mails</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAllMails()
   * @generated
   * @ordered
   */
  protected EList<RegisteredMail> allMails;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GeographicalArea()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PostalPackage.Literals.GEOGRAPHICAL_AREA;
  }

  /**
   * Returns the value of the '<em><b>Mailmen</b></em>' containment reference list.
   * The list contents are of type {@link edu.postal.Mailman}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mailmen</em>' containment reference list.
   * @see edu.postal.PostalPackage#getGeographicalArea_Mailmen()
   * @model containment="true"
   * @generated
   */
  public EList<Mailman> getMailmen()
  {
    if (mailmen == null)
    {
      mailmen = new EObjectContainmentEList<Mailman>(Mailman.class, this, PostalPackage.GEOGRAPHICAL_AREA__MAILMEN);
    }
    return mailmen;
  }

  /**
   * Returns the value of the '<em><b>Inhabitants</b></em>' containment reference list.
   * The list contents are of type {@link edu.postal.Inhabitant}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Inhabitants</em>' containment reference list.
   * @see edu.postal.PostalPackage#getGeographicalArea_Inhabitants()
   * @model containment="true"
   * @generated
   */
  public EList<Inhabitant> getInhabitants()
  {
    if (inhabitants == null)
    {
      inhabitants = new EObjectContainmentEList<Inhabitant>(Inhabitant.class, this, PostalPackage.GEOGRAPHICAL_AREA__INHABITANTS);
    }
    return inhabitants;
  }

  /**
   * Returns the value of the '<em><b>All Mails</b></em>' reference list.
   * The list contents are of type {@link edu.postal.RegisteredMail}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>All Mails</em>' reference list.
   * @see edu.postal.PostalPackage#getGeographicalArea_AllMails()
   * @model
   * @generated
   */
  public EList<RegisteredMail> getAllMails()
  {
    if (allMails == null)
    {
      allMails = new EObjectResolvingEList<RegisteredMail>(RegisteredMail.class, this, PostalPackage.GEOGRAPHICAL_AREA__ALL_MAILS);
    }
    return allMails;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @model kind="operation"
   *        annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public EList<RegisteredMail> getAllDeliveries()
  {
    // The list of all deliveries is simply the list that stores all registered mails.
    return getAllMails();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public boolean addInhabitant(final Inhabitant newInhabitant)
  {
    if (newInhabitant == null) {
      return false;
    }
    EList<Inhabitant> list = getInhabitants();
    if (!list.contains(newInhabitant)) {
      list.add(newInhabitant);
      return true;
    }
    return false;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public boolean removeInhabitant(final Inhabitant newInhabitant)
  {
    if (newInhabitant == null) {
      return false;
    }
    EList<Inhabitant> inhabitantList = getInhabitants();
    if (!inhabitantList.contains(newInhabitant)) {
      return false;
    }

    // Remove related mails that have a carrier assigned
    EList<RegisteredMail> mailList = getAllMails();
    // Collect mails to remove to avoid concurrent modification
    BasicEList<RegisteredMail> toRemove = new BasicEList<RegisteredMail>();
    for (RegisteredMail mail : mailList) {
      if (newInhabitant.equals(mail.getAddressee()) && mail.getCarrier() != null) {
        toRemove.add(mail);
      }
    }
    mailList.removeAll(toRemove);

    // Finally remove the inhabitant
    inhabitantList.remove(newInhabitant);
    return true;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public boolean addMailman(final Mailman newMailman)
  {
    if (newMailman == null) {
      return false;
    }
    EList<Mailman> list = getMailmen();
    if (!list.contains(newMailman)) {
      list.add(newMailman);
      return true;
    }
    return false;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public boolean removeMailman(final Mailman mailmanToRemove, final Mailman newMailman)
  {
    if (mailmanToRemove == null || newMailman == null) {
      return false;
    }
    EList<Mailman> mailmanList = getMailmen();

    // Must keep at least one mailman after removal
    if (!mailmanList.contains(mailmanToRemove) || mailmanList.size() <= 1) {
      return false;
    }

    // newMailman must be present and different from the one being removed
    if (!mailmanList.contains(newMailman) || mailmanToRemove.equals(newMailman)) {
      return false;
    }

    // Reassign all deliveries of mailmanToRemove to newMailman
    for (RegisteredMail mail : getAllMails()) {
      if (mailmanToRemove.equals(mail.getCarrier())) {
        mail.setCarrier(newMailman);
      }
    }

    // Remove the mailman
    mailmanList.remove(mailmanToRemove);
    return true;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public boolean assignRegisteredMailDeliver(final Mailman carrier, final Inhabitant addressee, final RegisteredMail mail)
  {
    if (carrier == null || addressee == null || mail == null) {
      return false;
    }

    // Check that carrier and addressee belong to this area
    if (!getMailmen().contains(carrier) || !getInhabitants().contains(addressee)) {
      return false;
    }

    // Ensure the mail is not already assigned
    if (mail.getCarrier() != null) {
      return false;
    }

    // Set relationships
    mail.setCarrier(carrier);
    mail.setAddressee(addressee);

    // Ensure the mail is tracked in the area
    EList<RegisteredMail> mailList = getAllMails();
    if (!mailList.contains(mail)) {
      mailList.add(mail);
    }

    return true;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public EList<RegisteredMail> listRegisteredMail(final Mailman carrier)
  {
    if (carrier == null) {
      return null;
    }
    BasicEList<RegisteredMail> result = new BasicEList<RegisteredMail>();
    for (RegisteredMail mail : getAllMails()) {
      if (carrier.equals(mail.getCarrier())) {
        result.add(mail);
      }
    }
    return result.isEmpty() ? null : result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public EList<RegisteredMail> listRegisteredMailWithInhabitant(final Inhabitant addressee)
  {
    if (addressee == null) {
      return null;
    }
    BasicEList<RegisteredMail> result = new BasicEList<RegisteredMail>();
    for (RegisteredMail mail : getAllMails()) {
      if (addressee.equals(mail.getAddressee())) {
        result.add(mail);
      }
    }
    return result.isEmpty() ? null : result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PostalPackage.GEOGRAPHICAL_AREA__MAILMEN:
        return ((InternalEList<?>)getMailmen()).basicRemove(otherEnd, msgs);
      case PostalPackage.GEOGRAPHICAL_AREA__INHABITANTS:
        return ((InternalEList<?>)getInhabitants()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PostalPackage.GEOGRAPHICAL_AREA__MAILMEN:
        return getMailmen();
      case PostalPackage.GEOGRAPHICAL_AREA__INHABITANTS:
        return getInhabitants();
      case PostalPackage.GEOGRAPHICAL_AREA__ALL_MAILS:
        return getAllMails();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PostalPackage.GEOGRAPHICAL_AREA__MAILMEN:
        getMailmen().clear();
        getMailmen().addAll((Collection<? extends Mailman>)newValue);
        return;
      case PostalPackage.GEOGRAPHICAL_AREA__INHABITANTS:
        getInhabitants().clear();
        getInhabitants().addAll((Collection<? extends Inhabitant>)newValue);
        return;
      case PostalPackage.GEOGRAPHICAL_AREA__ALL_MAILS:
        getAllMails().clear();
        getAllMails().addAll((Collection<? extends RegisteredMail>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PostalPackage.GEOGRAPHICAL_AREA__MAILMEN:
        getMailmen().clear();
        return;
      case PostalPackage.GEOGRAPHICAL_AREA__INHABITANTS:
        getInhabitants().clear();
        return;
      case PostalPackage.GEOGRAPHICAL_AREA__ALL_MAILS:
        getAllMails().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PostalPackage.GEOGRAPHICAL_AREA__MAILMEN:
        return mailmen != null && !mailmen.isEmpty();
      case PostalPackage.GEOGRAPHICAL_AREA__INHABITANTS:
        return inhabitants != null && !inhabitants.isEmpty();
      case PostalPackage.GEOGRAPHICAL_AREA__ALL_MAILS:
        return allMails != null && !allMails.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} // GeographicalArea
