/**
 * generated by Enhanced EcoreGen
 */
package edu.pets;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentWithInverseEList;
import org.eclipse.emf.ecore.util.InternalEList;
import org.eclipse.emf.common.util.BasicEList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>House</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.pets.House#getLived <em>Lived</em>}</li>
 * </ul>
 *
 * @see edu.pets.PetsPackage#getHouse()
 * @model kind="class"
 * @generated
 */
public class House extends MinimalEObjectImpl.Container implements EObject
{
  /**
   * The cached value of the '{@link #getLived() <em>Lived</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLived()
   * @generated
   * @ordered
   */
  protected EList<Pet> lived;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected House()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PetsPackage.Literals.HOUSE;
  }

  /**
   * Returns the value of the '<em><b>Lived</b></em>' containment reference list.
   * The list contents are of type {@link edu.pets.Pet}.
   * It is bidirectional and its opposite is '{@link edu.pets.Pet#getHouse <em>House</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lived</em>' containment reference list.
   * @see edu.pets.PetsPackage#getHouse_Lived()
   * @see edu.pets.Pet#getHouse
   * @model opposite="house" containment="true"
   * @generated
   */
  public EList<Pet> getLived()
  {
    if (lived == null)
    {
      lived = new EObjectContainmentWithInverseEList<Pet>(Pet.class, this, PetsPackage.HOUSE__LIVED, PetsPackage.PET__HOUSE);
    }
    return lived;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Retrieves a list of all pet names in the house.
   * Algorithm:
   * 1. Initialize empty list result
   * 2. For each pet in lived list:
   *    a. Add pet.name to result list
   * 3. Return result
   * Input: None
   * Output:
   * - List<String>: List of all pet names in the house
   *   - Empty list if no pets
   * Pre-condition: None
   * Post-condition: Returns all pet names in the house
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public EList<String> retrievePetNames()
  {
    BasicEList<String> result = new BasicEList<>();
    for (Pet pet : getLived()) {
      result.add(pet.getName());
    }
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Adds a pet to the house if it doesn't already belong to any house and has a name.
   * Algorithm:
   * 1. Check if pet is null or pet.name is null or empty
   * 2. If pet.house is not null, return false
   * 3. Set pet.house to this house
   * 4. Add pet to lived list
   * 5. Return true
   * Input:
   * - pet: The pet to be added (Dog or Cat)
   *   - name: Non-null and non-empty string
   *   - house: Must be null (no current house)
   * Output:
   * - boolean: true if pet was added successfully, false otherwise
   * Pre-condition: pet must be a valid Pet object (Dog or Cat)
   * Post-condition: If true is returned, pet.house is set to this house and pet is in lived list
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public boolean addPet(final Pet pet)
  {
    if (pet == null || pet.getName() == null || pet.getName().isEmpty()) {
      return false;
    }
    if (pet.getHouse() != null) {
      return false;
    }
    pet.setHouse(this);
    getLived().add(pet);
    return true;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Removes a pet from the house if it belongs to this house.
   * Algorithm:
   * 1. Check if pet is null
   * 2. Check if pet.house is this house
   * 3. If not, return false
   * 4. Set pet.house to null
   * 5. Remove pet from lived list
   * 6. Return true
   * Input:
   * - pet: The pet to be removed
   *   - Must be a pet in the lived list
   *   - Must be currently living in this house (pet.house == this)
   * Output:
   * - boolean: true if pet was removed successfully, false otherwise
   * Pre-condition: pet must be a valid Pet object
   * Post-condition: If true is returned, pet.house is null and pet is not in lived list
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public void removePet(final Pet pet)
  {
    if (pet == null || pet.getHouse() != this) {
      return;
    }
    pet.setHouse(null);
    getLived().remove(pet);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Retrieves a list of pets of a specific type in the house.
   * Algorithm:
   * 1. Initialize empty list result
   * 2. For each pet in lived list:
   *    a. If pet is instance of type (Dog or Cat)
   *    b. Add pet to result list
   * 3. Return result
   * Input:
   * - type: String specifying pet type ("dog" or "cat")
   *   - Must be either "dog" or "cat" (case-insensitive)
   * Output:
   * - List<Pet>: List of pets of the specified type in the house
   *   - Empty list if no pets of that type
   * Pre-condition: type must be either "dog" or "cat"
   * Post-condition: Returns all pets of the specified type in the house
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public EList<Pet> getPetsByType(final String type)
  {
    if (type == null) {
      return new BasicEList<>();
    }
    BasicEList<Pet> result = new BasicEList<>();
    for (Pet pet : getLived()) {
      if (type.equalsIgnoreCase("dog") && pet instanceof Dog) {
        result.add(pet);
      } else if (type.equalsIgnoreCase("cat") && pet instanceof Cat) {
        result.add(pet);
      }
    }
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Retrieves the number of pets in the house.
   * Algorithm: 
   * 1. Return the size of the list of pets in the house.
   * Input: 
   *  - None
   * Output: 
   *  - int: The number of pets in the house. It should be a non-negative integer.
   * Pre-condition: 
   *  - None
   * Post-condition: 
   *  - None
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public int getPetCount(final String type)
  {
    if (type == null) {
      return getLived().size();
    } else {
      return getPetsByType(type).size();
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public NotificationChain eInverseAdd(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PetsPackage.HOUSE__LIVED:
        return ((InternalEList<InternalEObject>)(InternalEList<?>)getLived()).basicAdd(otherEnd, msgs);
    }
    return super.eInverseAdd(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PetsPackage.HOUSE__LIVED:
        return ((InternalEList<?>)getLived()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PetsPackage.HOUSE__LIVED:
        return getLived();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PetsPackage.HOUSE__LIVED:
        getLived().clear();
        getLived().addAll((Collection<? extends Pet>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PetsPackage.HOUSE__LIVED:
        getLived().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PetsPackage.HOUSE__LIVED:
        return lived != null && !lived.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} // House
