/**
 * generated by Enhanced EcoreGen
 */
package edu.flights;

import java.util.Collection;
import java.util.Date;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Booking</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.flights.Booking#getReservations <em>Reservations</em>}</li>
 *   <li>{@link edu.flights.Booking#getCustomer <em>Customer</em>}</li>
 * </ul>
 *
 * @see edu.flights.FlightsPackage#getBooking()
 * @model kind="class"
 * @generated
 */
public class Booking extends MinimalEObjectImpl.Container implements EObject
{
  /**
   * The cached value of the '{@link #getReservations() <em>Reservations</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getReservations()
   * @generated
   * @ordered
   */
  protected EList<Reservation> reservations;

  /**
   * The cached value of the '{@link #getCustomer() <em>Customer</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCustomer()
   * @generated
   * @ordered
   */
  protected Customer customer;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Booking()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FlightsPackage.Literals.BOOKING;
  }

  /**
   * Returns the value of the '<em><b>Reservations</b></em>' containment reference list.
   * The list contents are of type {@link edu.flights.Reservation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reservations</em>' containment reference list.
   * @see edu.flights.FlightsPackage#getBooking_Reservations()
   * @model containment="true" required="true"
   * @generated
   */
  public EList<Reservation> getReservations()
  {
    if (reservations == null)
    {
      reservations = new EObjectContainmentEList<Reservation>(Reservation.class, this, FlightsPackage.BOOKING__RESERVATIONS);
    }
    return reservations;
  }

  /**
   * Returns the value of the '<em><b>Customer</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Customer</em>' reference.
   * @see #setCustomer(Customer)
   * @see edu.flights.FlightsPackage#getBooking_Customer()
   * @model required="true"
   * @generated
   */
  public Customer getCustomer()
  {
    if (customer != null && customer.eIsProxy())
    {
      InternalEObject oldCustomer = customer;
      customer = (Customer)eResolveProxy(oldCustomer);
      if (customer != oldCustomer)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, FlightsPackage.BOOKING__CUSTOMER, oldCustomer, customer));
      }
    }
    return customer;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Customer basicGetCustomer()
  {
    return customer;
  }

  /**
   * Sets the value of the '{@link edu.flights.Booking#getCustomer <em>Customer</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param newCustomer the new value of the '<em>Customer</em>' reference.
   * @see #getCustomer()
   * @generated
   */
  public void setCustomer(Customer newCustomer)
  {
    Customer oldCustomer = customer;
    customer = newCustomer;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FlightsPackage.BOOKING__CUSTOMER, oldCustomer, customer));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Creates a reservation for a passenger on a flight
   * Algorithm:
   *   1. If f.openForBooking == false, return false
   *   2. If now >= f.departureTime, return false
   *   3. Create new Passenger object with given name
   *   4. Create new Reservation with:
   *        - Unique ID generation
   *        - Status = PENDING
   *        - Flight = f
   *        - Passenger = new Passenger
   *   5. Add reservation to reservations list
   *   6. Add reservation to f.reservations list
   *   7. Return true
   * Input:
   *   - f: Flight to reserve
   *   - passenger: Passenger name (format: string)
   *   - now: Current date and time (format: EDate in yyyy-MM-dd HH:mm:ss)
   * Output: 
   *   - true if successful, false otherwise
   * Pre-condition: f != null, passenger != null, now != null
   * Post-condition: If successful, new reservation created with PENDING status
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public boolean createReservation(final Flight f, final String passenger, final Date now)
  {
    // Check pre-conditions
    if (f == null || passenger == null || now == null) {
      return false;
    }
    
    // Step 1: Check if flight is open for booking
    if (!f.isOpenForBooking()) {
      return false;
    }
    
    // Step 2: Check if current time is before departure time
    if (now.compareTo(f.getDepartureTime()) >= 0) {
      return false;
    }
    
    // Step 3: Create new Passenger object
    Passenger newPassenger = FlightsFactory.eINSTANCE.createPassenger();
    newPassenger.setName(passenger);
    
    // Step 4: Create new Reservation
    Reservation reservation = FlightsFactory.eINSTANCE.createReservation();
    
    // Generate unique ID (using current time in milliseconds)
    reservation.setId("RES_" + System.currentTimeMillis());
    
    // Set status to PENDING (assuming ReservationStatus.PENDING exists)
    reservation.setStatus(ReservationStatus.PENDING);
    
    // Set flight and passenger
    reservation.setFlight(f);
    reservation.setPassenger(newPassenger);
    
    // Step 5: Add reservation to bookings's reservations list
    this.getReservations().add(reservation);
    
    // Step 6: Add reservation to flight's reservations list
    f.getReservations().add(reservation);
    
    // Step 7: Return true
    return true;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case FlightsPackage.BOOKING__RESERVATIONS:
        return ((InternalEList<?>)getReservations()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case FlightsPackage.BOOKING__RESERVATIONS:
        return getReservations();
      case FlightsPackage.BOOKING__CUSTOMER:
        if (resolve) return getCustomer();
        return basicGetCustomer();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case FlightsPackage.BOOKING__RESERVATIONS:
        getReservations().clear();
        getReservations().addAll((Collection<? extends Reservation>)newValue);
        return;
      case FlightsPackage.BOOKING__CUSTOMER:
        setCustomer((Customer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case FlightsPackage.BOOKING__RESERVATIONS:
        getReservations().clear();
        return;
      case FlightsPackage.BOOKING__CUSTOMER:
        setCustomer((Customer)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case FlightsPackage.BOOKING__RESERVATIONS:
        return reservations != null && !reservations.isEmpty();
      case FlightsPackage.BOOKING__CUSTOMER:
        return customer != null;
    }
    return super.eIsSet(featureID);
  }

} // Booking
