/**
 * generated by Enhanced EcoreGen
 */
package edu.company;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.util.InternalEList;
import java.util.HashSet;
import java.util.Set;
import org.eclipse.emf.common.util.BasicEList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Warehouse</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.company.Warehouse#getCity <em>City</em>}</li>
 *   <li>{@link edu.company.Warehouse#getAddress <em>Address</em>}</li>
 *   <li>{@link edu.company.Warehouse#getSurface <em>Surface</em>}</li>
 *   <li>{@link edu.company.Warehouse#getOccupations <em>Occupations</em>}</li>
 *   <li>{@link edu.company.Warehouse#getCompany <em>Company</em>}</li>
 * </ul>
 *
 * @see edu.company.CompanyPackage#getWarehouse()
 * @model kind="class"
 * @generated
 */
public class Warehouse extends MinimalEObjectImpl.Container implements EObject
{
  /**
   * The default value of the '{@link #getCity() <em>City</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCity()
   * @generated
   * @ordered
   */
  protected static final String CITY_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCity() <em>City</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCity()
   * @generated
   * @ordered
   */
  protected String city = CITY_EDEFAULT;

  /**
   * The default value of the '{@link #getAddress() <em>Address</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAddress()
   * @generated
   * @ordered
   */
  protected static final String ADDRESS_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getAddress() <em>Address</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAddress()
   * @generated
   * @ordered
   */
  protected String address = ADDRESS_EDEFAULT;

  /**
   * The default value of the '{@link #getSurface() <em>Surface</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSurface()
   * @generated
   * @ordered
   */
  protected static final double SURFACE_EDEFAULT = 0.0;

  /**
   * The cached value of the '{@link #getSurface() <em>Surface</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSurface()
   * @generated
   * @ordered
   */
  protected double surface = SURFACE_EDEFAULT;

  /**
   * The cached value of the '{@link #getOccupations() <em>Occupations</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOccupations()
   * @generated
   * @ordered
   */
  protected EList<ProductOccupation> occupations;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Warehouse()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CompanyPackage.Literals.WAREHOUSE;
  }

  /**
   * Returns the value of the '<em><b>City</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>City</em>' attribute.
   * @see #setCity(String)
   * @see edu.company.CompanyPackage#getWarehouse_City()
   * @model
   * @generated
   */
  public String getCity()
  {
    return city;
  }

  /**
   * Sets the value of the '{@link edu.company.Warehouse#getCity <em>City</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param newCity the new value of the '<em>City</em>' attribute.
   * @see #getCity()
   * @generated
   */
  public void setCity(String newCity)
  {
    String oldCity = city;
    city = newCity;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CompanyPackage.WAREHOUSE__CITY, oldCity, city));
  }

  /**
   * Returns the value of the '<em><b>Address</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Address</em>' attribute.
   * @see #setAddress(String)
   * @see edu.company.CompanyPackage#getWarehouse_Address()
   * @model
   * @generated
   */
  public String getAddress()
  {
    return address;
  }

  /**
   * Sets the value of the '{@link edu.company.Warehouse#getAddress <em>Address</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param newAddress the new value of the '<em>Address</em>' attribute.
   * @see #getAddress()
   * @generated
   */
  public void setAddress(String newAddress)
  {
    String oldAddress = address;
    address = newAddress;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CompanyPackage.WAREHOUSE__ADDRESS, oldAddress, address));
  }

  /**
   * Returns the value of the '<em><b>Surface</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Surface</em>' attribute.
   * @see #setSurface(double)
   * @see edu.company.CompanyPackage#getWarehouse_Surface()
   * @model
   * @generated
   */
  public double getSurface()
  {
    return surface;
  }

  /**
   * Sets the value of the '{@link edu.company.Warehouse#getSurface <em>Surface</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param newSurface the new value of the '<em>Surface</em>' attribute.
   * @see #getSurface()
   * @generated
   */
  public void setSurface(double newSurface)
  {
    double oldSurface = surface;
    surface = newSurface;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CompanyPackage.WAREHOUSE__SURFACE, oldSurface, surface));
  }

  /**
   * Returns the value of the '<em><b>Occupations</b></em>' containment reference list.
   * The list contents are of type {@link edu.company.ProductOccupation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Occupations</em>' containment reference list.
   * @see edu.company.CompanyPackage#getWarehouse_Occupations()
   * @model containment="true"
   * @generated
   */
  public EList<ProductOccupation> getOccupations()
  {
    if (occupations == null)
    {
      occupations = new EObjectContainmentEList<ProductOccupation>(ProductOccupation.class, this, CompanyPackage.WAREHOUSE__OCCUPATIONS);
    }
    return occupations;
  }

  /**
   * Returns the value of the '<em><b>Company</b></em>' container reference.
   * It is bidirectional and its opposite is '{@link edu.company.Company#getWarehouses <em>Warehouses</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Company</em>' container reference.
   * @see #setCompany(Company)
   * @see edu.company.CompanyPackage#getWarehouse_Company()
   * @see edu.company.Company#getWarehouses
   * @model opposite="warehouses" transient="false"
   * @generated
   */
  public Company getCompany()
  {
    if (eContainerFeatureID() != CompanyPackage.WAREHOUSE__COMPANY) return null;
    return (Company)eInternalContainer();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetCompany(Company newCompany, NotificationChain msgs)
  {
    msgs = eBasicSetContainer(newCompany, CompanyPackage.WAREHOUSE__COMPANY, msgs);
    return msgs;
  }

  /**
   * Sets the value of the '{@link edu.company.Warehouse#getCompany <em>Company</em>}' container reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param newCompany the new value of the '<em>Company</em>' container reference.
   * @see #getCompany()
   * @generated
   */
  public void setCompany(Company newCompany)
  {
    if (newCompany != eInternalContainer() || (eContainerFeatureID() != CompanyPackage.WAREHOUSE__COMPANY && newCompany != null))
    {
      if (EcoreUtil.isAncestor(this, newCompany))
        throw new IllegalArgumentException("Recursive containment not allowed for " + toString());
      NotificationChain msgs = null;
      if (eInternalContainer() != null)
        msgs = eBasicRemoveFromContainer(msgs);
      if (newCompany != null)
        msgs = newCompany.eInverseAdd(this, CompanyPackage.COMPANY__WAREHOUSES, Company.class, msgs);
      msgs = basicSetCompany(newCompany, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CompanyPackage.WAREHOUSE__COMPANY, newCompany, newCompany));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary:
   *   Returns a list of distinct names of toxic products stored in this warehouse.
   * Algorithm:
   *   1. Create a Set<String> toxicNames ← empty.
   *   2. For each ProductOccupation occ in this.getOccupations():
   *        a. Let prod ← occ.getProduct().
   *        b. If prod is not null AND prod.isToxic() returns true:
   *              toxicNames.add(prod.getName()).
   *   3. Convert toxicNames to a List<String> (preserving any order) and return it.
   * Input:
   *   - (none)
   * Output:
   *   - List<String>
   *       Meaning   : names of toxic products present in the warehouse.
   *       Format    : list of unique strings; order is unspecified.
   *       Range     : may be empty if no toxic products are stored or if the
   *                  warehouse has no occupations.
   * Pre-condition:
   *   - This Warehouse instance exists.
   * Post-condition:
   *   - Returned list contains each toxic product name at most once.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public EList<String> retrieveToxicProductNames()
  {
    Set<String> toxicNames = new HashSet<>();
    for (ProductOccupation occ : getOccupations()) {
      Product prod = occ.getProduct();
      if (prod != null && prod.isToxic()) {
        toxicNames.add(prod.getName());
      }
    }
    BasicEList<String> result = new BasicEList<>(toxicNames.size());
    result.addAll(toxicNames);
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary:
   *   Retrieves all distinct Supplier objects whose products are stored in this
   *   warehouse.
   * Algorithm:
   *   1. Create a Set<Supplier> supplierSet ← empty.
   *   2. For each ProductOccupation occ in this.getOccupations():
   *        a. Let prod ← occ.getProduct().
   *        b. If prod is not null:
   *              Let sup ← prod.getSupplier().
   *              If sup is not null, supplierSet.add(sup).
   *   3. Convert supplierSet to a List<Supplier> and return it.
   * Input:
   *   - (none)
   * Output:
   *   - List<Supplier>
   *       Meaning   : distinct suppliers of the products stored in the warehouse.
   *       Format    : list of Supplier references; order unspecified.
   *       Range     : may be empty when the warehouse stores no products.
   * Pre-condition:
   *   - This Warehouse instance exists.
   * Post-condition:
   *   - No duplicate Supplier objects appear in the returned list.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public EList<Supplier> retrieveUniqueSuppliers()
  {
    Set<Supplier> supplierSet = new HashSet<>();
    for (ProductOccupation occ : getOccupations()) {
      Product prod = occ.getProduct();
      if (prod != null) {
        Supplier sup = prod.getSupplier();
        if (sup != null) {
          supplierSet.add(sup);
        }
      }
    }
    BasicEList<Supplier> result = new BasicEList<>(supplierSet.size());
    result.addAll(supplierSet);
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary:
   *   Checks whether this warehouse stores a product whose name matches the
   *   supplied productName.
   * Algorithm:
   *   1. If productName is null, return false.
   *   2. For each ProductOccupation occ in this.getOccupations():
   *        a. Let prod ← occ.getProduct().
   *        b. If prod is not null AND prod.getName().equals(productName):
   *              return true.
   *   3. After the loop, return false.
   * Input:
   *   - productName : String
   *       Meaning   : name of the product to look for.
   *       Format    : any non‑null string (case‑sensitive).
   * Output:
   *   - boolean
   *       Meaning   : true iff a product with the given name is stored in this
   *                  warehouse; false otherwise (including when the warehouse
   *                  or product does not exist).
   * Pre-condition:
   *   - This Warehouse instance exists.
   * Post-condition:
   *   - No side effects; the warehouse's state is unchanged.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public boolean containsProduct(final String productName)
  {
    if (productName == null) {
      return false;
    }
    for (ProductOccupation occ : getOccupations()) {
      Product prod = occ.getProduct();
      if (prod != null && productName.equals(prod.getName())) {
        return true;
      }
    }
    return false;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseAdd(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case CompanyPackage.WAREHOUSE__COMPANY:
        if (eInternalContainer() != null)
          msgs = eBasicRemoveFromContainer(msgs);
        return basicSetCompany((Company)otherEnd, msgs);
    }
    return super.eInverseAdd(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case CompanyPackage.WAREHOUSE__OCCUPATIONS:
        return ((InternalEList<?>)getOccupations()).basicRemove(otherEnd, msgs);
      case CompanyPackage.WAREHOUSE__COMPANY:
        return basicSetCompany(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eBasicRemoveFromContainerFeature(NotificationChain msgs)
  {
    switch (eContainerFeatureID())
    {
      case CompanyPackage.WAREHOUSE__COMPANY:
        return eInternalContainer().eInverseRemove(this, CompanyPackage.COMPANY__WAREHOUSES, Company.class, msgs);
    }
    return super.eBasicRemoveFromContainerFeature(msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case CompanyPackage.WAREHOUSE__CITY:
        return getCity();
      case CompanyPackage.WAREHOUSE__ADDRESS:
        return getAddress();
      case CompanyPackage.WAREHOUSE__SURFACE:
        return getSurface();
      case CompanyPackage.WAREHOUSE__OCCUPATIONS:
        return getOccupations();
      case CompanyPackage.WAREHOUSE__COMPANY:
        return getCompany();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case CompanyPackage.WAREHOUSE__CITY:
        setCity((String)newValue);
        return;
      case CompanyPackage.WAREHOUSE__ADDRESS:
        setAddress((String)newValue);
        return;
      case CompanyPackage.WAREHOUSE__SURFACE:
        setSurface((Double)newValue);
        return;
      case CompanyPackage.WAREHOUSE__OCCUPATIONS:
        getOccupations().clear();
        getOccupations().addAll((Collection<? extends ProductOccupation>)newValue);
        return;
      case CompanyPackage.WAREHOUSE__COMPANY:
        setCompany((Company)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case CompanyPackage.WAREHOUSE__CITY:
        setCity(CITY_EDEFAULT);
        return;
      case CompanyPackage.WAREHOUSE__ADDRESS:
        setAddress(ADDRESS_EDEFAULT);
        return;
      case CompanyPackage.WAREHOUSE__SURFACE:
        setSurface(SURFACE_EDEFAULT);
        return;
      case CompanyPackage.WAREHOUSE__OCCUPATIONS:
        getOccupations().clear();
        return;
      case CompanyPackage.WAREHOUSE__COMPANY:
        setCompany((Company)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case CompanyPackage.WAREHOUSE__CITY:
        return CITY_EDEFAULT == null ? city != null : !CITY_EDEFAULT.equals(city);
      case CompanyPackage.WAREHOUSE__ADDRESS:
        return ADDRESS_EDEFAULT == null ? address != null : !ADDRESS_EDEFAULT.equals(address);
      case CompanyPackage.WAREHOUSE__SURFACE:
        return surface != SURFACE_EDEFAULT;
      case CompanyPackage.WAREHOUSE__OCCUPATIONS:
        return occupations != null && !occupations.isEmpty();
      case CompanyPackage.WAREHOUSE__COMPANY:
        return getCompany() != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (city: ");
    result.append(city);
    result.append(", address: ");
    result.append(address);
    result.append(", surface: ");
    result.append(surface);
    result.append(')');
    return result.toString();
  }

} // Warehouse
