/**
 * generated by Enhanced EcoreGen
 */
package edu.ipo;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Email</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.ipo.Email#getReceiver <em>Receiver</em>}</li>
 *   <li>{@link edu.ipo.Email#getContent <em>Content</em>}</li>
 * </ul>
 *
 * @see edu.ipo.IpoPackage#getEmail()
 * @model kind="class"
 * @generated
 */
public class Email extends MinimalEObjectImpl.Container implements EObject
{
  /**
   * The default value of the '{@link #getReceiver() <em>Receiver</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getReceiver()
   * @generated
   * @ordered
   */
  protected static final String RECEIVER_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getReceiver() <em>Receiver</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getReceiver()
   * @generated
   * @ordered
   */
  protected String receiver = RECEIVER_EDEFAULT;

  /**
   * The default value of the '{@link #getContent() <em>Content</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getContent()
   * @generated
   * @ordered
   */
  protected static final String CONTENT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getContent() <em>Content</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getContent()
   * @generated
   * @ordered
   */
  protected String content = CONTENT_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Email()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return IpoPackage.Literals.EMAIL;
  }

  /**
   * Returns the value of the '<em><b>Receiver</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Receiver</em>' attribute.
   * @see #setReceiver(String)
   * @see edu.ipo.IpoPackage#getEmail_Receiver()
   * @model
   * @generated
   */
  public String getReceiver()
  {
    return receiver;
  }

  /**
   * Sets the value of the '{@link edu.ipo.Email#getReceiver <em>Receiver</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param newReceiver the new value of the '<em>Receiver</em>' attribute.
   * @see #getReceiver()
   * @generated
   */
  public void setReceiver(String newReceiver)
  {
    String oldReceiver = receiver;
    receiver = newReceiver;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IpoPackage.EMAIL__RECEIVER, oldReceiver, receiver));
  }

  /**
   * Returns the value of the '<em><b>Content</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Content</em>' attribute.
   * @see #setContent(String)
   * @see edu.ipo.IpoPackage#getEmail_Content()
   * @model
   * @generated
   */
  public String getContent()
  {
    return content;
  }

  /**
   * Sets the value of the '{@link edu.ipo.Email#getContent <em>Content</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param newContent the new value of the '<em>Content</em>' attribute.
   * @see #getContent()
   * @generated
   */
  public void setContent(String newContent)
  {
    String oldContent = content;
    content = newContent;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IpoPackage.EMAIL__CONTENT, oldContent, content));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Creates the email content for either a confirmation or rejection email.
   * Algorithm:
   * 1. Format the required information into a standardized email template
   * 2. Return the formatted string
   * Input:
   * - company: Company object being applied to
   * - shares: int number of shares applied for
   * - customer: Customer object making the application
   * - amount: double amount of money for the application
   * Output: String - formatted email content including all required information
   * Pre-conditions:
   * - All input parameters must be valid and non-null
   * Post-conditions:
   * - Returns a string containing all required email information in proper format
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public String createEmailContent(final Company company, final int shares, final Customer customer, final double amount)
  {
    StringBuilder emailContent = new StringBuilder();
    emailContent.append("Dear ").append(customer.getName()).append(" ").append(customer.getSurname()).append(",\n\n");

    emailContent.append("Thank you for your application to ").append(company.getName()).append(" IPO.\n");
    emailContent.append("Your application details are as follows:\n");
    emailContent.append("Company: ").append(company.getName()).append("\n");
    emailContent.append("Number of Shares: ").append(shares).append("\n");
    emailContent.append("Total Amount: ").append(amount).append("\n\n");

    emailContent.append("We will process your application and notify you of the outcome shortly.\n\n");
    emailContent.append("Best regards,\n");
    emailContent.append("IPO Application Team\n\n");

    emailContent.append("Contact Information:\n");
    emailContent.append("Email: ").append(company.getEmail()).append("\n");
    emailContent.append("Customer Email: ").append(customer.getEmail()).append("\n");
    emailContent.append("Customer Telephone: ").append(customer.getTelephone()).append("\n");

    return emailContent.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case IpoPackage.EMAIL__RECEIVER:
        return getReceiver();
      case IpoPackage.EMAIL__CONTENT:
        return getContent();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case IpoPackage.EMAIL__RECEIVER:
        setReceiver((String)newValue);
        return;
      case IpoPackage.EMAIL__CONTENT:
        setContent((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case IpoPackage.EMAIL__RECEIVER:
        setReceiver(RECEIVER_EDEFAULT);
        return;
      case IpoPackage.EMAIL__CONTENT:
        setContent(CONTENT_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case IpoPackage.EMAIL__RECEIVER:
        return RECEIVER_EDEFAULT == null ? receiver != null : !RECEIVER_EDEFAULT.equals(receiver);
      case IpoPackage.EMAIL__CONTENT:
        return CONTENT_EDEFAULT == null ? content != null : !CONTENT_EDEFAULT.equals(content);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (receiver: ");
    result.append(receiver);
    result.append(", content: ");
    result.append(content);
    result.append(')');
    return result.toString();
  }

} // Email
