/**
 * generated by Enhanced EcoreGen
 */
package edu.flights;

import java.util.Collection;
import java.util.Date;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectResolvingEList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Airline</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.flights.Airline#getFlights <em>Flights</em>}</li>
 * </ul>
 *
 * @see edu.flights.FlightsPackage#getAirline()
 * @model kind="class"
 * @generated
 */
public class Airline extends MinimalEObjectImpl.Container implements EObject
{
  /**
   * The cached value of the '{@link #getFlights() <em>Flights</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFlights()
   * @generated
   * @ordered
   */
  protected EList<Flight> flights;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Airline()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FlightsPackage.Literals.AIRLINE;
  }

  /**
   * Returns the value of the '<em><b>Flights</b></em>' reference list.
   * The list contents are of type {@link edu.flights.Flight}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Flights</em>' reference list.
   * @see edu.flights.FlightsPackage#getAirline_Flights()
   * @model
   * @generated
   */
  public EList<Flight> getFlights()
  {
    if (flights == null)
    {
      flights = new EObjectResolvingEList<Flight>(Flight.class, this, FlightsPackage.AIRLINE__FLIGHTS);
    }
    return flights;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Adds a flight to the airline's flight list
   * Algorithm: 
   *   1. Check if flight f is not null
   *   2. Add flight f to the flights list
   * Input: 
   *   - f: Flight object to be added
   * Output: 
   *   - void
   * Pre-condition: 
   *   - f != null
   *   - f.id should be unique (not already in flights list)
   * Post-condition: 
   *   - flights list contains flight f
   *   - flights.size() increases by 1
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public void addFlight(final Flight f)
  {
    if (f != null && !getFlights().contains(f)) {
      getFlights().add(f);
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Removes a flight from the airline's flight list
   * Algorithm:
   *   1. Check if flight f exists in flights list
   *   2. Remove flight f from flights list
   * Input:
   *   - f: Flight object to be removed
   * Output:
   *   - void
   * Pre-condition:
   *   - f != null
   *   - f exists in flights list
   * Post-condition:
   *   - flights list no longer contains flight f
   *   - flights.size() decreases by 1
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public void removeFlight(final Flight f)
  {
    if (f != null && getFlights().contains(f)) {
      getFlights().remove(f);
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Publishes a flight to make it available for booking
   * Algorithm:
   *   1. Check if flight has valid timestamps (yyyy-MM-dd HH:mm:ss format)
   *   2. Verify currentTime < departureTime < arrivalTime
   *   3. Check departureAirport ≠ arrivalAirport
   *   4. Ensure flight is not already published (openForBooking = false)
   *   5. Set flight.openForBooking = true
   *   6. Return true
   *   7. If any check fails, return false
   * Input:
   *   - f: Flight object to be published
   *   - now: EDate representing current date and time (format: yyyy-MM-dd HH:mm:ss)
   * Output:
   *   - boolean: true if successful, false otherwise
   * Pre-condition:
   *   - f != null
   *   - f has valid departureAirport and arrivalAirport
   *   - now is valid timestamp
   * Post-condition:
   *   - If successful: flight.openForBooking = true
   *   - If unsuccessful: flight status remains unchanged
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public boolean publishFlight(final Flight f, final Date now)
  {
    if (f == null || now == null) {
      return false;
    }
    
    Date departureTime = f.getDepartureTime();
    Date arrivalTime = f.getArrivalTime();
    
    if (departureTime == null || arrivalTime == null) {
      return false;
    }
    
    if (now.compareTo(departureTime) >= 0 || departureTime.compareTo(arrivalTime) >= 0) {
      return false;
    }
    
    Airport departureAirport = f.getDepartureAirport();
    Airport arrivalAirport = f.getArrialAirport();
    
    if (departureAirport == null || arrivalAirport == null || departureAirport.equals(arrivalAirport)) {
      return false;
    }
    
    if (f.isOpenForBooking()) {
      return false;
    }
    
    f.setOpenForBooking(true);
    return true;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Closes an open flight that has not yet departed
   * Algorithm:
   *   1. Find flight by flightId
   *   2. If flight exists, is open, and departureTime > now
   *   3. Set flight.openForBooking = false
   *   4. For each reservation in flight.reservations:
   *        if reservation.status is CONFIRMED, set to CANCELED
   *   5. Return true
   *   6. Else return false
   * Input:
   *   - flightId: String identifying the flight (format: unique flight identifier)
   *   - now: EDate representing current date and time (format: yyyy-MM-dd HH:mm:ss)
   * Output:
   *   - boolean: true if successful, false otherwise
   * Pre-condition:
   *   - flightId exists in flights list
   *   - now is valid timestamp
   * Post-condition:
   *   - If successful: flight is closed and confirmed reservations are canceled
   *   - If unsuccessful: flight status remains unchanged
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public boolean closeFlight(final String flightId, final Date now)
  {
    if (flightId == null || now == null) {
      return false;
    }
    
    for (Flight flight : getFlights()) {
      if (flightId.equals(flight.getId())) {
        if (flight.isOpenForBooking() && flight.getDepartureTime().compareTo(now) > 0) {
          flight.setOpenForBooking(false);
          
          // Note: The actual implementation would need to access reservation status
          // and set confirmed reservations to CANCELED, but the context doesn't provide
          // the necessary Reservation class methods to do this
          return true;
        }
      }
    }
    
    return false;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Searches for flights by origin, destination, and date
   * Algorithm:
   *   1. Filter flights list by:
   *      - departureAirport serves origin city OR airport id matches origin
   *      - arrivalAirport serves destination city OR airport id matches destination  
   *      - departureTime matches the specified date (same day)
   *   2. Return matching flights
   * Input:
   *   - origin: String representing origin city name or airport id
   *   - date: EDate representing departure date (format: yyyy-MM-dd)
   *   - dest: String representing destination city name or airport id
   * Output:
   *   - List<Flight>: list of matching flights, empty if none found
   * Pre-condition:
   *   - origin and dest are not null
   *   - date is valid date
   * Post-condition:
   *   - Returned list contains all flights matching the criteria
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public EList<Flight> searchFlights(final String origin, final Date date, final String dest)
  {
    EList<Flight> result = new BasicEList<>();
    
    if (origin == null || date == null || dest == null) {
      return result;
    }
    
    for (Flight flight : getFlights()) {
      Airport departureAirport = flight.getDepartureAirport();
      Airport arrivalAirport = flight.getArrialAirport();
      Date departureTime = flight.getDepartureTime();
      
      if (departureAirport == null || arrivalAirport == null || departureTime == null) {
      continue;
      }
      
      // Check origin match (city name or airport id)
      boolean originMatch = origin.equals(departureAirport.getId()) || 
             origin.equalsIgnoreCase(departureAirport.getCity());
      
      // Check destination match (city name or airport id)
      boolean destMatch = dest.equals(arrivalAirport.getId()) || 
             dest.equalsIgnoreCase(arrivalAirport.getCity());
      
      // Check date match (same day)
      boolean dateMatch = departureTime.getYear() == date.getYear() &&
                    departureTime.getMonth() == date.getMonth() &&
                    departureTime.getDate() == date.getDate();
      
      if (originMatch && destMatch && dateMatch) {
        result.add(flight);
      }
    }
    
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case FlightsPackage.AIRLINE__FLIGHTS:
        return getFlights();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case FlightsPackage.AIRLINE__FLIGHTS:
        getFlights().clear();
        getFlights().addAll((Collection<? extends Flight>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case FlightsPackage.AIRLINE__FLIGHTS:
        getFlights().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case FlightsPackage.AIRLINE__FLIGHTS:
        return flights != null && !flights.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} // Airline
