/**
 * generated by Enhanced EcoreGen
 */
package edu.postal;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.EObjectResolvingEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Geographical Area</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.postal.GeographicalArea#getMailmen <em>Mailmen</em>}</li>
 *   <li>{@link edu.postal.GeographicalArea#getInhabitants <em>Inhabitants</em>}</li>
 *   <li>{@link edu.postal.GeographicalArea#getAllMails <em>All Mails</em>}</li>
 * </ul>
 *
 * @see edu.postal.PostalPackage#getGeographicalArea()
 * @model kind="class"
 * @generated
 */
public class GeographicalArea extends MinimalEObjectImpl.Container implements EObject
{
  /**
   * The cached value of the '{@link #getMailmen() <em>Mailmen</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMailmen()
   * @generated
   * @ordered
   */
  protected EList<Mailman> mailmen;

  /**
   * The cached value of the '{@link #getInhabitants() <em>Inhabitants</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInhabitants()
   * @generated
   * @ordered
   */
  protected EList<Inhabitant> inhabitants;

  /**
   * The cached value of the '{@link #getAllMails() <em>All Mails</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAllMails()
   * @generated
   * @ordered
   */
  protected EList<RegisteredMail> allMails;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GeographicalArea()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PostalPackage.Literals.GEOGRAPHICAL_AREA;
  }

  /**
   * Returns the value of the '<em><b>Mailmen</b></em>' containment reference list.
   * The list contents are of type {@link edu.postal.Mailman}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mailmen</em>' containment reference list.
   * @see edu.postal.PostalPackage#getGeographicalArea_Mailmen()
   * @model containment="true"
   * @generated
   */
  public EList<Mailman> getMailmen()
  {
    if (mailmen == null)
    {
      mailmen = new EObjectContainmentEList<Mailman>(Mailman.class, this, PostalPackage.GEOGRAPHICAL_AREA__MAILMEN);
    }
    return mailmen;
  }

  /**
   * Returns the value of the '<em><b>Inhabitants</b></em>' containment reference list.
   * The list contents are of type {@link edu.postal.Inhabitant}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Inhabitants</em>' containment reference list.
   * @see edu.postal.PostalPackage#getGeographicalArea_Inhabitants()
   * @model containment="true"
   * @generated
   */
  public EList<Inhabitant> getInhabitants()
  {
    if (inhabitants == null)
    {
      inhabitants = new EObjectContainmentEList<Inhabitant>(Inhabitant.class, this, PostalPackage.GEOGRAPHICAL_AREA__INHABITANTS);
    }
    return inhabitants;
  }

  /**
   * Returns the value of the '<em><b>All Mails</b></em>' reference list.
   * The list contents are of type {@link edu.postal.RegisteredMail}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>All Mails</em>' reference list.
   * @see edu.postal.PostalPackage#getGeographicalArea_AllMails()
   * @model
   * @generated
   */
  public EList<RegisteredMail> getAllMails()
  {
    if (allMails == null)
    {
      allMails = new EObjectResolvingEList<RegisteredMail>(RegisteredMail.class, this, PostalPackage.GEOGRAPHICAL_AREA__ALL_MAILS);
    }
    return allMails;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Returns all registered mail items in the geographical area
   * Algorithm:
   *   1. Return allMails list
   * Input: None
   * Output:
   *   - List<RegisteredMail> containing all registered mail items
   *   - Format: List of RegisteredMail objects (letters and parcels)
   *   - Value range: May be empty list
   * Pre-condition: Geographical area exists
   * Post-condition: Returns current state of allMails
   * <!-- end-model-doc -->
   * @model kind="operation"
   *        annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public EList<RegisteredMail> getAllDeliveries()
  {
    return getAllMails();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Adds a new inhabitant to the geographical area
   * Algorithm:
   *   1. Check if newInhabitant is not null
   *   2. Check if newInhabitant is not already in inhabitants list
   *   3. Add newInhabitant to inhabitants list
   *   4. Return true if successful
   * Input: 
   *   - newInhabitant: Inhabitant object to be added
   *   - Format: Inhabitant instance
   *   - Value range: Non-null, valid Inhabitant object
   * Output: 
   *   - Boolean indicating success (true) or failure (false)
   * Pre-condition: Geographical area exists and is valid
   * Post-condition: If successful, inhabitants list contains newInhabitant
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public boolean addInhabitant(final Inhabitant newInhabitant)
  {
    if (newInhabitant == null) {
      return false;
    }
    if (getInhabitants().contains(newInhabitant)) {
      return false;
    }
    return getInhabitants().add(newInhabitant);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Removes an inhabitant from the geographical area and deletes their assigned mail
   * Algorithm:
   *   1. Check if inhabitantToRemove is not null
   *   2. Check if inhabitantToRemove exists in inhabitants list
   *   3. Find all mail items where addressee equals inhabitantToRemove AND carrier is assigned
   *   4. Remove all found mail items from allMails list
   *   5. Remove inhabitantToRemove from inhabitants list
   *   6. Return true if successful
   * Input:
   *   - inhabitantToRemove: Inhabitant to be removed
   *   - Format: Inhabitant instance
   *   - Value range: Non-null, valid Inhabitant object
   * Output:
   *   - Boolean indicating removal success (true) or failure (false)
   * Pre-condition: Inhabitant exists in geographical area
   * Post-condition: If successful, inhabitant is removed and their assigned mail is deleted
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public boolean removeInhabitant(final Inhabitant inhabitantToRemove)
  {
    if (inhabitantToRemove == null) {
      return false;
    }
    if (!getInhabitants().contains(inhabitantToRemove)) {
      return false;
    }
    
    // Find and remove all mail items where addressee equals inhabitantToRemove AND carrier is assigned
    EList<RegisteredMail> mailsToRemove = new EObjectResolvingEList<RegisteredMail>(RegisteredMail.class, this, PostalPackage.GEOGRAPHICAL_AREA__ALL_MAILS);
    for (RegisteredMail mail : getAllMails()) {
      if (inhabitantToRemove.equals(mail.getAddressee()) && mail.getCarrier() != null) {
        mailsToRemove.add(mail);
      }
    }
    getAllMails().removeAll(mailsToRemove);
    
    return getInhabitants().remove(inhabitantToRemove);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Adds a new mailman to the geographical area
   * Algorithm:
   *   1. Check if newMailman is not null
   *   2. Check if newMailman is not already in mailmen list
   *   3. Add newMailman to mailmen list
   *   4. Return true if successful
   * Input:
   *   - newMailman: Mailman object to be added
   *   - Format: Mailman instance
   *   - Value range: Non-null, valid Mailman object
   * Output:
   *   - Boolean indicating success (true) or failure (false)
   * Pre-condition: Geographical area exists and is valid
   * Post-condition: If successful, mailmen list contains newMailman
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public boolean addMailman(final Mailman newMailman)
  {
    if (newMailman == null) {
      return false;
    }
    if (getMailmen().contains(newMailman)) {
      return false;
    }
    return getMailmen().add(newMailman);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Removes a mailman from the geographical area after reassigning their deliveries
   * Algorithm:
   *   1. Check if mailmanToRemove and newMailman are not null
   *   2. Check if mailmanToRemove exists in mailmen list
   *   3. Check if newMailman exists in mailmen list and is different from mailmanToRemove
   *   4. Check if there is at least one other mailman in the area
   *   5. Find all mail items assigned to mailmanToRemove
   *   6. Reassign all found mail items to newMailman
   *   7. Remove mailmanToRemove from mailmen list
   *   8. Return true if successful
   * Input:
   *   - mailmanToRemove: Mailman to be removed
   *   - newMailman: Mailman who will take over deliveries
   *   - Format: Both are Mailman instances
   *   - Value range: Non-null, valid Mailman objects, must be different
   * Output:
   *   - Boolean indicating removal success (true) or failure (false)
   * Pre-condition: Both mailmen exist in geographical area and there are multiple mailmen
   * Post-condition: If successful, mailmanToRemove is removed and their mail is reassigned
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public boolean removeMailman(final Mailman mailmanToRemove, final Mailman newMailman)
  {
    if (mailmanToRemove == null || newMailman == null) {
      return false;
    }
    if (!getMailmen().contains(mailmanToRemove)) {
      return false;
    }
    if (!getMailmen().contains(newMailman) || mailmanToRemove.equals(newMailman)) {
      return false;
    }
    if (getMailmen().size() <= 1) {
      return false;
    }
    
    // Find all mail items assigned to mailmanToRemove and reassign them to newMailman
    for (RegisteredMail mail : getAllMails()) {
      if (mailmanToRemove.equals(mail.getCarrier())) {
        mail.setCarrier(newMailman);
      }
    }
    
    return getMailmen().remove(mailmanToRemove);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Assigns a specific mailman to deliver registered mail to an inhabitant
   * Algorithm:
   *   1. Verify carrier, addressee, and mail are not null
   *   2. Check if carrier belongs to this geographical area
   *   3. Check if addressee belongs to this geographical area
   *   4. Check if mail is not already assigned to any mailman
   *   5. Assign carrier to mail as the deliverer
   *   6. Add mail to allMails list if not already present
   *   7. Return true if assignment successful
   * Input:
   *   - carrier: Mailman assigned to deliver the mail
   *   - addressee: Inhabitant receiving the mail
   *   - mail: RegisteredMail item to be delivered
   *   - Format: Valid Mailman, Inhabitant, and RegisteredMail objects
   *   - Value range: All parameters non-null
   * Output:
   *   - Boolean indicating assignment success (true) or failure (false)
   * Pre-condition: All parameters exist and are valid
   * Post-condition: If successful, mail has carrier assigned and is in allMails
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public boolean assignRegisteredMailDeliver(final Mailman carrier, final Inhabitant addressee, final RegisteredMail mail)
  {
    if (carrier == null || addressee == null || mail == null) {
      return false;
    }
    if (!getMailmen().contains(carrier)) {
      return false;
    }
    if (!getInhabitants().contains(addressee)) {
      return false;
    }
    if (mail.getCarrier() != null) {
      return false;
    }
    
    mail.setCarrier(carrier);
    mail.setAddressee(addressee);
    
    if (!getAllMails().contains(mail)) {
      getAllMails().add(mail);
    }
    
    return true;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Lists all registered mail items assigned to a specified mailman
   * Algorithm:
   *   1. Check if carrier is not null
   *   2. Filter allMails to find items where carrier equals specified mailman
   *   3. If no items found, return null
   *   4. Return list of filtered mail items
   * Input:
   *   - carrier: Mailman to filter mail items for
   *   - Format: Mailman instance
   *   - Value range: Non-null Mailman object
   * Output:
   *   - List<RegisteredMail> containing mail assigned to the carrier
   *   - Format: List of RegisteredMail objects
   *   - Value range: Returns null if no mail found for carrier
   * Pre-condition: Carrier exists and geographical area is valid
   * Post-condition: Returned list contains only mail assigned to specified carrier
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public EList<RegisteredMail> listRegisteredMail(final Mailman carrier)
  {
    if (carrier == null) {
      return null;
    }
    
    EList<RegisteredMail> result = new EObjectResolvingEList<RegisteredMail>(RegisteredMail.class, this, PostalPackage.GEOGRAPHICAL_AREA__ALL_MAILS);
    for (RegisteredMail mail : getAllMails()) {
      if (carrier.equals(mail.getCarrier())) {
        result.add(mail);
      }
    }
    
    return result.isEmpty() ? null : result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Lists all registered mail items directed to a specified inhabitant
   * Algorithm:
   *   1. Check if addressee is not null
   *   2. Filter allMails to find items where addressee equals specified inhabitant
   *   3. If no items found, return null
   *   4. Return list of filtered mail items
   * Input:
   *   - addressee: Inhabitant to filter mail items for
   *   - Format: Inhabitant instance
   *   - Value range: Non-null Inhabitant object
   * Output:
   *   - List<RegisteredMail> containing mail addressed to the inhabitant
   *   - Format: List of RegisteredMail objects
   *   - Value range: Returns null if no mail found for inhabitant
   * Pre-condition: Addressee exists and geographical area is valid
   * Post-condition: Returned list contains only mail addressed to specified inhabitant
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public EList<RegisteredMail> listRegisteredMailWithInhabitant(final Inhabitant addressee)
  {
    if (addressee == null) {
      return null;
    }
    
    EList<RegisteredMail> result = new EObjectResolvingEList<RegisteredMail>(RegisteredMail.class, this, PostalPackage.GEOGRAPHICAL_AREA__ALL_MAILS);
    for (RegisteredMail mail : getAllMails()) {
      if (addressee.equals(mail.getAddressee())) {
        result.add(mail);
      }
    }
    
    return result.isEmpty() ? null : result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PostalPackage.GEOGRAPHICAL_AREA__MAILMEN:
        return ((InternalEList<?>)getMailmen()).basicRemove(otherEnd, msgs);
      case PostalPackage.GEOGRAPHICAL_AREA__INHABITANTS:
        return ((InternalEList<?>)getInhabitants()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PostalPackage.GEOGRAPHICAL_AREA__MAILMEN:
        return getMailmen();
      case PostalPackage.GEOGRAPHICAL_AREA__INHABITANTS:
        return getInhabitants();
      case PostalPackage.GEOGRAPHICAL_AREA__ALL_MAILS:
        return getAllMails();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PostalPackage.GEOGRAPHICAL_AREA__MAILMEN:
        getMailmen().clear();
        getMailmen().addAll((Collection<? extends Mailman>)newValue);
        return;
      case PostalPackage.GEOGRAPHICAL_AREA__INHABITANTS:
        getInhabitants().clear();
        getInhabitants().addAll((Collection<? extends Inhabitant>)newValue);
        return;
      case PostalPackage.GEOGRAPHICAL_AREA__ALL_MAILS:
        getAllMails().clear();
        getAllMails().addAll((Collection<? extends RegisteredMail>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PostalPackage.GEOGRAPHICAL_AREA__MAILMEN:
        getMailmen().clear();
        return;
      case PostalPackage.GEOGRAPHICAL_AREA__INHABITANTS:
        getInhabitants().clear();
        return;
      case PostalPackage.GEOGRAPHICAL_AREA__ALL_MAILS:
        getAllMails().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PostalPackage.GEOGRAPHICAL_AREA__MAILMEN:
        return mailmen != null && !mailmen.isEmpty();
      case PostalPackage.GEOGRAPHICAL_AREA__INHABITANTS:
        return inhabitants != null && !inhabitants.isEmpty();
      case PostalPackage.GEOGRAPHICAL_AREA__ALL_MAILS:
        return allMails != null && !allMails.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} // GeographicalArea
