/**
 * generated by Enhanced EcoreGen
 */
package edu.project;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see edu.project.ProjectFactory
 * @model kind="package"
 *        annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen requirement='A company is comprised of two to eight departments. Each department has an ID and email. A department hires employees for certain projects. Employees working on projects can be temporary employees or permanent employees. \nEach employee is identified by a name, email, employee ID, employee number. Projects can be of types - production projects, research projects, education projects, and community projects. All projects have a title, description, budget amount, and deadline. In addition, each education project and community project are associated with one funding group. The funding group can be of types - private group, government group, or mixed group. \nThe production projects are characterized by a site code.\nfunctional requirement\uff1a\n+ \"Total budget of all projects in a company\" : Calculate the sum of the budget amounts of all projects in all departments of a company. \n\n+ \"Average budget of all projects in a department\" : Calculate the average budget amount of all projects in a given department.\n\n+ \"Number of employees working on production projects in a company\" : Count the total number of employees working on production projects across all departments in a company. \n\n+ \"Funding group type of all community projects in a department\" : Retrieve the funding group type of all community projects within a given department.'"
 * @generated
 */
public class ProjectPackage extends EPackageImpl
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final String eNAME = "project";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final String eNS_URI = "http://www.example.org/project";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final String eNS_PREFIX = "project";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final ProjectPackage eINSTANCE = edu.project.ProjectPackage.init();

  /**
   * The meta object id for the '{@link edu.project.Company <em>Company</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.project.Company
   * @see edu.project.ProjectPackage#getCompany()
   * @generated
   */
  public static final int COMPANY = 0;

  /**
   * The feature id for the '<em><b>Departments</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int COMPANY__DEPARTMENTS = 0;

  /**
   * The number of structural features of the '<em>Company</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int COMPANY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link edu.project.Department <em>Department</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.project.Department
   * @see edu.project.ProjectPackage#getDepartment()
   * @generated
   */
  public static final int DEPARTMENT = 1;

  /**
   * The feature id for the '<em><b>ID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int DEPARTMENT__ID = 0;

  /**
   * The feature id for the '<em><b>Email</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int DEPARTMENT__EMAIL = 1;

  /**
   * The feature id for the '<em><b>Employees</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int DEPARTMENT__EMPLOYEES = 2;

  /**
   * The feature id for the '<em><b>Company</b></em>' container reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int DEPARTMENT__COMPANY = 3;

  /**
   * The feature id for the '<em><b>Projects</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int DEPARTMENT__PROJECTS = 4;

  /**
   * The number of structural features of the '<em>Department</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int DEPARTMENT_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link edu.project.Employee <em>Employee</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.project.Employee
   * @see edu.project.ProjectPackage#getEmployee()
   * @generated
   */
  public static final int EMPLOYEE = 2;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int EMPLOYEE__TYPE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int EMPLOYEE__NAME = 1;

  /**
   * The feature id for the '<em><b>Email</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int EMPLOYEE__EMAIL = 2;

  /**
   * The feature id for the '<em><b>ID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int EMPLOYEE__ID = 3;

  /**
   * The feature id for the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int EMPLOYEE__NUMBER = 4;

  /**
   * The feature id for the '<em><b>Department</b></em>' container reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int EMPLOYEE__DEPARTMENT = 5;

  /**
   * The number of structural features of the '<em>Employee</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int EMPLOYEE_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link edu.project.Project <em>Project</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.project.Project
   * @see edu.project.ProjectPackage#getProject()
   * @generated
   */
  public static final int PROJECT = 3;

  /**
   * The feature id for the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int PROJECT__TITLE = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int PROJECT__DESCRIPTION = 1;

  /**
   * The feature id for the '<em><b>Budget</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int PROJECT__BUDGET = 2;

  /**
   * The feature id for the '<em><b>Deadline</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int PROJECT__DEADLINE = 3;

  /**
   * The feature id for the '<em><b>Department</b></em>' container reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int PROJECT__DEPARTMENT = 4;

  /**
   * The feature id for the '<em><b>Working Employees</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int PROJECT__WORKING_EMPLOYEES = 5;

  /**
   * The number of structural features of the '<em>Project</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int PROJECT_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link edu.project.ProductionProject <em>Production Project</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.project.ProductionProject
   * @see edu.project.ProjectPackage#getProductionProject()
   * @generated
   */
  public static final int PRODUCTION_PROJECT = 4;

  /**
   * The feature id for the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int PRODUCTION_PROJECT__TITLE = PROJECT__TITLE;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int PRODUCTION_PROJECT__DESCRIPTION = PROJECT__DESCRIPTION;

  /**
   * The feature id for the '<em><b>Budget</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int PRODUCTION_PROJECT__BUDGET = PROJECT__BUDGET;

  /**
   * The feature id for the '<em><b>Deadline</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int PRODUCTION_PROJECT__DEADLINE = PROJECT__DEADLINE;

  /**
   * The feature id for the '<em><b>Department</b></em>' container reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int PRODUCTION_PROJECT__DEPARTMENT = PROJECT__DEPARTMENT;

  /**
   * The feature id for the '<em><b>Working Employees</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int PRODUCTION_PROJECT__WORKING_EMPLOYEES = PROJECT__WORKING_EMPLOYEES;

  /**
   * The feature id for the '<em><b>Site Code</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int PRODUCTION_PROJECT__SITE_CODE = PROJECT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Production Project</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int PRODUCTION_PROJECT_FEATURE_COUNT = PROJECT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.project.ResearchProject <em>Research Project</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.project.ResearchProject
   * @see edu.project.ProjectPackage#getResearchProject()
   * @generated
   */
  public static final int RESEARCH_PROJECT = 5;

  /**
   * The feature id for the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int RESEARCH_PROJECT__TITLE = PROJECT__TITLE;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int RESEARCH_PROJECT__DESCRIPTION = PROJECT__DESCRIPTION;

  /**
   * The feature id for the '<em><b>Budget</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int RESEARCH_PROJECT__BUDGET = PROJECT__BUDGET;

  /**
   * The feature id for the '<em><b>Deadline</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int RESEARCH_PROJECT__DEADLINE = PROJECT__DEADLINE;

  /**
   * The feature id for the '<em><b>Department</b></em>' container reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int RESEARCH_PROJECT__DEPARTMENT = PROJECT__DEPARTMENT;

  /**
   * The feature id for the '<em><b>Working Employees</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int RESEARCH_PROJECT__WORKING_EMPLOYEES = PROJECT__WORKING_EMPLOYEES;

  /**
   * The number of structural features of the '<em>Research Project</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int RESEARCH_PROJECT_FEATURE_COUNT = PROJECT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link edu.project.EducationProject <em>Education Project</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.project.EducationProject
   * @see edu.project.ProjectPackage#getEducationProject()
   * @generated
   */
  public static final int EDUCATION_PROJECT = 6;

  /**
   * The feature id for the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int EDUCATION_PROJECT__TITLE = PROJECT__TITLE;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int EDUCATION_PROJECT__DESCRIPTION = PROJECT__DESCRIPTION;

  /**
   * The feature id for the '<em><b>Budget</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int EDUCATION_PROJECT__BUDGET = PROJECT__BUDGET;

  /**
   * The feature id for the '<em><b>Deadline</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int EDUCATION_PROJECT__DEADLINE = PROJECT__DEADLINE;

  /**
   * The feature id for the '<em><b>Department</b></em>' container reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int EDUCATION_PROJECT__DEPARTMENT = PROJECT__DEPARTMENT;

  /**
   * The feature id for the '<em><b>Working Employees</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int EDUCATION_PROJECT__WORKING_EMPLOYEES = PROJECT__WORKING_EMPLOYEES;

  /**
   * The feature id for the '<em><b>Fundinggroup</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int EDUCATION_PROJECT__FUNDINGGROUP = PROJECT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Education Project</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int EDUCATION_PROJECT_FEATURE_COUNT = PROJECT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.project.CommunityProject <em>Community Project</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.project.CommunityProject
   * @see edu.project.ProjectPackage#getCommunityProject()
   * @generated
   */
  public static final int COMMUNITY_PROJECT = 7;

  /**
   * The feature id for the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int COMMUNITY_PROJECT__TITLE = PROJECT__TITLE;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int COMMUNITY_PROJECT__DESCRIPTION = PROJECT__DESCRIPTION;

  /**
   * The feature id for the '<em><b>Budget</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int COMMUNITY_PROJECT__BUDGET = PROJECT__BUDGET;

  /**
   * The feature id for the '<em><b>Deadline</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int COMMUNITY_PROJECT__DEADLINE = PROJECT__DEADLINE;

  /**
   * The feature id for the '<em><b>Department</b></em>' container reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int COMMUNITY_PROJECT__DEPARTMENT = PROJECT__DEPARTMENT;

  /**
   * The feature id for the '<em><b>Working Employees</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int COMMUNITY_PROJECT__WORKING_EMPLOYEES = PROJECT__WORKING_EMPLOYEES;

  /**
   * The feature id for the '<em><b>Fuding Group</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int COMMUNITY_PROJECT__FUDING_GROUP = PROJECT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Community Project</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int COMMUNITY_PROJECT_FEATURE_COUNT = PROJECT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.project.FundingGroup <em>Funding Group</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.project.FundingGroup
   * @see edu.project.ProjectPackage#getFundingGroup()
   * @generated
   */
  public static final int FUNDING_GROUP = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int FUNDING_GROUP__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int FUNDING_GROUP__TYPE = 1;

  /**
   * The feature id for the '<em><b>Funding Groupedu</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int FUNDING_GROUP__FUNDING_GROUPEDU = 2;

  /**
   * The feature id for the '<em><b>Funding Group</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int FUNDING_GROUP__FUNDING_GROUP = 3;

  /**
   * The number of structural features of the '<em>Funding Group</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  public static final int FUNDING_GROUP_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link edu.project.EmployeeType <em>Employee Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.project.EmployeeType
   * @see edu.project.ProjectPackage#getEmployeeType()
   * @generated
   */
  public static final int EMPLOYEE_TYPE = 9;

  /**
   * The meta object id for the '{@link edu.project.FundingGroupType <em>Funding Group Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.project.FundingGroupType
   * @see edu.project.ProjectPackage#getFundingGroupType()
   * @generated
   */
  public static final int FUNDING_GROUP_TYPE = 10;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass companyEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass departmentEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass employeeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass projectEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass productionProjectEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass researchProjectEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass educationProjectEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass communityProjectEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass fundingGroupEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum employeeTypeEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum fundingGroupTypeEEnum = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see edu.project.ProjectPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private ProjectPackage()
  {
    super(eNS_URI, ProjectFactory.eINSTANCE);
  }
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link ProjectPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static ProjectPackage init()
  {
    if (isInited) return (ProjectPackage)EPackage.Registry.INSTANCE.getEPackage(ProjectPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredProjectPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    ProjectPackage theProjectPackage = registeredProjectPackage instanceof ProjectPackage ? (ProjectPackage)registeredProjectPackage : new ProjectPackage();

    isInited = true;

    // Create package meta-data objects
    theProjectPackage.createPackageContents();

    // Initialize created meta-data
    theProjectPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theProjectPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(ProjectPackage.eNS_URI, theProjectPackage);
    return theProjectPackage;
  }


  /**
   * Returns the meta object for class '{@link edu.project.Company <em>Company</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Company</em>'.
   * @see edu.project.Company
   * @generated
   */
  public EClass getCompany()
  {
    return companyEClass;
  }

  /**
   * Returns the meta object for the containment reference list '{@link edu.project.Company#getDepartments <em>Departments</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Departments</em>'.
   * @see edu.project.Company#getDepartments()
   * @see #getCompany()
   * @generated
   */
  public EReference getCompany_Departments()
  {
    return (EReference)companyEClass.getEStructuralFeatures().get(0);
  }

  /**
   * Returns the meta object for class '{@link edu.project.Department <em>Department</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Department</em>'.
   * @see edu.project.Department
   * @generated
   */
  public EClass getDepartment()
  {
    return departmentEClass;
  }

  /**
   * Returns the meta object for the attribute '{@link edu.project.Department#getID <em>ID</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>ID</em>'.
   * @see edu.project.Department#getID()
   * @see #getDepartment()
   * @generated
   */
  public EAttribute getDepartment_ID()
  {
    return (EAttribute)departmentEClass.getEStructuralFeatures().get(0);
  }

  /**
   * Returns the meta object for the attribute '{@link edu.project.Department#getEmail <em>Email</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Email</em>'.
   * @see edu.project.Department#getEmail()
   * @see #getDepartment()
   * @generated
   */
  public EAttribute getDepartment_Email()
  {
    return (EAttribute)departmentEClass.getEStructuralFeatures().get(1);
  }

  /**
   * Returns the meta object for the containment reference list '{@link edu.project.Department#getEmployees <em>Employees</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Employees</em>'.
   * @see edu.project.Department#getEmployees()
   * @see #getDepartment()
   * @generated
   */
  public EReference getDepartment_Employees()
  {
    return (EReference)departmentEClass.getEStructuralFeatures().get(2);
  }

  /**
   * Returns the meta object for the container reference '{@link edu.project.Department#getCompany <em>Company</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the container reference '<em>Company</em>'.
   * @see edu.project.Department#getCompany()
   * @see #getDepartment()
   * @generated
   */
  public EReference getDepartment_Company()
  {
    return (EReference)departmentEClass.getEStructuralFeatures().get(3);
  }

  /**
   * Returns the meta object for the containment reference list '{@link edu.project.Department#getProjects <em>Projects</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Projects</em>'.
   * @see edu.project.Department#getProjects()
   * @see #getDepartment()
   * @generated
   */
  public EReference getDepartment_Projects()
  {
    return (EReference)departmentEClass.getEStructuralFeatures().get(4);
  }

  /**
   * Returns the meta object for class '{@link edu.project.Employee <em>Employee</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Employee</em>'.
   * @see edu.project.Employee
   * @generated
   */
  public EClass getEmployee()
  {
    return employeeEClass;
  }

  /**
   * Returns the meta object for the attribute '{@link edu.project.Employee#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see edu.project.Employee#getType()
   * @see #getEmployee()
   * @generated
   */
  public EAttribute getEmployee_Type()
  {
    return (EAttribute)employeeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * Returns the meta object for the attribute '{@link edu.project.Employee#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see edu.project.Employee#getName()
   * @see #getEmployee()
   * @generated
   */
  public EAttribute getEmployee_Name()
  {
    return (EAttribute)employeeEClass.getEStructuralFeatures().get(1);
  }

  /**
   * Returns the meta object for the attribute '{@link edu.project.Employee#getEmail <em>Email</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Email</em>'.
   * @see edu.project.Employee#getEmail()
   * @see #getEmployee()
   * @generated
   */
  public EAttribute getEmployee_Email()
  {
    return (EAttribute)employeeEClass.getEStructuralFeatures().get(2);
  }

  /**
   * Returns the meta object for the attribute '{@link edu.project.Employee#getID <em>ID</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>ID</em>'.
   * @see edu.project.Employee#getID()
   * @see #getEmployee()
   * @generated
   */
  public EAttribute getEmployee_ID()
  {
    return (EAttribute)employeeEClass.getEStructuralFeatures().get(3);
  }

  /**
   * Returns the meta object for the attribute '{@link edu.project.Employee#getNumber <em>Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Number</em>'.
   * @see edu.project.Employee#getNumber()
   * @see #getEmployee()
   * @generated
   */
  public EAttribute getEmployee_Number()
  {
    return (EAttribute)employeeEClass.getEStructuralFeatures().get(4);
  }

  /**
   * Returns the meta object for the container reference '{@link edu.project.Employee#getDepartment <em>Department</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the container reference '<em>Department</em>'.
   * @see edu.project.Employee#getDepartment()
   * @see #getEmployee()
   * @generated
   */
  public EReference getEmployee_Department()
  {
    return (EReference)employeeEClass.getEStructuralFeatures().get(5);
  }

  /**
   * Returns the meta object for class '{@link edu.project.Project <em>Project</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Project</em>'.
   * @see edu.project.Project
   * @generated
   */
  public EClass getProject()
  {
    return projectEClass;
  }

  /**
   * Returns the meta object for the attribute '{@link edu.project.Project#getTitle <em>Title</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Title</em>'.
   * @see edu.project.Project#getTitle()
   * @see #getProject()
   * @generated
   */
  public EAttribute getProject_Title()
  {
    return (EAttribute)projectEClass.getEStructuralFeatures().get(0);
  }

  /**
   * Returns the meta object for the attribute '{@link edu.project.Project#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see edu.project.Project#getDescription()
   * @see #getProject()
   * @generated
   */
  public EAttribute getProject_Description()
  {
    return (EAttribute)projectEClass.getEStructuralFeatures().get(1);
  }

  /**
   * Returns the meta object for the attribute '{@link edu.project.Project#getBudget <em>Budget</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Budget</em>'.
   * @see edu.project.Project#getBudget()
   * @see #getProject()
   * @generated
   */
  public EAttribute getProject_Budget()
  {
    return (EAttribute)projectEClass.getEStructuralFeatures().get(2);
  }

  /**
   * Returns the meta object for the attribute '{@link edu.project.Project#getDeadline <em>Deadline</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Deadline</em>'.
   * @see edu.project.Project#getDeadline()
   * @see #getProject()
   * @generated
   */
  public EAttribute getProject_Deadline()
  {
    return (EAttribute)projectEClass.getEStructuralFeatures().get(3);
  }

  /**
   * Returns the meta object for the container reference '{@link edu.project.Project#getDepartment <em>Department</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the container reference '<em>Department</em>'.
   * @see edu.project.Project#getDepartment()
   * @see #getProject()
   * @generated
   */
  public EReference getProject_Department()
  {
    return (EReference)projectEClass.getEStructuralFeatures().get(4);
  }

  /**
   * Returns the meta object for the reference list '{@link edu.project.Project#getWorkingEmployees <em>Working Employees</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Working Employees</em>'.
   * @see edu.project.Project#getWorkingEmployees()
   * @see #getProject()
   * @generated
   */
  public EReference getProject_WorkingEmployees()
  {
    return (EReference)projectEClass.getEStructuralFeatures().get(5);
  }

  /**
   * Returns the meta object for class '{@link edu.project.ProductionProject <em>Production Project</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Production Project</em>'.
   * @see edu.project.ProductionProject
   * @generated
   */
  public EClass getProductionProject()
  {
    return productionProjectEClass;
  }

  /**
   * Returns the meta object for the attribute '{@link edu.project.ProductionProject#getSiteCode <em>Site Code</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Site Code</em>'.
   * @see edu.project.ProductionProject#getSiteCode()
   * @see #getProductionProject()
   * @generated
   */
  public EAttribute getProductionProject_SiteCode()
  {
    return (EAttribute)productionProjectEClass.getEStructuralFeatures().get(0);
  }

  /**
   * Returns the meta object for class '{@link edu.project.ResearchProject <em>Research Project</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Research Project</em>'.
   * @see edu.project.ResearchProject
   * @generated
   */
  public EClass getResearchProject()
  {
    return researchProjectEClass;
  }

  /**
   * Returns the meta object for class '{@link edu.project.EducationProject <em>Education Project</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Education Project</em>'.
   * @see edu.project.EducationProject
   * @generated
   */
  public EClass getEducationProject()
  {
    return educationProjectEClass;
  }

  /**
   * Returns the meta object for the reference '{@link edu.project.EducationProject#getFundinggroup <em>Fundinggroup</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Fundinggroup</em>'.
   * @see edu.project.EducationProject#getFundinggroup()
   * @see #getEducationProject()
   * @generated
   */
  public EReference getEducationProject_Fundinggroup()
  {
    return (EReference)educationProjectEClass.getEStructuralFeatures().get(0);
  }

  /**
   * Returns the meta object for class '{@link edu.project.CommunityProject <em>Community Project</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Community Project</em>'.
   * @see edu.project.CommunityProject
   * @generated
   */
  public EClass getCommunityProject()
  {
    return communityProjectEClass;
  }

  /**
   * Returns the meta object for the reference '{@link edu.project.CommunityProject#getFudingGroup <em>Fuding Group</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Fuding Group</em>'.
   * @see edu.project.CommunityProject#getFudingGroup()
   * @see #getCommunityProject()
   * @generated
   */
  public EReference getCommunityProject_FudingGroup()
  {
    return (EReference)communityProjectEClass.getEStructuralFeatures().get(0);
  }

  /**
   * Returns the meta object for class '{@link edu.project.FundingGroup <em>Funding Group</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Funding Group</em>'.
   * @see edu.project.FundingGroup
   * @generated
   */
  public EClass getFundingGroup()
  {
    return fundingGroupEClass;
  }

  /**
   * Returns the meta object for the attribute '{@link edu.project.FundingGroup#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see edu.project.FundingGroup#getName()
   * @see #getFundingGroup()
   * @generated
   */
  public EAttribute getFundingGroup_Name()
  {
    return (EAttribute)fundingGroupEClass.getEStructuralFeatures().get(0);
  }

  /**
   * Returns the meta object for the attribute '{@link edu.project.FundingGroup#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see edu.project.FundingGroup#getType()
   * @see #getFundingGroup()
   * @generated
   */
  public EAttribute getFundingGroup_Type()
  {
    return (EAttribute)fundingGroupEClass.getEStructuralFeatures().get(1);
  }

  /**
   * Returns the meta object for the reference list '{@link edu.project.FundingGroup#getFundingGroupedu <em>Funding Groupedu</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Funding Groupedu</em>'.
   * @see edu.project.FundingGroup#getFundingGroupedu()
   * @see #getFundingGroup()
   * @generated
   */
  public EReference getFundingGroup_FundingGroupedu()
  {
    return (EReference)fundingGroupEClass.getEStructuralFeatures().get(2);
  }

  /**
   * Returns the meta object for the reference list '{@link edu.project.FundingGroup#getFundingGroup <em>Funding Group</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Funding Group</em>'.
   * @see edu.project.FundingGroup#getFundingGroup()
   * @see #getFundingGroup()
   * @generated
   */
  public EReference getFundingGroup_FundingGroup()
  {
    return (EReference)fundingGroupEClass.getEStructuralFeatures().get(3);
  }

  /**
   * Returns the meta object for enum '{@link edu.project.EmployeeType <em>Employee Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Employee Type</em>'.
   * @see edu.project.EmployeeType
   * @generated
   */
  public EEnum getEmployeeType()
  {
    return employeeTypeEEnum;
  }

  /**
   * Returns the meta object for enum '{@link edu.project.FundingGroupType <em>Funding Group Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Funding Group Type</em>'.
   * @see edu.project.FundingGroupType
   * @generated
   */
  public EEnum getFundingGroupType()
  {
    return fundingGroupTypeEEnum;
  }

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  public ProjectFactory getProjectFactory()
  {
    return (ProjectFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    companyEClass = createEClass(COMPANY);
    createEReference(companyEClass, COMPANY__DEPARTMENTS);

    departmentEClass = createEClass(DEPARTMENT);
    createEAttribute(departmentEClass, DEPARTMENT__ID);
    createEAttribute(departmentEClass, DEPARTMENT__EMAIL);
    createEReference(departmentEClass, DEPARTMENT__EMPLOYEES);
    createEReference(departmentEClass, DEPARTMENT__COMPANY);
    createEReference(departmentEClass, DEPARTMENT__PROJECTS);

    employeeEClass = createEClass(EMPLOYEE);
    createEAttribute(employeeEClass, EMPLOYEE__TYPE);
    createEAttribute(employeeEClass, EMPLOYEE__NAME);
    createEAttribute(employeeEClass, EMPLOYEE__EMAIL);
    createEAttribute(employeeEClass, EMPLOYEE__ID);
    createEAttribute(employeeEClass, EMPLOYEE__NUMBER);
    createEReference(employeeEClass, EMPLOYEE__DEPARTMENT);

    projectEClass = createEClass(PROJECT);
    createEAttribute(projectEClass, PROJECT__TITLE);
    createEAttribute(projectEClass, PROJECT__DESCRIPTION);
    createEAttribute(projectEClass, PROJECT__BUDGET);
    createEAttribute(projectEClass, PROJECT__DEADLINE);
    createEReference(projectEClass, PROJECT__DEPARTMENT);
    createEReference(projectEClass, PROJECT__WORKING_EMPLOYEES);

    productionProjectEClass = createEClass(PRODUCTION_PROJECT);
    createEAttribute(productionProjectEClass, PRODUCTION_PROJECT__SITE_CODE);

    researchProjectEClass = createEClass(RESEARCH_PROJECT);

    educationProjectEClass = createEClass(EDUCATION_PROJECT);
    createEReference(educationProjectEClass, EDUCATION_PROJECT__FUNDINGGROUP);

    communityProjectEClass = createEClass(COMMUNITY_PROJECT);
    createEReference(communityProjectEClass, COMMUNITY_PROJECT__FUDING_GROUP);

    fundingGroupEClass = createEClass(FUNDING_GROUP);
    createEAttribute(fundingGroupEClass, FUNDING_GROUP__NAME);
    createEAttribute(fundingGroupEClass, FUNDING_GROUP__TYPE);
    createEReference(fundingGroupEClass, FUNDING_GROUP__FUNDING_GROUPEDU);
    createEReference(fundingGroupEClass, FUNDING_GROUP__FUNDING_GROUP);

    // Create enums
    employeeTypeEEnum = createEEnum(EMPLOYEE_TYPE);
    fundingGroupTypeEEnum = createEEnum(FUNDING_GROUP_TYPE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    productionProjectEClass.getESuperTypes().add(this.getProject());
    researchProjectEClass.getESuperTypes().add(this.getProject());
    educationProjectEClass.getESuperTypes().add(this.getProject());
    communityProjectEClass.getESuperTypes().add(this.getProject());

    // Initialize classes and features; add operations and parameters
    initEClass(companyEClass, Company.class, "Company", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getCompany_Departments(), this.getDepartment(), this.getDepartment_Company(), "departments", null, 2, 8, Company.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    addEOperation(companyEClass, ecorePackage.getEDouble(), "calculateTotalBudget", 0, 1, IS_UNIQUE, IS_ORDERED);

    addEOperation(companyEClass, ecorePackage.getEInt(), "countEmployeesInProductionProjects", 0, 1, IS_UNIQUE, IS_ORDERED);

    initEClass(departmentEClass, Department.class, "Department", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDepartment_ID(), ecorePackage.getEString(), "ID", null, 0, 1, Department.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getDepartment_Email(), ecorePackage.getEString(), "email", null, 0, 1, Department.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDepartment_Employees(), this.getEmployee(), this.getEmployee_Department(), "employees", null, 0, -1, Department.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDepartment_Company(), this.getCompany(), this.getCompany_Departments(), "company", null, 1, 1, Department.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDepartment_Projects(), this.getProject(), this.getProject_Department(), "projects", null, 0, -1, Department.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    addEOperation(departmentEClass, ecorePackage.getEDouble(), "calculateAverageBudget", 0, 1, IS_UNIQUE, IS_ORDERED);

    addEOperation(departmentEClass, this.getFundingGroupType(), "getFundingGroupTypeCommunityProjects", 0, -1, IS_UNIQUE, IS_ORDERED);

    initEClass(employeeEClass, Employee.class, "Employee", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getEmployee_Type(), this.getEmployeeType(), "type", null, 0, 1, Employee.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getEmployee_Name(), ecorePackage.getEString(), "name", null, 0, 1, Employee.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getEmployee_Email(), ecorePackage.getEString(), "email", null, 0, 1, Employee.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getEmployee_ID(), ecorePackage.getEString(), "ID", null, 0, 1, Employee.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getEmployee_Number(), ecorePackage.getEString(), "number", null, 0, 1, Employee.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEmployee_Department(), this.getDepartment(), this.getDepartment_Employees(), "department", null, 1, 1, Employee.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(projectEClass, Project.class, "Project", IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getProject_Title(), ecorePackage.getEString(), "title", null, 0, 1, Project.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getProject_Description(), ecorePackage.getEString(), "description", null, 0, 1, Project.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getProject_Budget(), ecorePackage.getEDouble(), "budget", null, 0, 1, Project.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getProject_Deadline(), ecorePackage.getEDate(), "deadline", null, 0, 1, Project.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getProject_Department(), this.getDepartment(), this.getDepartment_Projects(), "department", null, 1, 1, Project.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getProject_WorkingEmployees(), this.getEmployee(), null, "workingEmployees", null, 0, -1, Project.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(productionProjectEClass, ProductionProject.class, "ProductionProject", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getProductionProject_SiteCode(), ecorePackage.getEString(), "siteCode", null, 0, 1, ProductionProject.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(researchProjectEClass, ResearchProject.class, "ResearchProject", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(educationProjectEClass, EducationProject.class, "EducationProject", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getEducationProject_Fundinggroup(), this.getFundingGroup(), this.getFundingGroup_FundingGroupedu(), "fundinggroup", null, 1, 1, EducationProject.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(communityProjectEClass, CommunityProject.class, "CommunityProject", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getCommunityProject_FudingGroup(), this.getFundingGroup(), this.getFundingGroup_FundingGroup(), "fudingGroup", null, 1, 1, CommunityProject.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(fundingGroupEClass, FundingGroup.class, "FundingGroup", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getFundingGroup_Name(), ecorePackage.getEString(), "name", null, 0, 1, FundingGroup.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getFundingGroup_Type(), this.getFundingGroupType(), "type", null, 0, 1, FundingGroup.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getFundingGroup_FundingGroupedu(), this.getEducationProject(), this.getEducationProject_Fundinggroup(), "fundingGroupedu", null, 1, -1, FundingGroup.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getFundingGroup_FundingGroup(), this.getCommunityProject(), this.getCommunityProject_FudingGroup(), "fundingGroup", null, 1, -1, FundingGroup.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Initialize enums and add enum literals
    initEEnum(employeeTypeEEnum, EmployeeType.class, "EmployeeType");
    addEEnumLiteral(employeeTypeEEnum, EmployeeType.TEMPORARY);
    addEEnumLiteral(employeeTypeEEnum, EmployeeType.PERMANENT);

    initEEnum(fundingGroupTypeEEnum, FundingGroupType.class, "FundingGroupType");
    addEEnumLiteral(fundingGroupTypeEEnum, FundingGroupType.PRIVATE);
    addEEnumLiteral(fundingGroupTypeEEnum, FundingGroupType.GOVERNMENT);
    addEEnumLiteral(fundingGroupTypeEEnum, FundingGroupType.MIXED);

    // Create resource
    createResource(eNS_URI);

    // Create annotations
    // http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen
    createEnhancedCodeGenAnnotations();
  }

  /**
   * Initializes the annotations for <b>http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen</b>.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected void createEnhancedCodeGenAnnotations()
  {
    String source = "http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen";
    addAnnotation
      (this,
       source,
       new String[]
       {
         "requirement", "A company is comprised of two to eight departments. Each department has an ID and email. A department hires employees for certain projects. Employees working on projects can be temporary employees or permanent employees. \nEach employee is identified by a name, email, employee ID, employee number. Projects can be of types - production projects, research projects, education projects, and community projects. All projects have a title, description, budget amount, and deadline. In addition, each education project and community project are associated with one funding group. The funding group can be of types - private group, government group, or mixed group. \nThe production projects are characterized by a site code.\nfunctional requirement\uff1a\n+ \"Total budget of all projects in a company\" : Calculate the sum of the budget amounts of all projects in all departments of a company. \n\n+ \"Average budget of all projects in a department\" : Calculate the average budget amount of all projects in a given department.\n\n+ \"Number of employees working on production projects in a company\" : Count the total number of employees working on production projects across all departments in a company. \n\n+ \"Funding group type of all community projects in a department\" : Retrieve the funding group type of all community projects within a given department."
       });
    addAnnotation
      (companyEClass.getEOperations().get(0),
       source,
       new String[]
       {
         "generated", "true"
       });
    addAnnotation
      (companyEClass.getEOperations().get(1),
       source,
       new String[]
       {
         "generated", "true"
       });
    addAnnotation
      (departmentEClass.getEOperations().get(0),
       source,
       new String[]
       {
         "generated", "true"
       });
    addAnnotation
      (departmentEClass.getEOperations().get(1),
       source,
       new String[]
       {
         "generated", "true"
       });
  }

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  public interface Literals
  {
    /**
     * The meta object literal for the '{@link edu.project.Company <em>Company</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.project.Company
     * @see edu.project.ProjectPackage#getCompany()
     * @generated
     */
    public static final EClass COMPANY = eINSTANCE.getCompany();

    /**
     * The meta object literal for the '<em><b>Departments</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EReference COMPANY__DEPARTMENTS = eINSTANCE.getCompany_Departments();

    /**
     * The meta object literal for the '{@link edu.project.Department <em>Department</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.project.Department
     * @see edu.project.ProjectPackage#getDepartment()
     * @generated
     */
    public static final EClass DEPARTMENT = eINSTANCE.getDepartment();

    /**
     * The meta object literal for the '<em><b>ID</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EAttribute DEPARTMENT__ID = eINSTANCE.getDepartment_ID();

    /**
     * The meta object literal for the '<em><b>Email</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EAttribute DEPARTMENT__EMAIL = eINSTANCE.getDepartment_Email();

    /**
     * The meta object literal for the '<em><b>Employees</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EReference DEPARTMENT__EMPLOYEES = eINSTANCE.getDepartment_Employees();

    /**
     * The meta object literal for the '<em><b>Company</b></em>' container reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EReference DEPARTMENT__COMPANY = eINSTANCE.getDepartment_Company();

    /**
     * The meta object literal for the '<em><b>Projects</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EReference DEPARTMENT__PROJECTS = eINSTANCE.getDepartment_Projects();

    /**
     * The meta object literal for the '{@link edu.project.Employee <em>Employee</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.project.Employee
     * @see edu.project.ProjectPackage#getEmployee()
     * @generated
     */
    public static final EClass EMPLOYEE = eINSTANCE.getEmployee();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EAttribute EMPLOYEE__TYPE = eINSTANCE.getEmployee_Type();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EAttribute EMPLOYEE__NAME = eINSTANCE.getEmployee_Name();

    /**
     * The meta object literal for the '<em><b>Email</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EAttribute EMPLOYEE__EMAIL = eINSTANCE.getEmployee_Email();

    /**
     * The meta object literal for the '<em><b>ID</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EAttribute EMPLOYEE__ID = eINSTANCE.getEmployee_ID();

    /**
     * The meta object literal for the '<em><b>Number</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EAttribute EMPLOYEE__NUMBER = eINSTANCE.getEmployee_Number();

    /**
     * The meta object literal for the '<em><b>Department</b></em>' container reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EReference EMPLOYEE__DEPARTMENT = eINSTANCE.getEmployee_Department();

    /**
     * The meta object literal for the '{@link edu.project.Project <em>Project</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.project.Project
     * @see edu.project.ProjectPackage#getProject()
     * @generated
     */
    public static final EClass PROJECT = eINSTANCE.getProject();

    /**
     * The meta object literal for the '<em><b>Title</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EAttribute PROJECT__TITLE = eINSTANCE.getProject_Title();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EAttribute PROJECT__DESCRIPTION = eINSTANCE.getProject_Description();

    /**
     * The meta object literal for the '<em><b>Budget</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EAttribute PROJECT__BUDGET = eINSTANCE.getProject_Budget();

    /**
     * The meta object literal for the '<em><b>Deadline</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EAttribute PROJECT__DEADLINE = eINSTANCE.getProject_Deadline();

    /**
     * The meta object literal for the '<em><b>Department</b></em>' container reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EReference PROJECT__DEPARTMENT = eINSTANCE.getProject_Department();

    /**
     * The meta object literal for the '<em><b>Working Employees</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EReference PROJECT__WORKING_EMPLOYEES = eINSTANCE.getProject_WorkingEmployees();

    /**
     * The meta object literal for the '{@link edu.project.ProductionProject <em>Production Project</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.project.ProductionProject
     * @see edu.project.ProjectPackage#getProductionProject()
     * @generated
     */
    public static final EClass PRODUCTION_PROJECT = eINSTANCE.getProductionProject();

    /**
     * The meta object literal for the '<em><b>Site Code</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EAttribute PRODUCTION_PROJECT__SITE_CODE = eINSTANCE.getProductionProject_SiteCode();

    /**
     * The meta object literal for the '{@link edu.project.ResearchProject <em>Research Project</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.project.ResearchProject
     * @see edu.project.ProjectPackage#getResearchProject()
     * @generated
     */
    public static final EClass RESEARCH_PROJECT = eINSTANCE.getResearchProject();

    /**
     * The meta object literal for the '{@link edu.project.EducationProject <em>Education Project</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.project.EducationProject
     * @see edu.project.ProjectPackage#getEducationProject()
     * @generated
     */
    public static final EClass EDUCATION_PROJECT = eINSTANCE.getEducationProject();

    /**
     * The meta object literal for the '<em><b>Fundinggroup</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EReference EDUCATION_PROJECT__FUNDINGGROUP = eINSTANCE.getEducationProject_Fundinggroup();

    /**
     * The meta object literal for the '{@link edu.project.CommunityProject <em>Community Project</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.project.CommunityProject
     * @see edu.project.ProjectPackage#getCommunityProject()
     * @generated
     */
    public static final EClass COMMUNITY_PROJECT = eINSTANCE.getCommunityProject();

    /**
     * The meta object literal for the '<em><b>Fuding Group</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EReference COMMUNITY_PROJECT__FUDING_GROUP = eINSTANCE.getCommunityProject_FudingGroup();

    /**
     * The meta object literal for the '{@link edu.project.FundingGroup <em>Funding Group</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.project.FundingGroup
     * @see edu.project.ProjectPackage#getFundingGroup()
     * @generated
     */
    public static final EClass FUNDING_GROUP = eINSTANCE.getFundingGroup();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EAttribute FUNDING_GROUP__NAME = eINSTANCE.getFundingGroup_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EAttribute FUNDING_GROUP__TYPE = eINSTANCE.getFundingGroup_Type();

    /**
     * The meta object literal for the '<em><b>Funding Groupedu</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EReference FUNDING_GROUP__FUNDING_GROUPEDU = eINSTANCE.getFundingGroup_FundingGroupedu();

    /**
     * The meta object literal for the '<em><b>Funding Group</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public static final EReference FUNDING_GROUP__FUNDING_GROUP = eINSTANCE.getFundingGroup_FundingGroup();

    /**
     * The meta object literal for the '{@link edu.project.EmployeeType <em>Employee Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.project.EmployeeType
     * @see edu.project.ProjectPackage#getEmployeeType()
     * @generated
     */
    public static final EEnum EMPLOYEE_TYPE = eINSTANCE.getEmployeeType();

    /**
     * The meta object literal for the '{@link edu.project.FundingGroupType <em>Funding Group Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.project.FundingGroupType
     * @see edu.project.ProjectPackage#getFundingGroupType()
     * @generated
     */
    public static final EEnum FUNDING_GROUP_TYPE = eINSTANCE.getFundingGroupType();

  }

} //ProjectPackage
