/**
 * generated by Enhanced EcoreGen
 */
package edu.library;

import java.util.Collection;
import java.util.Date;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.EObjectResolvingEList;
import org.eclipse.emf.ecore.util.InternalEList;
import java.util.HashSet;
import java.util.Set;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>System</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.library.LibrarySystem#getUsers <em>Users</em>}</li>
 *   <li>{@link edu.library.LibrarySystem#getBooks <em>Books</em>}</li>
 * </ul>
 *
 * @see edu.library.LibraryPackage#getLibrarySystem()
 * @model kind="class"
 * @generated
 */
public class LibrarySystem extends MinimalEObjectImpl.Container implements EObject
{
  /**
   * The cached value of the '{@link #getUsers() <em>Users</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUsers()
   * @generated
   * @ordered
   */
  protected EList<User> users;

  /**
   * The cached value of the '{@link #getBooks() <em>Books</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBooks()
   * @generated
   * @ordered
   */
  protected EList<Book> books;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LibrarySystem()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LibraryPackage.Literals.LIBRARY_SYSTEM;
  }

  /**
   * Returns the value of the '<em><b>Users</b></em>' reference list.
   * The list contents are of type {@link edu.library.User}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Users</em>' reference list.
   * @see edu.library.LibraryPackage#getLibrarySystem_Users()
   * @model
   * @generated
   */
  public EList<User> getUsers()
  {
    if (users == null)
    {
      users = new EObjectResolvingEList<User>(User.class, this, LibraryPackage.LIBRARY_SYSTEM__USERS);
    }
    return users;
  }

  /**
   * Returns the value of the '<em><b>Books</b></em>' containment reference list.
   * The list contents are of type {@link edu.library.Book}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Books</em>' containment reference list.
   * @see edu.library.LibraryPackage#getLibrarySystem_Books()
   * @model containment="true"
   * @generated
   */
  public EList<Book> getBooks()
  {
    if (books == null)
    {
      books = new EObjectContainmentEList<Book>(Book.class, this, LibraryPackage.LIBRARY_SYSTEM__BOOKS);
    }
    return books;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Calculates the total number of unique books checked out by a specific user.
   * Algorithm:
   *   1. Initialize a set to store unique book IDs.
   *   2. Iterate through all checkouts of the user.
   *   3. For each checkout, add the book's ISBN to the set.
   *   4. Return the size of the set.
   * Input:
   *   - user: The user to check. Must be a valid User object.
   * Output:
   *   - int: The number of unique books checked out by the user. Value is non-negative.
   * Pre-condition: The user parameter must not be null.
   * Post-condition: The returned value is the count of unique books checked out by the user.
   * <!-- end-model-doc -->
   * @model required="true" userRequired="true"
   *        annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public int totalUniqueBooksCheckedOutByUser(final User user)
  {
    if (user == null)
    {
      throw new IllegalArgumentException("User must not be null");
    }

    Set<String> uniqueBookISNs = new HashSet<>();
    for (CheckOut checkout : user.getCheckouts())
    {
      uniqueBookISNs.add(checkout.getBook().getISBN());
    }
    return uniqueBookISNs.size();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Calculates the average page count of the unique books borrowed by a specific user.
   * Algorithm:
   *   1. Get all unique books borrowed by the user (using uniqueBooksBorrowedByUser with no date constraints).
   *   2. If no books are found, return 0.0.
   *   3. Calculate the sum of the number of pages of all unique books.
   *   4. Divide the sum by the number of unique books.
   *   5. Return the result.
   * Input:
   *   - user: The user to calculate the average for. Must be a valid User object.
   * Output:
   *   - double: The average number of pages of unique books borrowed by the user. Value is non-negative.
   * Pre-condition: The user parameter must not be null.
   * Post-condition: The returned value is the average page count of unique books borrowed by the user.
   * <!-- end-model-doc -->
   * @model required="true" userRequired="true"
   *        annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public double averageNumberOfPagesUniqueBooksByUser(final User user)
  {
    if (user == null)
    {
      throw new IllegalArgumentException("User must not be null");
    }

    int uniqueBooksCount = totalUniqueBooksCheckedOutByUser(user);
    if (uniqueBooksCount == 0)
    {
      return 0.0;
    }

    int totalPages = 0;
    Set<String> uniqueBookISNs = new HashSet<>();
    for (CheckOut checkout : user.getCheckouts())
    {
      String isbn = checkout.getBook().getISBN();
      if (!uniqueBookISNs.contains(isbn))
      {
        uniqueBookISNs.add(isbn);
        totalPages += checkout.getBook().getNumberOfPages();
      }
    }

    return (double) totalPages / uniqueBooksCount;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Determines how many unique books a particular user has borrowed during a specified period.
   * Algorithm:
   *   1. Initialize a set to store unique book IDs.
   *   2. Iterate through all checkouts of the user.
   *   3. For each checkout, check if its start date is within the specified period.
   *   4. If it is, add the book's ISBN to the set.
   *   5. Return the size of the set.
   * Input:
   *   - user: The user to check. Must be a valid User object.
   *   - start: The start date of the period (format: yyyy-MM-dd). Must be a valid date.
   *   - end: The end date of the period (format: yyyy-MM-dd). Must be a valid date and after the start date.
   * Output:
   *   - int: The number of unique books borrowed by the user in the period. Value is non-negative.
   * Pre-condition: The user parameter must not be null, and the start date must be before the end date.
   * Post-condition: The returned value is the count of unique books borrowed by the user in the specified period.
   * <!-- end-model-doc -->
   * @model required="true" userRequired="true"
   *        annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public int uniqueBooksBorrowedByUser(final User user, final Date start, final Date end)
  {
    if (user == null)
    {
      throw new IllegalArgumentException("User must not be null");
    }
    if (start == null || end == null || start.after(end))
    {
      throw new IllegalArgumentException("Invalid date range");
    }

    Set<String> uniqueBookISNs = new HashSet<>();
    for (CheckOut checkout : user.getCheckouts())
    {
      Date checkoutStart = checkout.getStartDate();
      if (checkoutStart != null && !checkoutStart.before(start) && !checkoutStart.after(end))
      {
        uniqueBookISNs.add(checkout.getBook().getISBN());
      }
    }
    return uniqueBookISNs.size();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Counts the number of times a specific book has been checked out.
   * Algorithm:
   *   1. Initialize a counter to 0.
   *   2. Iterate through all checkouts in the system.
   *   3. For each checkout, check if the book matches the input book.
   *   4. If it matches, increment the counter.
   *   5. Return the counter.
   * Input:
   *   - book: The book to count checkouts for. Must be a valid Book object.
   * Output:
   *   - int: The number of times the book has been checked out. Value is non-negative.
   * Pre-condition: The book parameter must not be null.
   * Post-condition: The returned value is the count of checkouts for the specified book.
   * <!-- end-model-doc -->
   * @model required="true" bookRequired="true"
   *        annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public int countBookCheckOuts(final Book book)
  {
    if (book == null)
    {
      throw new IllegalArgumentException("Book must not be null");
    }

    int count = 0;
    for (User user : getUsers())
    {
      for (CheckOut checkout : user.getCheckouts())
      {
        if (checkout.getBook() == book)
        {
          count++;
        }
      }
    }
    return count;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case LibraryPackage.LIBRARY_SYSTEM__BOOKS:
        return ((InternalEList<?>)getBooks()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case LibraryPackage.LIBRARY_SYSTEM__USERS:
        return getUsers();
      case LibraryPackage.LIBRARY_SYSTEM__BOOKS:
        return getBooks();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case LibraryPackage.LIBRARY_SYSTEM__USERS:
        getUsers().clear();
        getUsers().addAll((Collection<? extends User>)newValue);
        return;
      case LibraryPackage.LIBRARY_SYSTEM__BOOKS:
        getBooks().clear();
        getBooks().addAll((Collection<? extends Book>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case LibraryPackage.LIBRARY_SYSTEM__USERS:
        getUsers().clear();
        return;
      case LibraryPackage.LIBRARY_SYSTEM__BOOKS:
        getBooks().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case LibraryPackage.LIBRARY_SYSTEM__USERS:
        return users != null && !users.isEmpty();
      case LibraryPackage.LIBRARY_SYSTEM__BOOKS:
        return books != null && !books.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} // LibrarySystem
