/**
 * generated by Enhanced EcoreGen
 */
package edu.videorental;

import java.util.Collection;
import java.util.Date;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentWithInverseEList;
import org.eclipse.emf.ecore.util.EObjectWithInverseResolvingEList;
import org.eclipse.emf.ecore.util.InternalEList;
import java.util.Calendar;
import org.eclipse.emf.common.util.BasicEList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Customer</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.videorental.Customer#getId <em>Id</em>}</li>
 *   <li>{@link edu.videorental.Customer#getRentals <em>Rentals</em>}</li>
 *   <li>{@link edu.videorental.Customer#getTransactions <em>Transactions</em>}</li>
 * </ul>
 *
 * @see edu.videorental.VideorentalPackage#getCustomer()
 * @model kind="class"
 * @generated
 */
public class Customer extends MinimalEObjectImpl.Container implements EObject
{
  /**
   * The default value of the '{@link #getId() <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getId()
   * @generated
   * @ordered
   */
  protected static final String ID_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getId() <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getId()
   * @generated
   * @ordered
   */
  protected String id = ID_EDEFAULT;

  /**
   * The cached value of the '{@link #getRentals() <em>Rentals</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRentals()
   * @generated
   * @ordered
   */
  protected EList<VideoRental> rentals;

  /**
   * The cached value of the '{@link #getTransactions() <em>Transactions</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTransactions()
   * @generated
   * @ordered
   */
  protected EList<RentalTransaction> transactions;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Customer()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return VideorentalPackage.Literals.CUSTOMER;
  }

  /**
   * Returns the value of the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' attribute.
   * @see #setId(String)
   * @see edu.videorental.VideorentalPackage#getCustomer_Id()
   * @model
   * @generated
   */
  public String getId()
  {
    return id;
  }

  /**
   * Sets the value of the '{@link edu.videorental.Customer#getId <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param newId the new value of the '<em>Id</em>' attribute.
   * @see #getId()
   * @generated
   */
  public void setId(String newId)
  {
    String oldId = id;
    id = newId;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, VideorentalPackage.CUSTOMER__ID, oldId, id));
  }

  /**
   * Returns the value of the '<em><b>Rentals</b></em>' containment reference list.
   * The list contents are of type {@link edu.videorental.VideoRental}.
   * It is bidirectional and its opposite is '{@link edu.videorental.VideoRental#getCustomer <em>Customer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rentals</em>' containment reference list.
   * @see edu.videorental.VideorentalPackage#getCustomer_Rentals()
   * @see edu.videorental.VideoRental#getCustomer
   * @model opposite="customer" containment="true" upper="20"
   * @generated
   */
  public EList<VideoRental> getRentals()
  {
    if (rentals == null)
    {
      rentals = new EObjectContainmentWithInverseEList<VideoRental>(VideoRental.class, this, VideorentalPackage.CUSTOMER__RENTALS, VideorentalPackage.VIDEO_RENTAL__CUSTOMER);
    }
    return rentals;
  }

  /**
   * Returns the value of the '<em><b>Transactions</b></em>' reference list.
   * The list contents are of type {@link edu.videorental.RentalTransaction}.
   * It is bidirectional and its opposite is '{@link edu.videorental.RentalTransaction#getCustomer <em>Customer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Transactions</em>' reference list.
   * @see edu.videorental.VideorentalPackage#getCustomer_Transactions()
   * @see edu.videorental.RentalTransaction#getCustomer
   * @model opposite="customer"
   * @generated
   */
  public EList<RentalTransaction> getTransactions()
  {
    if (transactions == null)
    {
      transactions = new EObjectWithInverseResolvingEList<RentalTransaction>(RentalTransaction.class, this, VideorentalPackage.CUSTOMER__TRANSACTIONS, VideorentalPackage.RENTAL_TRANSACTION__CUSTOMER);
    }
    return transactions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary:
   *   Attempts to add a new video tape rental for the customer. The operation verifies that the
   *   customer has fewer than 20 active rentals, has no outstanding past‑due amount, and that the
   *   requested tape is available on the given date. If all checks succeed, a new VideoRental
   *   instance is created, linked to the customer, the tape and a new RentalTransaction, and the
   *   method returns true; otherwise it returns false.
   * Algorithm:
   *   1. IF rentals.size ≥ 20 THEN return false.
   *   2. CALL calculateTotalPastDueAmount(currentDate). IF result > 0 THEN return false.
   *   3. CALL tape.isAvailable(currentDate). IF result = false THEN return false.
   *   4. CREATE new RentalTransaction txn with:
   *        - rentalDate = currentDate
   *        - customer = this
   *        - totalPrice = 0 (will be computed later)
   *      ADD txn to this.transactions.
   *   5. CREATE new VideoRental vr with:
   *        - customer = this
   *        - tape = tape
   *        - transaction = txn
   *        - dueDate = currentDate + default rental period (e.g., 7 days)
   *        - returnDate = null
   *        - ownedPastDueAmount = 0
   *      ADD vr to this.rentals and to tape.rentals and to txn.rentals.
   *   6. RETURN true.
   * Input:
   *   - tape : Tape – the tape the customer wishes to rent; must be a valid Tape object.
   *   - currentDate : EDate – the system date/time at which the rental is being created,
   *                           format "yyyy-MM-dd HH:mm:ss".
   * Output:
   *   - boolean – true if the rental is successfully created; false if any verification fails.
   * Pre-condition:
   *   - The customer object is fully initialized and contains up‑to‑date lists of rentals
   *     and transactions.
   *   - `tape` is not null and exists in inventory.
   * Post-condition:
   *   - If true is returned, the customer's rentals list contains the new VideoRental,
   *     the tape’s rentals list contains the new VideoRental, and a new RentalTransaction
   *     is stored in the customer's transactions list.
   *   - The tape is now considered unavailable until its VideoRental.returnDate is set.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public boolean addVedioTapeRental(final Tape tape, final Date currentDate)
  {
    // 1. check maximum number of active rentals
    if (getRentals().size() >= 20) {
      return false;
    }

    // 2. check outstanding past‑due amount
    if (calculateTotalPastDueAmount(currentDate) > 0.0) {
      return false;
    }

    // 3. check tape availability
    if (tape == null || !tape.isAvailable(currentDate)) {
      return false;
    }

    // 4. create a new RentalTransaction
    RentalTransaction txn = VideorentalFactory.eINSTANCE.createRentalTransaction();
    txn.setRentalDate(currentDate);
    txn.setCustomer(this);
    txn.setTotalPrice(0.0); // will be calculated later
    getTransactions().add(txn);

    // 5. create a new VideoRental
    VideoRental vr = VideorentalFactory.eINSTANCE.createVideoRental();
    vr.setCustomer(this);
    vr.setTape(tape);
    vr.setTransaction(txn);

    // compute default due date (7 days after currentDate)
    Calendar cal = Calendar.getInstance();
    cal.setTime(currentDate);
    cal.add(Calendar.DAY_OF_YEAR, 7);
    Date dueDate = cal.getTime();
    vr.setDueDate(dueDate);
    vr.setReturnDate(null);
    vr.setOwnedPastDueAmount(0.0);

    // add the rental to the appropriate collections
    getRentals().add(vr);
    tape.getRentals().add(vr);
    txn.getRentals().add(vr);

    // 6. success
    return true;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary:
   *   Retrieves a list of all Tape objects that the customer has rented but not yet returned.
   * Algorithm:
   *   1. result ← empty List<Tape>
   *   2. FOR each VideoRental vr in this.rentals DO
   *        IF vr.returnDate == null THEN
   *            result.add(vr.tape)
   *        END IF
   *      END FOR
   *   3. RETURN result
   * Input:
   *   – (none)
   * Output:
   *   - List<Tape> – a list containing the Tape instances with a null returnDate.
   *                  The list is empty if the customer has no active rentals.
   * Pre-condition:
   *   - The customer’s rentals list is populated.
   * Post-condition:
   *   - No modification of any object state; purely observational.
   * <!-- end-model-doc -->
   * @model kind="operation"
   *        annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public EList<Tape> getUnreturnedTapes()
  {
    BasicEList<Tape> result = new BasicEList<>();
    for (VideoRental vr : getRentals()) {
      if (vr.getReturnDate() == null) {
        result.add(vr.getTape());
      }
    }
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary:
   *   Calculates the total past‑due (overdue) amount for all rentals of this customer as of
   *   the supplied current date. The overdue fee for each rental is computed according to the
   *   business rule: $0.50 per overdue day, with any partial day rounded up, and a fee of 0
   *   if the return date is on or before the due date.
   * Algorithm:
   *   1. total ← 0.0
   *   2. FOR each VideoRental vr in this.rentals DO
   *        a. fee ← vr.calculateOwnedPastDueAmount(currentDate)
   *        b. total ← total + fee
   *      END FOR
   *   3. RETURN round(total, 2)   // round to two decimal places
   * Input:
   *   - currentDate : EDate – the date/time to consider as “today”, format "yyyy-MM-dd HH:mm:ss".
   * Output:
   *   - double – the sum of overdue fees for all rentals, rounded to two decimal places.
   * Pre-condition:
   *   - The customer’s rentals list is up‑to‑date.
   * Post-condition:
   *   - No state is modified; the method is pure (read‑only).
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public double calculateTotalPastDueAmount(final Date currentDate)
  {
    double total = 0.0;
    for (VideoRental vr : getRentals()) {
      total += vr.calculateOwnedPastDueAmount(currentDate);
    }
    // round to two decimal places
    return Math.round(total * 100.0) / 100.0;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public NotificationChain eInverseAdd(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case VideorentalPackage.CUSTOMER__RENTALS:
        return ((InternalEList<InternalEObject>)(InternalEList<?>)getRentals()).basicAdd(otherEnd, msgs);
      case VideorentalPackage.CUSTOMER__TRANSACTIONS:
        return ((InternalEList<InternalEObject>)(InternalEList<?>)getTransactions()).basicAdd(otherEnd, msgs);
    }
    return super.eInverseAdd(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case VideorentalPackage.CUSTOMER__RENTALS:
        return ((InternalEList<?>)getRentals()).basicRemove(otherEnd, msgs);
      case VideorentalPackage.CUSTOMER__TRANSACTIONS:
        return ((InternalEList<?>)getTransactions()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case VideorentalPackage.CUSTOMER__ID:
        return getId();
      case VideorentalPackage.CUSTOMER__RENTALS:
        return getRentals();
      case VideorentalPackage.CUSTOMER__TRANSACTIONS:
        return getTransactions();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case VideorentalPackage.CUSTOMER__ID:
        setId((String)newValue);
        return;
      case VideorentalPackage.CUSTOMER__RENTALS:
        getRentals().clear();
        getRentals().addAll((Collection<? extends VideoRental>)newValue);
        return;
      case VideorentalPackage.CUSTOMER__TRANSACTIONS:
        getTransactions().clear();
        getTransactions().addAll((Collection<? extends RentalTransaction>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case VideorentalPackage.CUSTOMER__ID:
        setId(ID_EDEFAULT);
        return;
      case VideorentalPackage.CUSTOMER__RENTALS:
        getRentals().clear();
        return;
      case VideorentalPackage.CUSTOMER__TRANSACTIONS:
        getTransactions().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case VideorentalPackage.CUSTOMER__ID:
        return ID_EDEFAULT == null ? id != null : !ID_EDEFAULT.equals(id);
      case VideorentalPackage.CUSTOMER__RENTALS:
        return rentals != null && !rentals.isEmpty();
      case VideorentalPackage.CUSTOMER__TRANSACTIONS:
        return transactions != null && !transactions.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (id: ");
    result.append(id);
    result.append(')');
    return result.toString();
  }

} // Customer
