/**
 * generated by Enhanced EcoreGen
 */
package edu.pets;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentWithInverseEList;
import org.eclipse.emf.ecore.util.InternalEList;
import org.eclipse.emf.common.util.BasicEList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>House</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.pets.House#getLived <em>Lived</em>}</li>
 * </ul>
 *
 * @see edu.pets.PetsPackage#getHouse()
 * @model kind="class"
 * @generated
 */
public class House extends MinimalEObjectImpl.Container implements EObject
{
  /**
   * The cached value of the '{@link #getLived() <em>Lived</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLived()
   * @generated
   * @ordered
   */
  protected EList<Pet> lived;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected House()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PetsPackage.Literals.HOUSE;
  }

  /**
   * Returns the value of the '<em><b>Lived</b></em>' containment reference list.
   * The list contents are of type {@link edu.pets.Pet}.
   * It is bidirectional and its opposite is '{@link edu.pets.Pet#getHouse <em>House</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lived</em>' containment reference list.
   * @see edu.pets.PetsPackage#getHouse_Lived()
   * @see edu.pets.Pet#getHouse
   * @model opposite="house" containment="true"
   * @generated
   */
  public EList<Pet> getLived()
  {
    if (lived == null)
    {
      lived = new EObjectContainmentWithInverseEList<Pet>(Pet.class, this, PetsPackage.HOUSE__LIVED, PetsPackage.PET__HOUSE);
    }
    return lived;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary:
   *   Retrieves the names of all pets (dogs and cats) that live in this house.
   * Algorithm:
   *   1. Create an empty list of strings `names`.
   *   2) Iterate over each pet in `lived`:
   *        a) If pet.name is non‑null, add pet.name to `names`.
   *   3) Return `names`. (If no pets, the list is empty.)
   * Input:
   *   - None.
   * Output:
   *   - List<String>
   *       * Contains the name of each pet residing in the house.
   *       * Order corresponds to the iteration order of the lived collection.
   * Pre‑condition:
   *   - The House instance is valid.
   * Post‑condition:
   *   - The returned list reflects the current state of the house’s pets; no modification to the house occurs.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public EList<String> retrievePetNames()
  {
    BasicEList<String> names = new BasicEList<>();
    if (lived != null) {
      for (Pet pet : lived) {
        if (pet != null) {
          String name = pet.getName();
          if (name != null) {
            names.add(name);
          }
        }
      }
    }
    return names;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary:
   *   Adds a given Pet to the House’s collection of lived pets.
   * Algorithm:
   *   1. Validate that the pet is not null.
   *   2. Verify that pet.name is a non‑empty string; if empty or null, return false.
   *   3. Check pet.house:
   *        a) If pet.house is not null, the pet already belongs to a house (could be this house or another); return false.
   *   4. Append the pet to the lived list.
   *   5. Set pet.house = this house.
   *   6. Return true.
   * Input:
   *   - pet : Pet
   *       * The Pet instance to be added.
   *       * Must have a non‑null, non‑empty name.
   * Output:
   *   - boolean
   *       * true  – the pet was successfully added.
   *       * false – the pet already belongs to a house or has no valid name.
   * Pre‑condition:
   *   - The House instance exists (i.e., `this` is a valid object).
   * Post‑condition:
   *   - If true is returned: pet is contained in this.lived and pet.house == this.
   *   - If false is returned: the lived list and pet.house remain unchanged.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public boolean addPet(final Pet pet)
  {
    if (pet == null) {
      return false;
    }
    String name = pet.getName();
    if (name == null || name.isEmpty()) {
      return false;
    }
    if (pet.getHouse() != null) {
      return false;
    }
    if (lived == null) {
      // ensure lived list is initialised (this normally handled by generated getter)
      lived = new BasicEList<>();
    }
    lived.add(pet);
    pet.setHouse(this);
    return true;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary:
   *   Removes a specified Pet from the current House.
   * Algorithm:
   *   1. Validate that the pet is not null.
   *   2. Check whether pet.house == this.
   *        a) If not, return false (the pet does not belong to this house).
   *   3. Remove the pet from the lived list.
   *   4. Set pet.house = null.
   *   5. Return true.
   * Input:
   *   - pet : Pet
   *       * The Pet instance to be removed.
   * Output:
   *   - boolean
   *       * true  – the pet was removed successfully.
   *       * false – the pet did not belong to this house.
   * Pre‑condition:
   *   - The House instance is valid.
   * Post‑condition:
   *   - If true is returned: pet is no longer in this.lived and pet.house is null.
   *   - If false is returned: the lived list and pet.house remain unchanged.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public void removePet(final Pet pet)
  {
    if (pet == null) {
      return;
    }
    if (pet.getHouse() != this) {
      return;
    }
    if (lived != null) {
      lived.remove(pet);
    }
    pet.setHouse(null);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary:
   *   Returns a list of pets of a specific type ("dog" or "cat") that live in this house.
   * Algorithm:
   *   1. Validate that `type` is not null and normalize it (e.g., lower‑case trim).
   *   2. If `type` is not "dog" nor "cat", return an empty list.
   *   3. Create an empty list `result`.
   *   4. For each pet in `lived`:
   *        a) If `type` == "dog" and pet is an instance of Dog, add pet to `result`.
   *        b) If `type` == "cat" and pet is an instance of Cat, add pet to `result`.
   *   5. Return `result`.
   * Input:
   *   - type : String
   *       * Expected values: "dog" or "cat" (case‑insensitive).
   * Output:
   *   - List<Pet>
   *       * Contains only pets matching the requested type.
   *       * Empty list if no matching pets or if `type` is invalid.
   * Pre‑condition:
   *   - The House instance is valid.
   * Post‑condition:
   *   - The house’s state is unchanged; the returned list is a snapshot of matching pets.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public EList<Pet> getPetsByType(final String type)
  {
    BasicEList<Pet> result = new BasicEList<>();
    if (type == null) {
      return result;
    }
    String t = type.trim().toLowerCase();
    if (!t.equals("dog") && !t.equals("cat")) {
      return result;
    }
    if (lived != null) {
      for (Pet pet : lived) {
        if (pet != null) {
          if (t.equals("dog") && pet instanceof Dog) {
            result.add(pet);
          } else if (t.equals("cat") && pet instanceof Cat) {
            result.add(pet);
          }
        }
      }
    }
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary:
   *   Counts the number of pets of a particular type ("dog" or "cat") living in this house.
   * Algorithm:
   *   1. Reuse `getPetsByType(type)` to obtain the filtered list.
   *   2. Return the size of that list.
   * Input:
   *   - type : String
   *       * Expected values: "dog" or "cat" (case‑insensitive).
   * Output:
   *   - int
   *       * Number of pets of the requested type.
   *       * Returns 0 if there are none or if `type` is invalid.
   * Pre‑condition:
   *   - The House instance is valid.
   * Post‑condition:
   *   - No modification to the house or its pets.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public int getPetCount(final String type)
  {
    EList<Pet> filtered = getPetsByType(type);
    return filtered.size();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public NotificationChain eInverseAdd(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PetsPackage.HOUSE__LIVED:
        return ((InternalEList<InternalEObject>)(InternalEList<?>)getLived()).basicAdd(otherEnd, msgs);
    }
    return super.eInverseAdd(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PetsPackage.HOUSE__LIVED:
        return ((InternalEList<?>)getLived()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PetsPackage.HOUSE__LIVED:
        return getLived();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PetsPackage.HOUSE__LIVED:
        getLived().clear();
        getLived().addAll((Collection<? extends Pet>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PetsPackage.HOUSE__LIVED:
        getLived().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PetsPackage.HOUSE__LIVED:
        return lived != null && !lived.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} // House
