/**
 * generated by Enhanced EcoreGen
 */
package edu.company;

import java.util.Collection;
import java.util.Map;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentWithInverseEList;
import org.eclipse.emf.ecore.util.InternalEList;
import java.util.HashMap;
import org.eclipse.emf.common.util.BasicEList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Company</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.company.Company#getWarehouses <em>Warehouses</em>}</li>
 * </ul>
 *
 * @see edu.company.CompanyPackage#getCompany()
 * @model kind="class"
 * @generated
 */
public class Company extends MinimalEObjectImpl.Container implements EObject
{
  /**
   * The cached value of the '{@link #getWarehouses() <em>Warehouses</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWarehouses()
   * @generated
   * @ordered
   */
  protected EList<Warehouse> warehouses;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Company()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CompanyPackage.Literals.COMPANY;
  }

  /**
   * Returns the value of the '<em><b>Warehouses</b></em>' containment reference list.
   * The list contents are of type {@link edu.company.Warehouse}.
   * It is bidirectional and its opposite is '{@link edu.company.Warehouse#getCompany <em>Company</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Warehouses</em>' containment reference list.
   * @see edu.company.CompanyPackage#getCompany_Warehouses()
   * @see edu.company.Warehouse#getCompany
   * @model opposite="company" containment="true"
   * @generated
   */
  public EList<Warehouse> getWarehouses()
  {
    if (warehouses == null)
    {
      warehouses = new EObjectContainmentWithInverseEList<Warehouse>(Warehouse.class, this, CompanyPackage.COMPANY__WAREHOUSES, CompanyPackage.WAREHOUSE__COMPANY);
    }
    return warehouses;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Calculates the total volume of all products supplied by a specific supplier across all warehouses in the company.
   * Algorithm:
   *   1. Initialize totalVolume = 0.0
   *   2. For each warehouse in the company's warehouses:
   *       2.1. For each productOccupation in the warehouse's occupations:
   *           2.1.1. If the product's supplier name matches the input supplierName:
   *               2.1.1.1. Add the productOccupation's volume to totalVolume
   *   3. Return totalVolume
   * Input:
   *   - supplierName: String, the name of the supplier to search for. Case-sensitive matching is assumed unless otherwise specified.
   * Output:
   *   - double: the total volume (m³) of products from the specified supplier. Returns 0.0 if no matching products are found.
   * Pre-condition: None
   * Post-condition: The company and its warehouses remain unchanged.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public double countTotalVolumeBySupplier(final String supplierName)
  {
    double totalVolume = 0.0;
    
    for (Warehouse warehouse : getWarehouses()) {
      for (ProductOccupation productOccupation : warehouse.getOccupations()) {
        Product product = productOccupation.getProduct();
        if (product != null) {
          Supplier supplier = product.getSupplier();
          if (supplier != null && supplierName.equals(supplier.getName())) {
            totalVolume += productOccupation.getVolume();
          }
        }
      }
    }
    
    return totalVolume;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Finds all warehouse locations (city and address) that contain a specific product.
   * Algorithm:
   *   1. Initialize an empty list of EMap (expected to contain city and address key-value pairs)
   *   2. For each warehouse in the company's warehouses:
   *       2.1. For each productOccupation in the warehouse's occupations:
   *           2.1.1. If the product's name matches the input productName (case-sensitive):
   *               2.1.1.1. Create a new EMap with keys "city" and "address"
   *               2.1.1.2. Put warehouse.city and warehouse.address into the EMap
   *               2.1.1.3. Add the EMap to the results list
   *               2.1.1.4. Break inner loop (avoid duplicate entries for same warehouse)
   *   3. Return the results list
   * Input:
   *   - productName: String, the name of the product to search for. Case-sensitive matching is assumed.
   * Output:
   *   - List<EMap>: A list of maps where each map contains "city" and "address" keys with corresponding values. Returns empty list if product is not found.
   * Pre-condition: None
   * Post-condition: The company and its warehouses remain unchanged.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public EList<Map<String, String>> findProductLocations(final String productName)
  {
    EList<Map<String, String>> result = new BasicEList<>();
    
    for (Warehouse warehouse : getWarehouses()) {
      boolean productFound = false;
      
      for (ProductOccupation productOccupation : warehouse.getOccupations()) {
        Product product = productOccupation.getProduct();
        if (product != null && productName.equals(product.getName())) {
          Map<String, String> locationMap = new HashMap<>();
          locationMap.put("city", warehouse.getCity());
          locationMap.put("address", warehouse.getAddress());
          result.add(locationMap);
          productFound = true;
          break;
        }
      }
    }
    
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public NotificationChain eInverseAdd(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case CompanyPackage.COMPANY__WAREHOUSES:
        return ((InternalEList<InternalEObject>)(InternalEList<?>)getWarehouses()).basicAdd(otherEnd, msgs);
    }
    return super.eInverseAdd(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case CompanyPackage.COMPANY__WAREHOUSES:
        return ((InternalEList<?>)getWarehouses()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case CompanyPackage.COMPANY__WAREHOUSES:
        return getWarehouses();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case CompanyPackage.COMPANY__WAREHOUSES:
        getWarehouses().clear();
        getWarehouses().addAll((Collection<? extends Warehouse>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case CompanyPackage.COMPANY__WAREHOUSES:
        getWarehouses().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case CompanyPackage.COMPANY__WAREHOUSES:
        return warehouses != null && !warehouses.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} // Company
