/**
 * generated by Enhanced EcoreGen
 */
package edu.employee;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentWithInverseEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Company</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.employee.Company#getDepartments <em>Departments</em>}</li>
 *   <li>{@link edu.employee.Company#getEmployees <em>Employees</em>}</li>
 * </ul>
 *
 * @see edu.employee.EmployeePackage#getCompany()
 * @model kind="class"
 * @generated
 */
public class Company extends MinimalEObjectImpl.Container implements EObject
{
  /**
   * The cached value of the '{@link #getDepartments() <em>Departments</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDepartments()
   * @generated
   * @ordered
   */
  protected EList<Department> departments;

  /**
   * The cached value of the '{@link #getEmployees() <em>Employees</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEmployees()
   * @generated
   * @ordered
   */
  protected EList<Employee> employees;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Company()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EmployeePackage.Literals.COMPANY;
  }

  /**
   * Returns the value of the '<em><b>Departments</b></em>' containment reference list.
   * The list contents are of type {@link edu.employee.Department}.
   * It is bidirectional and its opposite is '{@link edu.employee.Department#getCompany <em>Company</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Departments</em>' containment reference list.
   * @see edu.employee.EmployeePackage#getCompany_Departments()
   * @see edu.employee.Department#getCompany
   * @model opposite="company" containment="true"
   * @generated
   */
  public EList<Department> getDepartments()
  {
    if (departments == null)
    {
      departments = new EObjectContainmentWithInverseEList<Department>(Department.class, this, EmployeePackage.COMPANY__DEPARTMENTS, EmployeePackage.DEPARTMENT__COMPANY);
    }
    return departments;
  }

  /**
   * Returns the value of the '<em><b>Employees</b></em>' containment reference list.
   * The list contents are of type {@link edu.employee.Employee}.
   * It is bidirectional and its opposite is '{@link edu.employee.Employee#getCompany <em>Company</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Employees</em>' containment reference list.
   * @see edu.employee.EmployeePackage#getCompany_Employees()
   * @see edu.employee.Employee#getCompany
   * @model opposite="company" containment="true"
   * @generated
   */
  public EList<Employee> getEmployees()
  {
    if (employees == null)
    {
      employees = new EObjectContainmentWithInverseEList<Employee>(Employee.class, this, EmployeePackage.COMPANY__EMPLOYEES, EmployeePackage.EMPLOYEE__COMPANY);
    }
    return employees;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary:
   *   Computes the total salary expense for the whole company. It sums the salary of every
   *   employee, where the salary calculation differs per employee category (Worker,
   *   ShiftWorker, SalesPeople, Manager).
   * Algorithm:
   *   1. total ← 0
   *   2. For each e in this.employees
   *        a. if e is instance of ShiftWorker
   *               base ← e.weeklyWorkingHour * e.hourlyRates
   *               premium ← e.calculateHolidayPremium()
   *               total ← total + (base + premium)
   *        b. else if e is instance of OffShiftWorker
   *               total ← total + (e.weeklyWorkingHour * e.hourlyRates)
   *        c. else if e is instance of SalesPeople
   *               total ← total + (e.salary + e.amountOfSales * e.commissionPercentage)
   *        d. else if e is instance of Manager
   *               total ← total + e.salary
   *   3. Return total
   * Input:
   *   None (operates on the state of the Company instance).
   * Output:
   *   double – total salary amount of all employees, ≥ 0.
   * Pre‑condition:
   *   - The Company instance must have its employees list correctly populated.
   *   - For each employee, required fields (hourlyRates, weeklyWorkingHour, salary, etc.) must be non‑null.
   * Post‑condition:
   *   - Returns the sum of all employees’ salaries; the internal state of the Company is unchanged.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public double calculateTotalEmployeeSalary()
  {
    double total = 0.0;
    for (Employee e : getEmployees()) {
      if (e instanceof ShiftWorker) {
        ShiftWorker sw = (ShiftWorker) e;
        double base = sw.getWeeklyWorkingHour() * sw.getHourlyRates();
        double premium = sw.calculateHolidayPremium();
        total += base + premium;
      } else if (e instanceof OffShiftWorker) {
        OffShiftWorker ow = (OffShiftWorker) e;
        total += ow.getWeeklyWorkingHour() * ow.getHourlyRates();
      } else if (e instanceof SalesPeople) {
        SalesPeople sp = (SalesPeople) e;
        total += sp.getSalary() + sp.getAmountOfSales() * sp.getCommissionPercentage();
      } else if (e instanceof Manager) {
        Manager m = (Manager) e;
        total += m.getSalary();
      }
    }
    return total;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary:
   *   Calculates the aggregate commission earned by every SalesPeople in the company.
   * Algorithm:
   *   1. totalCommission ← 0
   *   2. For each e in this.employees
   *        if e is instance of SalesPeople
   *            totalCommission ← totalCommission + (e.amountOfSales * e.commissionPercentage)
   *   3. Return totalCommission
   * Input:
   *   None.
   * Output:
   *   double – total commission amount, ≥ 0.
   * Pre‑condition:
   *   - All SalesPeople objects have non‑null amountOfSales and commissionPercentage.
   * Post‑condition:
   *   - The method does not modify any object state.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public double calculateTotalSalesPeopleCommission()
  {
    double totalCommission = 0.0;
    for (Employee e : getEmployees()) {
      if (e instanceof SalesPeople) {
        SalesPeople sp = (SalesPeople) e;
        totalCommission += sp.getAmountOfSales() * sp.getCommissionPercentage();
      }
    }
    return totalCommission;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary:
   *   Computes the sum of holiday premiums that must be paid to all shift workers
   *   (only shift workers can belong to the DELIVERY department, but the method sums across the
   *   whole company, returning 0 when none exist).
   * Algorithm:
   *   1. totalPremium ← 0
   *   2. For each e in this.employees
   *        if e is instance of ShiftWorker
   *            totalPremium ← totalPremium + e.calculateHolidayPremium()
   *   3. Return totalPremium
   * Input:
   *   None.
   * Output:
   *   double – total holiday premium amount, ≥ 0.
   * Pre‑condition:
   *   - Every ShiftWorker has its holidayPremium field correctly populated.
   * Post‑condition:
   *   - No mutation of the model.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public double calculateTotalShiftWorkerHolidayPremiums()
  {
    double totalPremium = 0.0;
    for (Employee e : getEmployees()) {
      if (e instanceof ShiftWorker) {
        ShiftWorker sw = (ShiftWorker) e;
        totalPremium += sw.calculateHolidayPremium();
      }
    }
    return totalPremium;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public NotificationChain eInverseAdd(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case EmployeePackage.COMPANY__DEPARTMENTS:
        return ((InternalEList<InternalEObject>)(InternalEList<?>)getDepartments()).basicAdd(otherEnd, msgs);
      case EmployeePackage.COMPANY__EMPLOYEES:
        return ((InternalEList<InternalEObject>)(InternalEList<?>)getEmployees()).basicAdd(otherEnd, msgs);
    }
    return super.eInverseAdd(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case EmployeePackage.COMPANY__DEPARTMENTS:
        return ((InternalEList<?>)getDepartments()).basicRemove(otherEnd, msgs);
      case EmployeePackage.COMPANY__EMPLOYEES:
        return ((InternalEList<?>)getEmployees()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case EmployeePackage.COMPANY__DEPARTMENTS:
        return getDepartments();
      case EmployeePackage.COMPANY__EMPLOYEES:
        return getEmployees();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case EmployeePackage.COMPANY__DEPARTMENTS:
        getDepartments().clear();
        getDepartments().addAll((Collection<? extends Department>)newValue);
        return;
      case EmployeePackage.COMPANY__EMPLOYEES:
        getEmployees().clear();
        getEmployees().addAll((Collection<? extends Employee>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case EmployeePackage.COMPANY__DEPARTMENTS:
        getDepartments().clear();
        return;
      case EmployeePackage.COMPANY__EMPLOYEES:
        getEmployees().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case EmployeePackage.COMPANY__DEPARTMENTS:
        return departments != null && !departments.isEmpty();
      case EmployeePackage.COMPANY__EMPLOYEES:
        return employees != null && !employees.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} // Company
