/**
 * generated by Enhanced EcoreGen
 */
package edu.flights;

import java.util.Collection;
import java.util.Date;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectResolvingEList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Airline</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.flights.Airline#getFlights <em>Flights</em>}</li>
 * </ul>
 *
 * @see edu.flights.FlightsPackage#getAirline()
 * @model kind="class"
 * @generated
 */
public class Airline extends MinimalEObjectImpl.Container implements EObject
{
  /**
   * The cached value of the '{@link #getFlights() <em>Flights</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFlights()
   * @generated
   * @ordered
   */
  protected EList<Flight> flights;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Airline()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FlightsPackage.Literals.AIRLINE;
  }

  /**
   * Returns the value of the '<em><b>Flights</b></em>' reference list.
   * The list contents are of type {@link edu.flights.Flight}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Flights</em>' reference list.
   * @see edu.flights.FlightsPackage#getAirline_Flights()
   * @model
   * @generated
   */
  public EList<Flight> getFlights()
  {
    if (flights == null)
    {
      flights = new EObjectResolvingEList<Flight>(Flight.class, this, FlightsPackage.AIRLINE__FLIGHTS);
    }
    return flights;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Adds a new flight to the airline's list of flights.
   * Algorithm: Append the flight to the flights list.
   * Input: f (Flight) - The flight object to be added.
   * Output: None.
   * Pre-condition: The flight must not already exist in the flights list.
   * Post-condition: The flight is added to the flights list.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public void addFlight(final Flight f)
  {
    if (f != null && !getFlights().contains(f))
    {
      getFlights().add(f);
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Removes a flight from the airline's list of flights.
   * Algorithm: Remove the flight from the flights list.
   * Input: f (Flight) - The flight object to be removed.
   * Output: None.
   * Pre-condition: The flight must exist in the flights list.
   * Post-condition: The flight is removed from the flights list.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public void removeFlight(final Flight f)
  {
    if (f != null && getFlights().contains(f))
    {
      getFlights().remove(f);
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Publishes a flight for booking after validating its details.
   * Algorithm:
   * 1. Check if the flight's departure and arrival timestamps are in yyyy-MM-dd HH:mm:ss format.
   * 2. Verify temporal consistency: now < departureTime < arrivalTime.
   * 3. Ensure route integrity: departureAirport ≠ arrivalAirport.
   * 4. Check if the flight has not been published before and is open for booking.
   * 5. If all checks pass, set the flight's status to open for booking and return true.
   * 6. Otherwise, return false.
   * Input: f (Flight) - The flight to be published.
   *        now (EDate) - The current date and time.
   * Output: boolean - True if the flight was successfully published, false otherwise.
   * Pre-condition: The flight must exist and not have been published before.
   * Post-condition: The flight is open for booking.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public boolean publishFlight(final Flight f, final Date now)
  {
    if (f == null || f.isOpenForBooking() || f.getDepartureTime() == null || f.getArrivalTime() == null)
    {
      return false;
    }

    // Check timestamp format (simplified check)
    if (f.getDepartureTime().toString().matches("\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}") &&
        f.getArrivalTime().toString().matches("\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}"))
    {
      // Verify temporal consistency
      if (now.before(f.getDepartureTime()) && f.getDepartureTime().before(f.getArrivalTime()))
      {
        // Ensure route integrity
        if (f.getDepartureAirport() != null && f.getArrialAirport() != null &&
            !f.getDepartureAirport().equals(f.getArrialAirport()))
        {
          f.setOpenForBooking(true);
          return true;
        }
      }
    }
    return false;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Closes an open flight and cancels all confirmed reservations.
   * Algorithm:
   * 1. Find the flight with the given flightId.
   * 2. Check if the flight is open and has not yet departed (now < departureTime).
   * 3. If valid, set the flight's status to closed and cancel all confirmed reservations.
   * 4. Return true if successful, false otherwise.
   * Input: flightId (String) - The unique identifier of the flight.
   *        now (EDate) - The current date and time.
   * Output: boolean - True if the flight was successfully closed, false otherwise.
   * Pre-condition: The flight must exist and be open for booking.
   * Post-condition: The flight is closed, and all confirmed reservations are canceled.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public boolean closeFlight(final String flightId, final Date now)
  {
    if (flightId == null || now == null)
    {
      return false;
    }

    for (Flight flight : getFlights())
    {
      if (flight.getId().equals(flightId) && flight.isOpenForBooking() &&
          now.before(flight.getDepartureTime()))
      {
        flight.setOpenForBooking(false);
        // Cancel all confirmed reservations
        for (Reservation reservation : flight.getConfirmedReservations())
        {
          // Assuming there's a method to cancel reservations
          // reservation.cancel();
        }
        return true;
      }
    }
    return false;
  }

  /***
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Searches for flights based on origin, date, and destination.
   * Algorithm:
   * 1. Iterate through the flights list.
   * 2. Filter flights that match the origin, date, and destination.
   * 3. Return the filtered list.
   * Input: origin (String) - The origin city or airport.
   *        date (EDate) - The departure date.
   *        dest (String) - The destination city or airport.
   * Output: List<Flight> - A list of flights matching the criteria.
   * Pre-condition: The flights list must be initialized.
   * Post-condition: The returned list contains all matching flights.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public EList<Flight> searchFlights(final String origin, final Date date, final String dest)
  {
    EList<Flight> result = new EObjectResolvingEList<Flight>(Flight.class, this, FlightsPackage.AIRLINE__FLIGHTS);
    if (origin == null || date == null || dest == null)
    {
      return result;
    }

    for (Flight flight : getFlights())
    {
      if (flight.getDepartureAirport() != null && flight.getArrialAirport() != null &&
            flight.getDepartureAirport().getId().equals(origin) &&
            flight.getArrialAirport().getId().equals(dest))
      {
        // Check if the flight's departure date matches the given date (simplified check)
        if (flight.getDepartureTime().toString().startsWith(date.toString().substring(0, 10)))
        {
          result.add(flight);
        }
      }
    }
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case FlightsPackage.AIRLINE__FLIGHTS:
        return getFlights();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case FlightsPackage.AIRLINE__FLIGHTS:
        getFlights().clear();
        getFlights().addAll((Collection<? extends Flight>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case FlightsPackage.AIRLINE__FLIGHTS:
        getFlights().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case FlightsPackage.AIRLINE__FLIGHTS:
        return flights != null && !flights.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} // Airline
