/**
 * generated by Enhanced EcoreGen
 */
package edu.department;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.EObjectContainmentWithInverseEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Company</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.department.Company#getDepartments <em>Departments</em>}</li>
 *   <li>{@link edu.department.Company#getEmployees <em>Employees</em>}</li>
 * </ul>
 *
 * @see edu.department.DepartmentPackage#getCompany()
 * @model kind="class"
 * @generated
 */
public class Company extends MinimalEObjectImpl.Container implements EObject
{
  /**
   * The cached value of the '{@link #getDepartments() <em>Departments</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDepartments()
   * @generated
   * @ordered
   */
  protected EList<Department> departments;

  /**
   * The cached value of the '{@link #getEmployees() <em>Employees</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEmployees()
   * @generated
   * @ordered
   */
  protected EList<Employee> employees;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Company()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DepartmentPackage.Literals.COMPANY;
  }

  /**
   * Returns the value of the '<em><b>Departments</b></em>' containment reference list.
   * The list contents are of type {@link edu.department.Department}.
   * It is bidirectional and its opposite is '{@link edu.department.Department#getCompany <em>Company</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Departments</em>' containment reference list.
   * @see edu.department.DepartmentPackage#getCompany_Departments()
   * @see edu.department.Department#getCompany
   * @model opposite="company" containment="true"
   * @generated
   */
  public EList<Department> getDepartments()
  {
    if (departments == null)
    {
      departments = new EObjectContainmentWithInverseEList<Department>(Department.class, this, DepartmentPackage.COMPANY__DEPARTMENTS, DepartmentPackage.DEPARTMENT__COMPANY);
    }
    return departments;
  }

  /**
   * Returns the value of the '<em><b>Employees</b></em>' containment reference list.
   * The list contents are of type {@link edu.department.Employee}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Employees</em>' containment reference list.
   * @see edu.department.DepartmentPackage#getCompany_Employees()
   * @model containment="true"
   * @generated
   */
  public EList<Employee> getEmployees()
  {
    if (employees == null)
    {
      employees = new EObjectContainmentEList<Employee>(Employee.class, this, DepartmentPackage.COMPANY__EMPLOYEES);
    }
    return employees;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public boolean addDepartment(final Department department)
  {
    if (department == null) {
      return false;
    }
    if (!getDepartments().contains(department)) {
      getDepartments().add(department);
      return true;
    }
    return false;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public boolean addEmployee(final Employee employee)
  {
    if (employee == null) {
      return false;
    }
    if (!getEmployees().contains(employee)) {
      getEmployees().add(employee);
      return true;
    }
    return false;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public boolean deleteDepartment(final Department department)
  {
    if (department == null || !getDepartments().contains(department)) {
      return false;
    }
    
    // Remove all employees from the department and company
    if (department.getManager() != null) {
      getEmployees().remove(department.getManager());
    }
    
    // Remove the department
    getDepartments().remove(department);
    
    return true;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public EList<Department> listDepartmentsWithoutManager()
  {
    EList<Department> departmentsWithoutManager = new org.eclipse.emf.common.util.BasicEList<Department>();
    
    for (Department department : getDepartments()) {
      if (!department.hasManager()) {
        departmentsWithoutManager.add(department);
      }
    }
    
    if (departmentsWithoutManager.isEmpty()) {
      return null;
    }
    
    return departmentsWithoutManager;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public boolean assignManager(final Employee employee, final Department department)
  {
    if (employee == null || department == null) {
      return false;
    }
    
    // Check if employee and department belong to this company
    if (!getEmployees().contains(employee) || !getDepartments().contains(department)) {
      return false;
    }
    
    // Check if department already has a manager
    if (department.hasManager()) {
      return false;
    }
    
    // Assign the manager
    department.setManager(employee);
    return true;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public NotificationChain eInverseAdd(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case DepartmentPackage.COMPANY__DEPARTMENTS:
        return ((InternalEList<InternalEObject>)(InternalEList<?>)getDepartments()).basicAdd(otherEnd, msgs);
    }
    return super.eInverseAdd(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case DepartmentPackage.COMPANY__DEPARTMENTS:
        return ((InternalEList<?>)getDepartments()).basicRemove(otherEnd, msgs);
      case DepartmentPackage.COMPANY__EMPLOYEES:
        return ((InternalEList<?>)getEmployees()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DepartmentPackage.COMPANY__DEPARTMENTS:
        return getDepartments();
      case DepartmentPackage.COMPANY__EMPLOYEES:
        return getEmployees();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DepartmentPackage.COMPANY__DEPARTMENTS:
        getDepartments().clear();
        getDepartments().addAll((Collection<? extends Department>)newValue);
        return;
      case DepartmentPackage.COMPANY__EMPLOYEES:
        getEmployees().clear();
        getEmployees().addAll((Collection<? extends Employee>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DepartmentPackage.COMPANY__DEPARTMENTS:
        getDepartments().clear();
        return;
      case DepartmentPackage.COMPANY__EMPLOYEES:
        getEmployees().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DepartmentPackage.COMPANY__DEPARTMENTS:
        return departments != null && !departments.isEmpty();
      case DepartmentPackage.COMPANY__EMPLOYEES:
        return employees != null && !employees.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} // Company
