/**
 * generated by Enhanced EcoreGen
 */
package edu.employee;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentWithInverseEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Company</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.employee.Company#getDepartments <em>Departments</em>}</li>
 *   <li>{@link edu.employee.Company#getEmployees <em>Employees</em>}</li>
 * </ul>
 *
 * @see edu.employee.EmployeePackage#getCompany()
 * @model kind="class"
 * @generated
 */
public class Company extends MinimalEObjectImpl.Container implements EObject
{
  /**
   * The cached value of the '{@link #getDepartments() <em>Departments</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDepartments()
   * @generated
   * @ordered
   */
  protected EList<Department> departments;

  /**
   * The cached value of the '{@link #getEmployees() <em>Employees</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEmployees()
   * @generated
   * @ordered
   */
  protected EList<Employee> employees;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Company()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EmployeePackage.Literals.COMPANY;
  }

  /**
   * Returns the value of the '<em><b>Departments</b></em>' containment reference list.
   * The list contents are of type {@link edu.employee.Department}.
   * It is bidirectional and its opposite is '{@link edu.employee.Department#getCompany <em>Company</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Departments</em>' containment reference list.
   * @see edu.employee.EmployeePackage#getCompany_Departments()
   * @see edu.employee.Department#getCompany
   * @model opposite="company" containment="true"
   * @generated
   */
  public EList<Department> getDepartments()
  {
    if (departments == null)
    {
      departments = new EObjectContainmentWithInverseEList<Department>(Department.class, this, EmployeePackage.COMPANY__DEPARTMENTS, EmployeePackage.DEPARTMENT__COMPANY);
    }
    return departments;
  }

  /**
   * Returns the value of the '<em><b>Employees</b></em>' containment reference list.
   * The list contents are of type {@link edu.employee.Employee}.
   * It is bidirectional and its opposite is '{@link edu.employee.Employee#getCompany <em>Company</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Employees</em>' containment reference list.
   * @see edu.employee.EmployeePackage#getCompany_Employees()
   * @see edu.employee.Employee#getCompany
   * @model opposite="company" containment="true"
   * @generated
   */
  public EList<Employee> getEmployees()
  {
    if (employees == null)
    {
      employees = new EObjectContainmentWithInverseEList<Employee>(Employee.class, this, EmployeePackage.COMPANY__EMPLOYEES, EmployeePackage.EMPLOYEE__COMPANY);
    }
    return employees;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary:
   *   Computes the total monthly (or weekly) salary expense of the entire company by aggregating the
   *   salaries of workers, salespeople and managers.
   * Algorithm:
   *   1. total ← 0
   *   2. FOR each emp IN this.employees DO
   *        IF emp IS Worker THEN
   *            salary ← emp.weeklyWorkingHour * emp.hourlyRates
   *            IF emp IS ShiftWorker THEN
   *                salary ← salary + emp.calculateHolidayPremium()
   *            ENDIF
   *        ELSE IF emp IS SalesPeople THEN
   *            salary ← emp.salary + (emp.amountOfSales * emp.commissionPercentage)
   *        ELSE IF emp IS Manager THEN
   *            salary ← emp.salary
   *        ENDIF
   *        total ← total + salary
   *      END FOR
   *   3. RETURN total
   * Input:
   *   None.
   * Output:
   *   total – double – total salary of all employees, ≥ 0.
   * Pre‑condition:
   *   • this.employees is not null and contains only properly initialised Employee objects.
   *   • For each Worker, hourlyRates ≥ 0 and weeklyWorkingHour ≥ 0.
   *   • For each SalesPeople, salary ≥ 0, amountOfSales ≥ 0, commissionPercentage ∈ [0,1].
   *   • For each Manager, salary ≥ 0.
   * Post‑condition:
   *   • Returns the sum of all individual salaries as defined above.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public double calculateTotalEmployeeSalary()
  {
    double total = 0.0;
    for (Employee emp : getEmployees()) {
      double salary = 0.0;
      if (emp instanceof Worker) {
        Worker w = (Worker) emp;
        salary = w.getWeeklyWorkingHour() * w.getHourlyRates();
        if (emp instanceof ShiftWorker) {
          ShiftWorker sw = (ShiftWorker) emp;
          salary += sw.calculateHolidayPremium();
        }
      } else if (emp instanceof SalesPeople) {
        SalesPeople s = (SalesPeople) emp;
        salary = s.getSalary() + (s.getAmountOfSales() * s.getCommissionPercentage());
      } else if (emp instanceof Manager) {
        Manager m = (Manager) emp;
        salary = m.getSalary();
      }
      total += salary;
    }
    return total;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary:
   *   Calculates the total commission amount earned by all salespeople in the company.
   * Algorithm:
   *   1. totalCommission ← 0
   *   2. FOR each emp IN this.employees DO
   *        IF emp IS SalesPeople THEN
   *            totalCommission ← totalCommission + (emp.amountOfSales * emp.commissionPercentage)
   *        ENDIF
   *      END FOR
   *   3. RETURN totalCommission
   * Input:
   *   None.
   * Output:
   *   totalCommission – double – sum of (amountOfSales × commissionPercentage) for every SalesPeople, ≥ 0.
   * Pre‑condition:
   *   • this.employees is not null.
   *   • For each SalesPeople, amountOfSales ≥ 0, commissionPercentage ∈ [0,1].
   * Post‑condition:
   *   • The returned value equals the aggregate commission of all salespeople.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public double calculateTotalSalesPeopleCommission()
  {
    double totalCommission = 0.0;
    for (Employee emp : getEmployees()) {
      if (emp instanceof SalesPeople) {
        SalesPeople s = (SalesPeople) emp;
        totalCommission += s.getAmountOfSales() * s.getCommissionPercentage();
      }
    }
    return totalCommission;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary:
   *   Computes the total amount of holiday premiums that must be paid to all shift workers in the
   *   company. If there is no shift worker, the result is 0.
   * Algorithm:
   *   1. totalPremium ← 0
   *   2. FOR each emp IN this.employees DO
   *        IF emp IS ShiftWorker THEN
   *            totalPremium ← totalPremium + emp.calculateHolidayPremium()
   *        ENDIF
   *      END FOR
   *   3. RETURN totalPremium
   * Input:
   *   None.
   * Output:
   *   totalPremium – double – aggregated holiday premium, ≥ 0.
   * Pre‑condition:
   *   • this.employees is not null.
   * Post‑condition:
   *   • If no ShiftWorker exists, the method returns 0; otherwise returns the sum of their premiums.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public double calculateTotalShiftWorkerHolidayPremiums()
  {
    double totalPremium = 0.0;
    for (Employee emp : getEmployees()) {
      if (emp instanceof ShiftWorker) {
        ShiftWorker sw = (ShiftWorker) emp;
        totalPremium += sw.calculateHolidayPremium();
      }
    }
    return totalPremium;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public NotificationChain eInverseAdd(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case EmployeePackage.COMPANY__DEPARTMENTS:
        return ((InternalEList<InternalEObject>)(InternalEList<?>)getDepartments()).basicAdd(otherEnd, msgs);
      case EmployeePackage.COMPANY__EMPLOYEES:
        return ((InternalEList<InternalEObject>)(InternalEList<?>)getEmployees()).basicAdd(otherEnd, msgs);
    }
    return super.eInverseAdd(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case EmployeePackage.COMPANY__DEPARTMENTS:
        return ((InternalEList<?>)getDepartments()).basicRemove(otherEnd, msgs);
      case EmployeePackage.COMPANY__EMPLOYEES:
        return ((InternalEList<?>)getEmployees()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case EmployeePackage.COMPANY__DEPARTMENTS:
        return getDepartments();
      case EmployeePackage.COMPANY__EMPLOYEES:
        return getEmployees();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case EmployeePackage.COMPANY__DEPARTMENTS:
        getDepartments().clear();
        getDepartments().addAll((Collection<? extends Department>)newValue);
        return;
      case EmployeePackage.COMPANY__EMPLOYEES:
        getEmployees().clear();
        getEmployees().addAll((Collection<? extends Employee>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case EmployeePackage.COMPANY__DEPARTMENTS:
        getDepartments().clear();
        return;
      case EmployeePackage.COMPANY__EMPLOYEES:
        getEmployees().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case EmployeePackage.COMPANY__DEPARTMENTS:
        return departments != null && !departments.isEmpty();
      case EmployeePackage.COMPANY__EMPLOYEES:
        return employees != null && !employees.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} // Company
