/**
 * generated by Enhanced EcoreGen
 */
package edu.project;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Education Project</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.project.EducationProject#getFundinggroup <em>Fundinggroup</em>}</li>
 * </ul>
 *
 * @see edu.project.ProjectPackage#getEducationProject()
 * @model kind="class"
 * @generated
 */
public class EducationProject extends Project
{
  /**
   * The cached value of the '{@link #getFundinggroup() <em>Fundinggroup</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFundinggroup()
   * @generated
   * @ordered
   */
  protected FundingGroup fundinggroup;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EducationProject()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ProjectPackage.Literals.EDUCATION_PROJECT;
  }

  /**
   * Returns the value of the '<em><b>Fundinggroup</b></em>' reference.
   * It is bidirectional and its opposite is '{@link edu.project.FundingGroup#getFundingGroupedu <em>Funding Groupedu</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fundinggroup</em>' reference.
   * @see #setFundinggroup(FundingGroup)
   * @see edu.project.ProjectPackage#getEducationProject_Fundinggroup()
   * @see edu.project.FundingGroup#getFundingGroupedu
   * @model opposite="fundingGroupedu" required="true"
   * @generated
   */
  public FundingGroup getFundinggroup()
  {
    if (fundinggroup != null && fundinggroup.eIsProxy())
    {
      InternalEObject oldFundinggroup = fundinggroup;
      fundinggroup = (FundingGroup)eResolveProxy(oldFundinggroup);
      if (fundinggroup != oldFundinggroup)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, ProjectPackage.EDUCATION_PROJECT__FUNDINGGROUP, oldFundinggroup, fundinggroup));
      }
    }
    return fundinggroup;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FundingGroup basicGetFundinggroup()
  {
    return fundinggroup;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetFundinggroup(FundingGroup newFundinggroup, NotificationChain msgs)
  {
    FundingGroup oldFundinggroup = fundinggroup;
    fundinggroup = newFundinggroup;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ProjectPackage.EDUCATION_PROJECT__FUNDINGGROUP, oldFundinggroup, newFundinggroup);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * Sets the value of the '{@link edu.project.EducationProject#getFundinggroup <em>Fundinggroup</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param newFundinggroup the new value of the '<em>Fundinggroup</em>' reference.
   * @see #getFundinggroup()
   * @generated
   */
  public void setFundinggroup(FundingGroup newFundinggroup)
  {
    if (newFundinggroup != fundinggroup)
    {
      NotificationChain msgs = null;
      if (fundinggroup != null)
        msgs = fundinggroup.eInverseRemove(this, ProjectPackage.FUNDING_GROUP__FUNDING_GROUPEDU, FundingGroup.class, msgs);
      if (newFundinggroup != null)
        msgs = newFundinggroup.eInverseAdd(this, ProjectPackage.FUNDING_GROUP__FUNDING_GROUPEDU, FundingGroup.class, msgs);
      msgs = basicSetFundinggroup(newFundinggroup, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ProjectPackage.EDUCATION_PROJECT__FUNDINGGROUP, newFundinggroup, newFundinggroup));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseAdd(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ProjectPackage.EDUCATION_PROJECT__FUNDINGGROUP:
        if (fundinggroup != null)
          msgs = fundinggroup.eInverseRemove(this, ProjectPackage.FUNDING_GROUP__FUNDING_GROUPEDU, FundingGroup.class, msgs);
        return basicSetFundinggroup((FundingGroup)otherEnd, msgs);
    }
    return super.eInverseAdd(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ProjectPackage.EDUCATION_PROJECT__FUNDINGGROUP:
        return basicSetFundinggroup(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ProjectPackage.EDUCATION_PROJECT__FUNDINGGROUP:
        if (resolve) return getFundinggroup();
        return basicGetFundinggroup();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ProjectPackage.EDUCATION_PROJECT__FUNDINGGROUP:
        setFundinggroup((FundingGroup)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ProjectPackage.EDUCATION_PROJECT__FUNDINGGROUP:
        setFundinggroup((FundingGroup)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ProjectPackage.EDUCATION_PROJECT__FUNDINGGROUP:
        return fundinggroup != null;
    }
    return super.eIsSet(featureID);
  }

} // EducationProject
