/**
 * generated by Enhanced EcoreGen
 */
package edu.bank;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import java.math.BigDecimal;
import java.math.RoundingMode;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Saving Account</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.bank.SavingAccount#getInterestRate <em>Interest Rate</em>}</li>
 * </ul>
 *
 * @see edu.bank.BankPackage#getSavingAccount()
 * @model kind="class"
 * @generated
 */
public class SavingAccount extends Account
{
  /**
   * The default value of the '{@link #getInterestRate() <em>Interest Rate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInterestRate()
   * @generated
   * @ordered
   */
  protected static final double INTEREST_RATE_EDEFAULT = 0.0;

  /**
   * The cached value of the '{@link #getInterestRate() <em>Interest Rate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInterestRate()
   * @generated
   * @ordered
   */
  protected double interestRate = INTEREST_RATE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SavingAccount()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BankPackage.Literals.SAVING_ACCOUNT;
  }

  /**
   * Returns the value of the '<em><b>Interest Rate</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Interest Rate</em>' attribute.
   * @see #setInterestRate(double)
   * @see edu.bank.BankPackage#getSavingAccount_InterestRate()
   * @model
   * @generated
   */
  public double getInterestRate()
  {
    return interestRate;
  }

  /**
   * Sets the value of the '{@link edu.bank.SavingAccount#getInterestRate <em>Interest Rate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param newInterestRate the new value of the '<em>Interest Rate</em>' attribute.
   * @see #getInterestRate()
   * @generated
   */
  public void setInterestRate(double newInterestRate)
  {
    double oldInterestRate = interestRate;
    interestRate = newInterestRate;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BankPackage.SAVING_ACCOUNT__INTEREST_RATE, oldInterestRate, interestRate));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary:
   *   Calculates the daily interest for a saving account, adds it to the account
   *   balance, and returns the interest amount (rounded to two decimal places).
   * Algorithm:
   *   1. Compute rawInterest ← balance × interestRate / 360.
   *   2. Round interest ← rawInterest to two decimal places (half‑up).
   *   3. Update balance ← balance + interest.
   *   4. Return interest.
   * Input:
   *   (none)
   * Output:
   *   double – the interest amount added to the balance, rounded to two decimals.
   * Pre-condition:
   *   SavingAccount exists with a non‑negative balance and a non‑negative
   *   interestRate.
   * Post-condition:
   *   balance = old_balance + interest (where interest is rounded to two decimals).
   *   The method returns the same interest value.
   * <!-- end-model-doc -->
   * @model required="true"
   *        annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public double calculateDailyInterest()
  {
    // Retrieve the current balance
    double balance = getBalance();

    // 1. Compute raw interest
    double rawInterest = balance * interestRate / 360.0;

    // 2. Round to two decimal places, half‑up
    BigDecimal bd = new BigDecimal(rawInterest);
    bd = bd.setScale(2, RoundingMode.HALF_UP);
    double interest = bd.doubleValue();

    // 3. Update the balance with the rounded interest
    setBalance(balance + interest);

    // 4. Return the interest amount
    return interest;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case BankPackage.SAVING_ACCOUNT__INTEREST_RATE:
        return getInterestRate();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case BankPackage.SAVING_ACCOUNT__INTEREST_RATE:
        setInterestRate((Double)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case BankPackage.SAVING_ACCOUNT__INTEREST_RATE:
        setInterestRate(INTEREST_RATE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case BankPackage.SAVING_ACCOUNT__INTEREST_RATE:
        return interestRate != INTEREST_RATE_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (interestRate: ");
    result.append(interestRate);
    result.append(')');
    return result.toString();
  }

} // SavingAccount
