/**
 * generated by Enhanced EcoreGen
 */
package edu.rideshare;

import java.util.Collection;
import java.util.Date;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentWithInverseEList;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.util.InternalEList;
import org.eclipse.emf.common.util.BasicEList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Trip</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.rideshare.Trip#getDepartureStation <em>Departure Station</em>}</li>
 *   <li>{@link edu.rideshare.Trip#getArrivalStation <em>Arrival Station</em>}</li>
 *   <li>{@link edu.rideshare.Trip#getDepartureTime <em>Departure Time</em>}</li>
 *   <li>{@link edu.rideshare.Trip#getArrivalTime <em>Arrival Time</em>}</li>
 *   <li>{@link edu.rideshare.Trip#getNumberOfSeats <em>Number Of Seats</em>}</li>
 *   <li>{@link edu.rideshare.Trip#getDepartureDate <em>Departure Date</em>}</li>
 *   <li>{@link edu.rideshare.Trip#getPrice <em>Price</em>}</li>
 *   <li>{@link edu.rideshare.Trip#getBookings <em>Bookings</em>}</li>
 *   <li>{@link edu.rideshare.Trip#getStops <em>Stops</em>}</li>
 *   <li>{@link edu.rideshare.Trip#getDriver <em>Driver</em>}</li>
 * </ul>
 *
 * @see edu.rideshare.RidesharePackage#getTrip()
 * @model kind="class"
 * @generated
 */
public class Trip extends MinimalEObjectImpl.Container implements EObject
{
  /**
   * The default value of the '{@link #getDepartureStation() <em>Departure Station</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDepartureStation()
   * @generated
   * @ordered
   */
  protected static final String DEPARTURE_STATION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDepartureStation() <em>Departure Station</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDepartureStation()
   * @generated
   * @ordered
   */
  protected String departureStation = DEPARTURE_STATION_EDEFAULT;

  /**
   * The default value of the '{@link #getArrivalStation() <em>Arrival Station</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getArrivalStation()
   * @generated
   * @ordered
   */
  protected static final String ARRIVAL_STATION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getArrivalStation() <em>Arrival Station</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getArrivalStation()
   * @generated
   * @ordered
   */
  protected String arrivalStation = ARRIVAL_STATION_EDEFAULT;

  /**
   * The default value of the '{@link #getDepartureTime() <em>Departure Time</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDepartureTime()
   * @generated
   * @ordered
   */
  protected static final String DEPARTURE_TIME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDepartureTime() <em>Departure Time</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDepartureTime()
   * @generated
   * @ordered
   */
  protected String departureTime = DEPARTURE_TIME_EDEFAULT;

  /**
   * The default value of the '{@link #getArrivalTime() <em>Arrival Time</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getArrivalTime()
   * @generated
   * @ordered
   */
  protected static final String ARRIVAL_TIME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getArrivalTime() <em>Arrival Time</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getArrivalTime()
   * @generated
   * @ordered
   */
  protected String arrivalTime = ARRIVAL_TIME_EDEFAULT;

  /**
   * The default value of the '{@link #getNumberOfSeats() <em>Number Of Seats</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNumberOfSeats()
   * @generated
   * @ordered
   */
  protected static final int NUMBER_OF_SEATS_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getNumberOfSeats() <em>Number Of Seats</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNumberOfSeats()
   * @generated
   * @ordered
   */
  protected int numberOfSeats = NUMBER_OF_SEATS_EDEFAULT;

  /**
   * The default value of the '{@link #getDepartureDate() <em>Departure Date</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDepartureDate()
   * @generated
   * @ordered
   */
  protected static final Date DEPARTURE_DATE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDepartureDate() <em>Departure Date</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDepartureDate()
   * @generated
   * @ordered
   */
  protected Date departureDate = DEPARTURE_DATE_EDEFAULT;

  /**
   * The default value of the '{@link #getPrice() <em>Price</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPrice()
   * @generated
   * @ordered
   */
  protected static final double PRICE_EDEFAULT = 0.0;

  /**
   * The cached value of the '{@link #getPrice() <em>Price</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPrice()
   * @generated
   * @ordered
   */
  protected double price = PRICE_EDEFAULT;

  /**
   * The cached value of the '{@link #getBookings() <em>Bookings</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBookings()
   * @generated
   * @ordered
   */
  protected EList<Booking> bookings;

  /**
   * The cached value of the '{@link #getStops() <em>Stops</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStops()
   * @generated
   * @ordered
   */
  protected EList<Stop> stops;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Trip()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RidesharePackage.Literals.TRIP;
  }

  /**
   * Returns the value of the '<em><b>Departure Station</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Departure Station</em>' attribute.
   * @see #setDepartureStation(String)
   * @see edu.rideshare.RidesharePackage#getTrip_DepartureStation()
   * @model
   * @generated
   */
  public String getDepartureStation()
  {
    return departureStation;
  }

  /**
   * Sets the value of the '{@link edu.rideshare.Trip#getDepartureStation <em>Departure Station</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param newDepartureStation the new value of the '<em>Departure Station</em>' attribute.
   * @see #getDepartureStation()
   * @generated
   */
  public void setDepartureStation(String newDepartureStation)
  {
    String oldDepartureStation = departureStation;
    departureStation = newDepartureStation;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RidesharePackage.TRIP__DEPARTURE_STATION, oldDepartureStation, departureStation));
  }

  /**
   * Returns the value of the '<em><b>Arrival Station</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arrival Station</em>' attribute.
   * @see #setArrivalStation(String)
   * @see edu.rideshare.RidesharePackage#getTrip_ArrivalStation()
   * @model
   * @generated
   */
  public String getArrivalStation()
  {
    return arrivalStation;
  }

  /**
   * Sets the value of the '{@link edu.rideshare.Trip#getArrivalStation <em>Arrival Station</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param newArrivalStation the new value of the '<em>Arrival Station</em>' attribute.
   * @see #getArrivalStation()
   * @generated
   */
  public void setArrivalStation(String newArrivalStation)
  {
    String oldArrivalStation = arrivalStation;
    arrivalStation = newArrivalStation;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RidesharePackage.TRIP__ARRIVAL_STATION, oldArrivalStation, arrivalStation));
  }

  /**
   * Returns the value of the '<em><b>Departure Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Departure Time</em>' attribute.
   * @see #setDepartureTime(String)
   * @see edu.rideshare.RidesharePackage#getTrip_DepartureTime()
   * @model
   * @generated
   */
  public String getDepartureTime()
  {
    return departureTime;
  }

  /**
   * Sets the value of the '{@link edu.rideshare.Trip#getDepartureTime <em>Departure Time</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param newDepartureTime the new value of the '<em>Departure Time</em>' attribute.
   * @see #getDepartureTime()
   * @generated
   */
  public void setDepartureTime(String newDepartureTime)
  {
    String oldDepartureTime = departureTime;
    departureTime = newDepartureTime;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RidesharePackage.TRIP__DEPARTURE_TIME, oldDepartureTime, departureTime));
  }

  /**
   * Returns the value of the '<em><b>Arrival Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arrival Time</em>' attribute.
   * @see #setArrivalTime(String)
   * @see edu.rideshare.RidesharePackage#getTrip_ArrivalTime()
   * @model
   * @generated
   */
  public String getArrivalTime()
  {
    return arrivalTime;
  }

  /**
   * Sets the value of the '{@link edu.rideshare.Trip#getArrivalTime <em>Arrival Time</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param newArrivalTime the new value of the '<em>Arrival Time</em>' attribute.
   * @see #getArrivalTime()
   * @generated
   */
  public void setArrivalTime(String newArrivalTime)
  {
    String oldArrivalTime = arrivalTime;
    arrivalTime = newArrivalTime;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RidesharePackage.TRIP__ARRIVAL_TIME, oldArrivalTime, arrivalTime));
  }

  /**
   * Returns the value of the '<em><b>Number Of Seats</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Number Of Seats</em>' attribute.
   * @see #setNumberOfSeats(int)
   * @see edu.rideshare.RidesharePackage#getTrip_NumberOfSeats()
   * @model
   * @generated
   */
  public int getNumberOfSeats()
  {
    return numberOfSeats;
  }

  /**
   * Sets the value of the '{@link edu.rideshare.Trip#getNumberOfSeats <em>Number Of Seats</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param newNumberOfSeats the new value of the '<em>Number Of Seats</em>' attribute.
   * @see #getNumberOfSeats()
   * @generated
   */
  public void setNumberOfSeats(int newNumberOfSeats)
  {
    int oldNumberOfSeats = numberOfSeats;
    numberOfSeats = newNumberOfSeats;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RidesharePackage.TRIP__NUMBER_OF_SEATS, oldNumberOfSeats, numberOfSeats));
  }

  /**
   * Returns the value of the '<em><b>Departure Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Departure Date</em>' attribute.
   * @see #setDepartureDate(Date)
   * @see edu.rideshare.RidesharePackage#getTrip_DepartureDate()
   * @model
   * @generated
   */
  public Date getDepartureDate()
  {
    return departureDate;
  }

  /**
   * Sets the value of the '{@link edu.rideshare.Trip#getDepartureDate <em>Departure Date</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param newDepartureDate the new value of the '<em>Departure Date</em>' attribute.
   * @see #getDepartureDate()
   * @generated
   */
  public void setDepartureDate(Date newDepartureDate)
  {
    Date oldDepartureDate = departureDate;
    departureDate = newDepartureDate;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RidesharePackage.TRIP__DEPARTURE_DATE, oldDepartureDate, departureDate));
  }

  /**
   * Returns the value of the '<em><b>Price</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Price</em>' attribute.
   * @see #setPrice(double)
   * @see edu.rideshare.RidesharePackage#getTrip_Price()
   * @model
   * @generated
   */
  public double getPrice()
  {
    return price;
  }

  /**
   * Sets the value of the '{@link edu.rideshare.Trip#getPrice <em>Price</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param newPrice the new value of the '<em>Price</em>' attribute.
   * @see #getPrice()
   * @generated
   */
  public void setPrice(double newPrice)
  {
    double oldPrice = price;
    price = newPrice;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RidesharePackage.TRIP__PRICE, oldPrice, price));
  }

  /**
   * Returns the value of the '<em><b>Bookings</b></em>' containment reference list.
   * The list contents are of type {@link edu.rideshare.Booking}.
   * It is bidirectional and its opposite is '{@link edu.rideshare.Booking#getTrip <em>Trip</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bookings</em>' containment reference list.
   * @see edu.rideshare.RidesharePackage#getTrip_Bookings()
   * @see edu.rideshare.Booking#getTrip
   * @model opposite="trip" containment="true"
   * @generated
   */
  public EList<Booking> getBookings()
  {
    if (bookings == null)
    {
      bookings = new EObjectContainmentWithInverseEList<Booking>(Booking.class, this, RidesharePackage.TRIP__BOOKINGS, RidesharePackage.BOOKING__TRIP);
    }
    return bookings;
  }

  /**
   * Returns the value of the '<em><b>Stops</b></em>' containment reference list.
   * The list contents are of type {@link edu.rideshare.Stop}.
   * It is bidirectional and its opposite is '{@link edu.rideshare.Stop#getTrip <em>Trip</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Stops</em>' containment reference list.
   * @see edu.rideshare.RidesharePackage#getTrip_Stops()
   * @see edu.rideshare.Stop#getTrip
   * @model opposite="trip" containment="true"
   * @generated
   */
  public EList<Stop> getStops()
  {
    if (stops == null)
    {
      stops = new EObjectContainmentWithInverseEList<Stop>(Stop.class, this, RidesharePackage.TRIP__STOPS, RidesharePackage.STOP__TRIP);
    }
    return stops;
  }

  /**
   * Returns the value of the '<em><b>Driver</b></em>' container reference.
   * It is bidirectional and its opposite is '{@link edu.rideshare.Driver#getTrips <em>Trips</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Driver</em>' container reference.
   * @see #setDriver(Driver)
   * @see edu.rideshare.RidesharePackage#getTrip_Driver()
   * @see edu.rideshare.Driver#getTrips
   * @model opposite="trips" required="true" transient="false"
   * @generated
   */
  public Driver getDriver()
  {
    if (eContainerFeatureID() != RidesharePackage.TRIP__DRIVER) return null;
    return (Driver)eInternalContainer();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDriver(Driver newDriver, NotificationChain msgs)
  {
    msgs = eBasicSetContainer(newDriver, RidesharePackage.TRIP__DRIVER, msgs);
    return msgs;
  }

  /**
   * Sets the value of the '{@link edu.rideshare.Trip#getDriver <em>Driver</em>}' container reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param newDriver the new value of the '<em>Driver</em>' container reference.
   * @see #getDriver()
   * @generated
   */
  public void setDriver(Driver newDriver)
  {
    if (newDriver != eInternalContainer() || (eContainerFeatureID() != RidesharePackage.TRIP__DRIVER && newDriver != null))
    {
      if (EcoreUtil.isAncestor(this, newDriver))
        throw new IllegalArgumentException("Recursive containment not allowed for " + toString());
      NotificationChain msgs = null;
      if (eInternalContainer() != null)
        msgs = eBasicRemoveFromContainer(msgs);
      if (newDriver != null)
        msgs = newDriver.eInverseAdd(this, RidesharePackage.DRIVER__TRIPS, Driver.class, msgs);
      msgs = basicSetDriver(newDriver, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RidesharePackage.TRIP__DRIVER, newDriver, newDriver));
  }

  /***
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Calculates the discounted price for a trip based on the customer's membership.
   * Algorithm:
   * 1. Check if the customer has a membership package.
   * 2. If the customer has a membership with DISCOUNTS award, apply a 10% discount.
   * 3. If the booking time is during off-peak hours (e.g., 10 PM - 6 AM), apply an additional 5% discount.
   * 4. Return the final price.
   * Input:
   * - customer: Customer object to check for discounts
   * - bookingTime: String representing the booking time (e.g., "14:30")
   * Output:
   * - double: Discounted price of the trip
   * Pre-condition: The customer must be non-null.
   * Post-condition: The discounted price is calculated without modifying any state.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public double calculateDiscountedPrice(final Customer customer, final String bookingTime)
  {
    if (customer == null) {
      throw new IllegalArgumentException("Customer must not be null");
    }

    double discountedPrice = this.price;
    MembershipPackage membership = customer.getMembershipPackage();

    // Apply 10% discount if customer has membership with DISCOUNTS award
    if (membership != null && "DISCOUNTS".equals(membership.getAward())) {
      discountedPrice *= 0.9;
    }

    // Apply additional 5% discount for off-peak hours (10 PM - 6 AM)
    if (isOffPeakTime(bookingTime)) {
      discountedPrice *= 0.95;
    }

    return discountedPrice;
  }

  /***
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Calculates the reward points earned by the customer for the trip in the specified month.
   * Algorithm:
   * 1. Check if the trip's departure date is in the current month.
   * 2. If the customer has a membership with POINTS award, award 1 point per seat booked.
   * 3. Return the total points.
   * Input:
   * - customer: Customer object to check for points
   * - currentMonth: String representing the month (e.g., "January")
   * Output:
   * - int: Total points earned for the trip in the month
   * Pre-condition: The currentMonth must be a valid month name.
   * Post-condition: The points are calculated without modifying any state.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public int calculateMonthlyPoints(final Customer customer, final String currentMonth)
  {
    if (currentMonth == null) {
      throw new IllegalArgumentException("Current month must not be null");
    }

    if (getDepartureDate() == null) {
      return 0;
    }

    // Check if departure date is in the current month
    if (!isSameMonth(getDepartureDate(), currentMonth)) {
      return 0;
    }

    MembershipPackage membership = customer.getMembershipPackage();
    if (membership == null || !"POINTS".equals(membership.getAward())) {
      return 0;
    }

    // Calculate points (1 per seat booked)
    int points = 0;
    for (Booking booking : getBookings()) {
      points += booking.getNumberOfSeats();
    }

    return points;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Books a specified number of seats in the trip if available.
   * Algorithm:
   * 1. Check if the number of seats requested is <= available seats.
   * 2. If available, decrement the available seats by the requested number.
   * 3. Return the booking status.
   * Input:
   * - num: Number of seats to book (must be > 0 and <= available seats)
   * Output:
   * - boolean: true if seats are booked successfully, false otherwise
   * Pre-condition: The trip must have available seats.
   * Post-condition: The available seats are updated if booking is successful.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public boolean bookSeats(final int num)
  {
    if (num <= 0) {
      return false;
    }

    if (num > getNumberOfSeats()) {
      return false;
    }

    setNumberOfSeats(getNumberOfSeats() - num);
    return true;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Confirms a booking for the specified number of seats in the trip.
   * Algorithm:
   * 1. Check if the number of seats requested is <= available seats.
   * 2. If available, decrement the available seats by the requested number.
   * 3. Create a new Booking object and add it to the trip's bookings list.
   * Input:
   * - seats: Number of seats to confirm (must be > 0 and <= available seats)
   * Output:
   * - boolean: true if booking is confirmed, false otherwise
   * Pre-condition: The trip must have available seats.
   * Post-condition: The available seats are updated, and a new booking is created.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public boolean confirmBooking(final int seats)
  {
    if (seats <= 0) {
      return false;
    }

    if (seats > getNumberOfSeats()) {
      return false;
    }

    // Create and add new booking
    Booking booking = RideshareFactory.eINSTANCE.createBooking();
    booking.setNumberOfSeats(seats);
    booking.setBookingDate(new Date());
    booking.setTrip(this);
    getBookings().add(booking);

    // Update available seats
    setNumberOfSeats(getNumberOfSeats() - seats);
    return true;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Retrieves a list of all stop stations for the trip.
   * Algorithm:
   * 1. Iterate through the stops list and collect all stopStation values.
   * Input:
   * - None
   * Output:
   * - List<String>: List of stop station names
   * Pre-condition: The trip must have stops.
   * Post-condition: The list of stop stations is returned without modifying any state.
   * <!-- end-model-doc -->
   * @model kind="operation"
   *        annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public EList<String> getStopStations()
  {
    BasicEList<String> result = new BasicEList<String>();
    for (Stop stop : getStops()) {
      result.add(stop.getStopStation());
    }
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Checks if the new departure and arrival times conflict with existing trips.
   * Algorithm:
   * 1. Compare the new departure and arrival times with the driver's existing trips.
   * 2. If any existing trip overlaps with the new times, return true.
   * Input:
   * - newDepartureTime: String representing the new departure time (e.g., "14:30")
   * - newArrivalTime: String representing the new arrival time (e.g., "16:00")
   * Output:
   * - boolean: true if times conflict, false otherwise
   * Pre-condition: The times must be in a valid format.
   * Post-condition: The conflict status is determined without modifying any state.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public boolean isTimeConflicting(final String newDepartureTime, final String newArrivalTime)
  {
    if (newDepartureTime == null || newArrivalTime == null) {
      throw new IllegalArgumentException("Times must not be null");
    }

    Driver driver = getDriver();
    if (driver == null) {
      return false; // No driver, no conflicts
    }

    for (Trip existingTrip : driver.getTrips()) {
      if (existingTrip == this) {
        continue; // Skip current trip
      }

      if (driver.checkStopOverlap(this, existingTrip)) {
        return true;
      }
    }

    return false;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public NotificationChain eInverseAdd(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case RidesharePackage.TRIP__BOOKINGS:
        return ((InternalEList<InternalEObject>)(InternalEList<?>)getBookings()).basicAdd(otherEnd, msgs);
      case RidesharePackage.TRIP__STOPS:
        return ((InternalEList<InternalEObject>)(InternalEList<?>)getStops()).basicAdd(otherEnd, msgs);
      case RidesharePackage.TRIP__DRIVER:
        if (eInternalContainer() != null)
          msgs = eBasicRemoveFromContainer(msgs);
        return basicSetDriver((Driver)otherEnd, msgs);
    }
    return super.eInverseAdd(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case RidesharePackage.TRIP__BOOKINGS:
        return ((InternalEList<?>)getBookings()).basicRemove(otherEnd, msgs);
      case RidesharePackage.TRIP__STOPS:
        return ((InternalEList<?>)getStops()).basicRemove(otherEnd, msgs);
      case RidesharePackage.TRIP__DRIVER:
        return basicSetDriver(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eBasicRemoveFromContainerFeature(NotificationChain msgs)
  {
    switch (eContainerFeatureID())
    {
      case RidesharePackage.TRIP__DRIVER:
        return eInternalContainer().eInverseRemove(this, RidesharePackage.DRIVER__TRIPS, Driver.class, msgs);
    }
    return super.eBasicRemoveFromContainerFeature(msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case RidesharePackage.TRIP__DEPARTURE_STATION:
        return getDepartureStation();
      case RidesharePackage.TRIP__ARRIVAL_STATION:
        return getArrivalStation();
      case RidesharePackage.TRIP__DEPARTURE_TIME:
        return getDepartureTime();
      case RidesharePackage.TRIP__ARRIVAL_TIME:
        return getArrivalTime();
      case RidesharePackage.TRIP__NUMBER_OF_SEATS:
        return getNumberOfSeats();
      case RidesharePackage.TRIP__DEPARTURE_DATE:
        return getDepartureDate();
      case RidesharePackage.TRIP__PRICE:
        return getPrice();
      case RidesharePackage.TRIP__BOOKINGS:
        return getBookings();
      case RidesharePackage.TRIP__STOPS:
        return getStops();
      case RidesharePackage.TRIP__DRIVER:
        return getDriver();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case RidesharePackage.TRIP__DEPARTURE_STATION:
        setDepartureStation((String)newValue);
        return;
      case RidesharePackage.TRIP__ARRIVAL_STATION:
        setArrivalStation((String)newValue);
        return;
      case RidesharePackage.TRIP__DEPARTURE_TIME:
        setDepartureTime((String)newValue);
        return;
      case RidesharePackage.TRIP__ARRIVAL_TIME:
        setArrivalTime((String)newValue);
        return;
      case RidesharePackage.TRIP__NUMBER_OF_SEATS:
        setNumberOfSeats((Integer)newValue);
        return;
      case RidesharePackage.TRIP__DEPARTURE_DATE:
        setDepartureDate((Date)newValue);
        return;
      case RidesharePackage.TRIP__PRICE:
        setPrice((Double)newValue);
        return;
      case RidesharePackage.TRIP__BOOKINGS:
        getBookings().clear();
        getBookings().addAll((Collection<? extends Booking>)newValue);
        return;
      case RidesharePackage.TRIP__STOPS:
        getStops().clear();
        getStops().addAll((Collection<? extends Stop>)newValue);
        return;
      case RidesharePackage.TRIP__DRIVER:
        setDriver((Driver)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case RidesharePackage.TRIP__DEPARTURE_STATION:
        setDepartureStation(DEPARTURE_STATION_EDEFAULT);
        return;
      case RidesharePackage.TRIP__ARRIVAL_STATION:
        setArrivalStation(ARRIVAL_STATION_EDEFAULT);
        return;
      case RidesharePackage.TRIP__DEPARTURE_TIME:
        setDepartureTime(DEPARTURE_TIME_EDEFAULT);
        return;
      case RidesharePackage.TRIP__ARRIVAL_TIME:
        setArrivalTime(ARRIVAL_TIME_EDEFAULT);
        return;
      case RidesharePackage.TRIP__NUMBER_OF_SEATS:
        setNumberOfSeats(NUMBER_OF_SEATS_EDEFAULT);
        return;
      case RidesharePackage.TRIP__DEPARTURE_DATE:
        setDepartureDate(DEPARTURE_DATE_EDEFAULT);
        return;
      case RidesharePackage.TRIP__PRICE:
        setPrice(PRICE_EDEFAULT);
        return;
      case RidesharePackage.TRIP__BOOKINGS:
        getBookings().clear();
        return;
      case RidesharePackage.TRIP__STOPS:
        getStops().clear();
        return;
      case RidesharePackage.TRIP__DRIVER:
        setDriver((Driver)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case RidesharePackage.TRIP__DEPARTURE_STATION:
        return DEPARTURE_STATION_EDEFAULT == null ? departureStation != null : !DEPARTURE_STATION_EDEFAULT.equals(departureStation);
      case RidesharePackage.TRIP__ARRIVAL_STATION:
        return ARRIVAL_STATION_EDEFAULT == null ? arrivalStation != null : !ARRIVAL_STATION_EDEFAULT.equals(arrivalStation);
      case RidesharePackage.TRIP__DEPARTURE_TIME:
        return DEPARTURE_TIME_EDEFAULT == null ? departureTime != null : !DEPARTURE_TIME_EDEFAULT.equals(departureTime);
      case RidesharePackage.TRIP__ARRIVAL_TIME:
        return ARRIVAL_TIME_EDEFAULT == null ? arrivalTime != null : !ARRIVAL_TIME_EDEFAULT.equals(arrivalTime);
      case RidesharePackage.TRIP__NUMBER_OF_SEATS:
        return numberOfSeats != NUMBER_OF_SEATS_EDEFAULT;
      case RidesharePackage.TRIP__DEPARTURE_DATE:
        return DEPARTURE_DATE_EDEFAULT == null ? departureDate != null : !DEPARTURE_DATE_EDEFAULT.equals(departureDate);
      case RidesharePackage.TRIP__PRICE:
        return price != PRICE_EDEFAULT;
      case RidesharePackage.TRIP__BOOKINGS:
        return bookings != null && !bookings.isEmpty();
      case RidesharePackage.TRIP__STOPS:
        return stops != null && !stops.isEmpty();
      case RidesharePackage.TRIP__DRIVER:
        return getDriver() != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (departureStation: ");
    result.append(departureStation);
    result.append(", arrivalStation: ");
    result.append(arrivalStation);
    result.append(", departureTime: ");
    result.append(departureTime);
    result.append(", arrivalTime: ");
    result.append(arrivalTime);
    result.append(", numberOfSeats: ");
    result.append(numberOfSeats);
    result.append(", departureDate: ");
    result.append(departureDate);
    result.append(", price: ");
    result.append(price);
    result.append(')');
    return result.toString();
  }

  /** @LLM */ private boolean isOffPeakTime(String time) {
    if (time == null) return false;
    String[] parts = time.split(":");
    if (parts.length != 2) return false;
  
    try {
      int hour = Integer.parseInt(parts[0]);
      return hour >= 22 || hour < 6;
    } catch (NumberFormatException e) {
      return false;
    }
  }

  /** @LLM */ private boolean isSameMonth(Date date, String month) {
    if (date == null || month == null) return false;
  
    String[] months = {"January", "February", "March", "April", "May", "June",
                       "July", "August", "September", "October", "November", "December"};
    int monthIndex = -1;
  
    for (int i = 0; i < months.length; i++) {
      if (months[i].equalsIgnoreCase(month)) {
        monthIndex = i;
        break;
      }
    }
  
    if (monthIndex == -1) return false;
  
    java.util.Calendar cal = java.util.Calendar.getInstance();
    cal.setTime(date);
    return cal.get(java.util.Calendar.MONTH) == monthIndex;
  }

} // Trip
