/**
 * generated by Enhanced EcoreGen
 */
package edu.footballteam;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.EObjectResolvingEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Football Team</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.footballteam.FootballTeam#getFirstEleven <em>First Eleven</em>}</li>
 *   <li>{@link edu.footballteam.FootballTeam#getSpareTeam <em>Spare Team</em>}</li>
 *   <li>{@link edu.footballteam.FootballTeam#getPlayers <em>Players</em>}</li>
 *   <li>{@link edu.footballteam.FootballTeam#getAnnouncements <em>Announcements</em>}</li>
 * </ul>
 *
 * @see edu.footballteam.FootballteamPackage#getFootballTeam()
 * @model kind="class"
 * @generated
 */
public class FootballTeam extends MinimalEObjectImpl.Container implements EObject
{
  /**
   * The cached value of the '{@link #getFirstEleven() <em>First Eleven</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFirstEleven()
   * @generated
   * @ordered
   */
  protected EList<Player> firstEleven;

  /**
   * The cached value of the '{@link #getSpareTeam() <em>Spare Team</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSpareTeam()
   * @generated
   * @ordered
   */
  protected EList<Player> spareTeam;

  /**
   * The cached value of the '{@link #getPlayers() <em>Players</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPlayers()
   * @generated
   * @ordered
   */
  protected EList<Player> players;

  /**
   * The cached value of the '{@link #getAnnouncements() <em>Announcements</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAnnouncements()
   * @generated
   * @ordered
   */
  protected EList<Announcement> announcements;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FootballTeam()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FootballteamPackage.Literals.FOOTBALL_TEAM;
  }

  /**
   * Returns the value of the '<em><b>First Eleven</b></em>' reference list.
   * The list contents are of type {@link edu.footballteam.Player}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>First Eleven</em>' reference list.
   * @see edu.footballteam.FootballteamPackage#getFootballTeam_FirstEleven()
   * @model upper="11"
   * @generated
   */
  public EList<Player> getFirstEleven()
  {
    if (firstEleven == null)
    {
      firstEleven = new EObjectResolvingEList<Player>(Player.class, this, FootballteamPackage.FOOTBALL_TEAM__FIRST_ELEVEN);
    }
    return firstEleven;
  }

  /**
   * Returns the value of the '<em><b>Spare Team</b></em>' reference list.
   * The list contents are of type {@link edu.footballteam.Player}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Spare Team</em>' reference list.
   * @see edu.footballteam.FootballteamPackage#getFootballTeam_SpareTeam()
   * @model
   * @generated
   */
  public EList<Player> getSpareTeam()
  {
    if (spareTeam == null)
    {
      spareTeam = new EObjectResolvingEList<Player>(Player.class, this, FootballteamPackage.FOOTBALL_TEAM__SPARE_TEAM);
    }
    return spareTeam;
  }

  /**
   * Returns the value of the '<em><b>Players</b></em>' containment reference list.
   * The list contents are of type {@link edu.footballteam.Player}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Players</em>' containment reference list.
   * @see edu.footballteam.FootballteamPackage#getFootballTeam_Players()
   * @model containment="true"
   * @generated
   */
  public EList<Player> getPlayers()
  {
    if (players == null)
    {
      players = new EObjectContainmentEList<Player>(Player.class, this, FootballteamPackage.FOOTBALL_TEAM__PLAYERS);
    }
    return players;
  }

  /**
   * Returns the value of the '<em><b>Announcements</b></em>' containment reference list.
   * The list contents are of type {@link edu.footballteam.Announcement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Announcements</em>' containment reference list.
   * @see edu.footballteam.FootballteamPackage#getFootballTeam_Announcements()
   * @model containment="true"
   * @generated
   */
  public EList<Announcement> getAnnouncements()
  {
    if (announcements == null)
    {
      announcements = new EObjectContainmentEList<Announcement>(Announcement.class, this, FootballteamPackage.FOOTBALL_TEAM__ANNOUNCEMENTS);
    }
    return announcements;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Calculate the total number of goal-scoring announcements for the starting eleven players of the football team
   * Algorithm:
   *   1. Initialize counter = 0
   *   2. For each player in firstEleven:
   *       2.1. If player.position == Position.FORWARD:
   *           2.1.1. For each announcement in announcements:
   *               2.1.1.1. If announcement.player == player AND announcement.type == AnnouncementType.SCORE:
   *                   2.1.1.1.1. counter++
   *   3. Return counter
   * Input: None
   * Output: Total count of goal-scoring announcements made by forwards in the first eleven (integer, range: >= 0)
   * Pre-condition: firstEleven and announcements lists are initialized (may be empty)
   * Post-condition: Returns the correct count based on announcements and first eleven forward players
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public int calculateTotalGoalScoringAnnouncementsForFirstEleven()
  {
    int counter = 0;
    EList<Player> firstElevenList = getFirstEleven();
    EList<Announcement> announcementsList = getAnnouncements();
    
    for (Player player : firstElevenList) {
      if (player.getPosition() == Position.FORWARD) {
        for (Announcement announcement : announcementsList) {
          if (announcement.getPlayer() == player && announcement.getType() == AnnouncementType.SCORE) {
            counter++;
          }
        }
      }
    }
    return counter;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Find the midfielder player with the highest number within all players of the football team
   * Algorithm:
   *   1. Initialize highestNumberPlayer = null
   *   2. For each player in players:
   *       2.1. If player.position == Position.MIDFIELD:
   *           2.1.1. If highestNumberPlayer is null OR player.number > highestNumberPlayer.number:
   *               2.1.1.1. highestNumberPlayer = player
   *   3. Return highestNumberPlayer
   * Input: None
   * Output: Midfielder player with highest number, or null if no midfielders found (Player object or null)
   * Pre-condition: players list is initialized (may be empty)
   * Post-condition: Returns correct midfielder player or null if no midfielders exist
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public Player findMidfielderWithHighestNumber()
  {
    Player highestNumberPlayer = null;
    EList<Player> playersList = getPlayers();
    
    for (Player player : playersList) {
      if (player.getPosition() == Position.MIDFIELD) {
        if (highestNumberPlayer == null || player.getNumber() > highestNumberPlayer.getNumber()) {
          highestNumberPlayer = player;
        }
      }
    }
    return highestNumberPlayer;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Calculate the average age of players in the spare team of the football team
   * Algorithm:
   *   1. If spareTeam is empty, return 0.0
   *   2. Initialize totalAge = 0
   *   3. For each player in spareTeam:
   *       3.1. totalAge += player.age
   *   4. average = (double)totalAge / spareTeam.size()
   *   5. Return average
   * Input: None
   * Output: Average age of spare team players as floating-point number (double, range: >= 0.0)
   * Pre-condition: spareTeam list is initialized
   * Post-condition: Returns correct average age or 0.0 if spare team is empty
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public double calculateAverageAgeOfSpareTeam()
  {
    EList<Player> spareTeamList = getSpareTeam();
    if (spareTeamList.isEmpty()) {
      return 0.0;
    }
    
    int totalAge = 0;
    for (Player player : spareTeamList) {
      totalAge += player.getAge();
    }
    
    return (double) totalAge / spareTeamList.size();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Count the number of goal-saving announcements made by all goalkeepers on the team
   * Algorithm:
   *   1. Initialize counter = 0
   *   2. For each announcement in announcements:
   *       2.1. If announcement.type == AnnouncementType.SAVE AND announcement.player.position == Position.GOALKEEPER:
   *           2.1.1. counter++
   *   3. Return counter
   * Input: None
   * Output: Total count of goal-saving announcements by goalkeepers (integer, range: >= 0)
   * Pre-condition: announcements list is initialized (may be empty)
   * Post-condition: Returns correct count of goalkeeper save announcements
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public int calculateGoalSavingAnnouncementsByGoalkeeper()
  {
    int counter = 0;
    EList<Announcement> announcementsList = getAnnouncements();
    
    for (Announcement announcement : announcementsList) {
      if (announcement.getType() == AnnouncementType.SAVE && 
          announcement.getPlayer().getPosition() == Position.GOALKEEPER) {
        counter++;
      }
    }
    return counter;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Calculate the total number of announcements made by all forwards on the team
   * Algorithm:
   *   1. Initialize counter = 0
   *   2. For each announcement in announcements:
   *       2.1. If announcement.player.position == Position.FORWARD:
   *           2.1.1. counter++
   *   3. Return counter
   * Input: None
   * Output: Total count of all announcements by forward players (integer, range: >= 0)
   * Pre-condition: announcements list is initialized (may be empty)
   * Post-condition: Returns correct count of all forward player announcements
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public int calculateTotalAnnouncementsForForwardPlayers()
  {
    int counter = 0;
    EList<Announcement> announcementsList = getAnnouncements();
    
    for (Announcement announcement : announcementsList) {
      if (announcement.getPlayer().getPosition() == Position.FORWARD) {
        counter++;
      }
    }
    return counter;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case FootballteamPackage.FOOTBALL_TEAM__PLAYERS:
        return ((InternalEList<?>)getPlayers()).basicRemove(otherEnd, msgs);
      case FootballteamPackage.FOOTBALL_TEAM__ANNOUNCEMENTS:
        return ((InternalEList<?>)getAnnouncements()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case FootballteamPackage.FOOTBALL_TEAM__FIRST_ELEVEN:
        return getFirstEleven();
      case FootballteamPackage.FOOTBALL_TEAM__SPARE_TEAM:
        return getSpareTeam();
      case FootballteamPackage.FOOTBALL_TEAM__PLAYERS:
        return getPlayers();
      case FootballteamPackage.FOOTBALL_TEAM__ANNOUNCEMENTS:
        return getAnnouncements();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case FootballteamPackage.FOOTBALL_TEAM__FIRST_ELEVEN:
        getFirstEleven().clear();
        getFirstEleven().addAll((Collection<? extends Player>)newValue);
        return;
      case FootballteamPackage.FOOTBALL_TEAM__SPARE_TEAM:
        getSpareTeam().clear();
        getSpareTeam().addAll((Collection<? extends Player>)newValue);
        return;
      case FootballteamPackage.FOOTBALL_TEAM__PLAYERS:
        getPlayers().clear();
        getPlayers().addAll((Collection<? extends Player>)newValue);
        return;
      case FootballteamPackage.FOOTBALL_TEAM__ANNOUNCEMENTS:
        getAnnouncements().clear();
        getAnnouncements().addAll((Collection<? extends Announcement>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case FootballteamPackage.FOOTBALL_TEAM__FIRST_ELEVEN:
        getFirstEleven().clear();
        return;
      case FootballteamPackage.FOOTBALL_TEAM__SPARE_TEAM:
        getSpareTeam().clear();
        return;
      case FootballteamPackage.FOOTBALL_TEAM__PLAYERS:
        getPlayers().clear();
        return;
      case FootballteamPackage.FOOTBALL_TEAM__ANNOUNCEMENTS:
        getAnnouncements().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case FootballteamPackage.FOOTBALL_TEAM__FIRST_ELEVEN:
        return firstEleven != null && !firstEleven.isEmpty();
      case FootballteamPackage.FOOTBALL_TEAM__SPARE_TEAM:
        return spareTeam != null && !spareTeam.isEmpty();
      case FootballteamPackage.FOOTBALL_TEAM__PLAYERS:
        return players != null && !players.isEmpty();
      case FootballteamPackage.FOOTBALL_TEAM__ANNOUNCEMENTS:
        return announcements != null && !announcements.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} // FootballTeam
