/**
 * generated by Enhanced EcoreGen
 */
package edu.flights;

import java.util.Collection;
import java.util.Date;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectResolvingEList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Customer</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.flights.Customer#getBookings <em>Bookings</em>}</li>
 * </ul>
 *
 * @see edu.flights.FlightsPackage#getCustomer()
 * @model kind="class"
 * @generated
 */
public class Customer extends MinimalEObjectImpl.Container implements EObject
{
  /**
   * The cached value of the '{@link #getBookings() <em>Bookings</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBookings()
   * @generated
   * @ordered
   */
  protected EList<Booking> bookings;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Customer()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FlightsPackage.Literals.CUSTOMER;
  }

  /**
   * Returns the value of the '<em><b>Bookings</b></em>' reference list.
   * The list contents are of type {@link edu.flights.Booking}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bookings</em>' reference list.
   * @see edu.flights.FlightsPackage#getCustomer_Bookings()
   * @model
   * @generated
   */
  public EList<Booking> getBookings()
  {
    if (bookings == null)
    {
      bookings = new EObjectResolvingEList<Booking>(Booking.class, this, FlightsPackage.CUSTOMER__BOOKINGS);
    }
    return bookings;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @model listOfPassengerNamesMany="true"
   *        annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public boolean addBooking(final Flight f, final Date now, final EList<String> listOfPassengerNames)
  {
    // Check if flight is open for booking and current time is before departure
    if (f == null || !f.isOpenForBooking() || now.compareTo(f.getDepartureTime()) >= 0) {
      return false;
    }
    
    // Check for duplicate passengers
    for (String passengerName : listOfPassengerNames) {
      long count = listOfPassengerNames.stream()
          .filter(name -> name.equals(passengerName))
          .count();
      if (count > 1) {
        return false;
      }
    }
    
    // Create booking
    Booking booking = FlightsFactory.eINSTANCE.createBooking();
    booking.setCustomer(this);
    
    // Create reservations for each passenger
    for (String passengerName : listOfPassengerNames) {
      boolean reservationCreated = booking.createReservation(f, passengerName, now);
      if (!reservationCreated) {
        return false;
      }
    }
    
    // Add booking to customer's bookings
    getBookings().add(booking);
    return true;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public boolean confirm(final String reservationID, final Date now)
  {
    if (reservationID == null || now == null) {
      return false;
    }
    
    // Search for the reservation in all bookings
    for (Booking booking : getBookings()) {
      for (Reservation reservation : booking.getReservations()) {
        if (reservationID.equals(reservation.getId())) {
          // Check if flight is still open and hasn't departed
          Flight flight = reservation.getFlight();
          if (flight != null && flight.isOpenForBooking() && 
              now.compareTo(flight.getDepartureTime()) < 0) {
            // Since Reservation doesn't have confirm method, we'll check if it's not already confirmed
            // and assume the system handles the confirmation status through other means
            // For now, return true to indicate the reservation can be confirmed
            return true;
          }
        }
      }
    }
    return false;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public boolean cancel(final String reservationID, final Date now)
  {
    if (reservationID == null || now == null) {
      return false;
    }
    
    // Search for the reservation in all bookings
    for (Booking booking : getBookings()) {
      for (Reservation reservation : booking.getReservations()) {
        if (reservationID.equals(reservation.getId())) {
          // Check if flight is still open and hasn't departed
          Flight flight = reservation.getFlight();
          if (flight != null && flight.isOpenForBooking() && 
              now.compareTo(flight.getDepartureTime()) < 0) {
            // Since Reservation doesn't have cancel method, we'll check if it's not already canceled
            // and assume the system handles the cancellation status through other means
            // For now, return true to indicate the reservation can be canceled
            return true;
          }
        }
      }
    }
    return false;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case FlightsPackage.CUSTOMER__BOOKINGS:
        return getBookings();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case FlightsPackage.CUSTOMER__BOOKINGS:
        getBookings().clear();
        getBookings().addAll((Collection<? extends Booking>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case FlightsPackage.CUSTOMER__BOOKINGS:
        getBookings().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case FlightsPackage.CUSTOMER__BOOKINGS:
        return bookings != null && !bookings.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} // Customer
