/**
 * generated by Enhanced EcoreGen
 */
package edu.company;

import java.util.Collection;
import java.util.Map;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentWithInverseEList;
import org.eclipse.emf.ecore.util.InternalEList;
import java.util.HashMap;
import org.eclipse.emf.common.util.BasicEList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Company</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.company.Company#getWarehouses <em>Warehouses</em>}</li>
 * </ul>
 *
 * @see edu.company.CompanyPackage#getCompany()
 * @model kind="class"
 * @generated
 */
public class Company extends MinimalEObjectImpl.Container implements EObject
{
  /**
   * The cached value of the '{@link #getWarehouses() <em>Warehouses</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWarehouses()
   * @generated
   * @ordered
   */
  protected EList<Warehouse> warehouses;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Company()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CompanyPackage.Literals.COMPANY;
  }

  /**
   * Returns the value of the '<em><b>Warehouses</b></em>' containment reference list.
   * The list contents are of type {@link edu.company.Warehouse}.
   * It is bidirectional and its opposite is '{@link edu.company.Warehouse#getCompany <em>Company</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Warehouses</em>' containment reference list.
   * @see edu.company.CompanyPackage#getCompany_Warehouses()
   * @see edu.company.Warehouse#getCompany
   * @model opposite="company" containment="true"
   * @generated
   */
  public EList<Warehouse> getWarehouses()
  {
    if (warehouses == null)
    {
      warehouses = new EObjectContainmentWithInverseEList<Warehouse>(Warehouse.class, this, CompanyPackage.COMPANY__WAREHOUSES, CompanyPackage.WAREHOUSE__COMPANY);
    }
    return warehouses;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary:
   *   Calculates the sum of the volumes of all product occupations that belong to products
   *   supplied by a supplier identified by its name, across the whole company.
   * Algorithm:
   *   1. Validate that supplierName is not null and not empty; if invalid, return 0.0.
   *   2. Initialize totalVolume ← 0.0.
   *   3. For each Warehouse w in this.warehouses:
   *        a. For each ProductOccupation po in w.occupations:
   *            i. Let prod ← po.product.
   *            ii. If prod.supplier is not null AND prod.supplier.name equals supplierName:
   *                - totalVolume ← totalVolume + po.volume.
   *   4. Return totalVolume.
   * Input:
   *   - supplierName : String
   *       * Meaning: the exact name of the supplier whose products' volumes are to be summed.
   *       * Format: non‑null, non‑empty text.
   *       * Value range: any Unicode string; case‑sensitive matching is used.
   * Output:
   *   - double
   *       * Meaning: total summed volume (in cubic meters) of all products supplied by the given supplier.
   *       * Format: IEEE‑754 double.
   *       * Value range: ≥ 0.0. Returns 0.0 if no matching supplier or no products found.
   * Pre‑condition:
   *   - The Company instance must have its warehouses list properly initialized (may be empty).
   * Post‑condition:
   *   - The method does not modify any model elements.
   *   - Returns the correct total volume as defined above.
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public double countTotalVolumeBySupplier(final String supplierName)
  {
    // Validate input
    if (supplierName == null || supplierName.isEmpty()) {
      return 0.0;
    }

    double totalVolume = 0.0;

    // Iterate over all warehouses
    for (Warehouse w : getWarehouses()) {
      // Iterate over occupations in each warehouse
      for (ProductOccupation po : w.getOccupations()) {
        Product prod = po.getProduct();
        if (prod != null) {
          Supplier sup = prod.getSupplier();
          if (sup != null && supplierName.equals(sup.getName())) {
            totalVolume += po.getVolume();
          }
        }
      }
    }

    return totalVolume;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary:
   *   Retrieves the locations (city and address) of every warehouse that stores at least one
   *   product with the given product name.
   * Algorithm:
   *   1. Validate that productName is not null and not empty; if invalid, return an empty list.
   *   2. Initialize resultList ← empty List<EMap<String,String>>.
   *   3. For each Warehouse w in this.warehouses:
   *        a. For each ProductOccupation po in w.occupations:
   *            i. If po.product.name equals productName:
   *               - Create a map entry locMap.
   *               - locMap.put("city", w.city).
   *               - locMap.put("address", w.address).
   *               - Add locMap to resultList.
   *               - Break inner loop (no need to check further occupations in this warehouse).
   *   4. Return resultList.
   * Input:
   *   - productName : String
   *       * Meaning: the exact name of the product to locate.
   *       * Format: non‑null, non‑empty text.
   *       * Value range: any Unicode string; case‑sensitive match.
   * Output:
   *   - List<EMap>
   *       * Meaning: a list where each element is a map containing two entries:
   *           "city" → String (city of the warehouse)
   *           "address" → String (address of the warehouse)
   *       * Format: Java List of EMF EMap<String,String>.
   *       * Value range: may be empty if the product is not stored anywhere or the company has no warehouses.
   * Pre‑condition:
   *   - Company.warehouses is initialized.
   * Post‑condition:
   *   - No model elements are altered.
   *   - The returned list contains distinct warehouse locations (duplicates are avoided by breaking after first match per warehouse).
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public EList<Map<String, String>> findProductLocations(final String productName)
  {
    // Validate input
    if (productName == null || productName.isEmpty()) {
      return new BasicEList<>();
    }

    EList<Map<String, String>> resultList = new BasicEList<>();

    // Iterate over all warehouses
    for (Warehouse w : getWarehouses()) {
      // Check each occupation in the warehouse
      for (ProductOccupation po : w.getOccupations()) {
        Product prod = po.getProduct();
        if (prod != null && productName.equals(prod.getName())) {
          Map<String, String> locMap = new HashMap<>();
          locMap.put("city", w.getCity());
          locMap.put("address", w.getAddress());
          resultList.add(locMap);
          // Stop checking further occupations in this warehouse
          break;
        }
      }
    }

    return resultList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public NotificationChain eInverseAdd(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case CompanyPackage.COMPANY__WAREHOUSES:
        return ((InternalEList<InternalEObject>)(InternalEList<?>)getWarehouses()).basicAdd(otherEnd, msgs);
    }
    return super.eInverseAdd(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case CompanyPackage.COMPANY__WAREHOUSES:
        return ((InternalEList<?>)getWarehouses()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case CompanyPackage.COMPANY__WAREHOUSES:
        return getWarehouses();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case CompanyPackage.COMPANY__WAREHOUSES:
        getWarehouses().clear();
        getWarehouses().addAll((Collection<? extends Warehouse>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case CompanyPackage.COMPANY__WAREHOUSES:
        getWarehouses().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case CompanyPackage.COMPANY__WAREHOUSES:
        return warehouses != null && !warehouses.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} // Company
