/**
 * generated by Enhanced EcoreGen
 */
package edu.flights;

import java.util.Collection;
import java.util.Date;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectResolvingEList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Airline</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.flights.Airline#getFlights <em>Flights</em>}</li>
 * </ul>
 *
 * @see edu.flights.FlightsPackage#getAirline()
 * @model kind="class"
 * @generated
 */
public class Airline extends MinimalEObjectImpl.Container implements EObject
{
  /**
   * The cached value of the '{@link #getFlights() <em>Flights</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFlights()
   * @generated
   * @ordered
   */
  protected EList<Flight> flights;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Airline()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FlightsPackage.Literals.AIRLINE;
  }

  /**
   * Returns the value of the '<em><b>Flights</b></em>' reference list.
   * The list contents are of type {@link edu.flights.Flight}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Flights</em>' reference list.
   * @see edu.flights.FlightsPackage#getAirline_Flights()
   * @model
   * @generated
   */
  public EList<Flight> getFlights()
  {
    if (flights == null)
    {
      flights = new EObjectResolvingEList<Flight>(Flight.class, this, FlightsPackage.AIRLINE__FLIGHTS);
    }
    return flights;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Adds a flight to the airline's flight list
   * Algorithm: 
   *   IF f != null THEN
   *     flights.add(f)
   *   END IF
   * Input: f - Flight object to be added
   * Output: None
   * Pre-condition: f is a valid Flight object
   * Post-condition: flights contains f
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public void addFlight(final Flight f)
  {
    if (f != null) {
      getFlights().add(f);
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Removes a flight from the airline's flight list
   * Algorithm:
   *   IF f != null THEN
   *     flights.remove(f)
   *   END IF
   * Input: f - Flight object to be removed
   * Output: None
   * Pre-condition: f exists in flights list
   * Post-condition: flights no longer contains f
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public void removeFlight(final Flight f)
  {
    if (f != null) {
      getFlights().remove(f);
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Publishes a flight to make it available for booking
   * Algorithm:
   *   IF f == null OR f.openForBooking != false THEN
   *     RETURN false
   *   END IF
   *   IF f.departureTime == null OR f.arrivalTime == null THEN
   *     RETURN false
   *   END IF
   *   IF now >= f.departureTime OR f.departureTime >= f.arrivalTime THEN
   *     RETURN false
   *   END IF
   *   IF f.departureAirport == null OR f.arrivalAirport == null OR 
   *      f.departureAirport == f.arrivalAirport THEN
   *     RETURN false
   *   END IF
   *   f.openForBooking = true
   *   flights.add(f)
   *   RETURN true
   * Input: f - Flight object to publish, now - current date and time
   * Output: true if successful, false otherwise
   * Pre-condition: f is a valid Flight object with proper airports and timestamps
   * Post-condition: If successful, flight is added to flights list and open for booking
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public boolean publishFlight(final Flight f, final Date now)
  {
    if (f == null || f.isOpenForBooking()) {
      return false;
    }
    
    if (f.getDepartureTime() == null || f.getArrivalTime() == null) {
      return false;
    }
    
    if (now.compareTo(f.getDepartureTime()) >= 0 || 
        f.getDepartureTime().compareTo(f.getArrivalTime()) >= 0) {
      return false;
    }
    
    if (f.getDepartureAirport() == null || f.getArrialAirport() == null ||
        f.getDepartureAirport().equals(f.getArrialAirport())) {
      return false;
    }
    
    f.setOpenForBooking(true);
    getFlights().add(f);
    return true;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Closes an open flight and cancels all confirmed reservations
   * Algorithm:
   *   flight = find flight by flightId in flights
   *   IF flight == null OR !flight.openForBooking OR flight.departureTime <= now THEN
   *     RETURN false
   *   END IF
   *   flight.openForBooking = false
   *   FOR EACH reservation IN flight.reservations:
   *     IF reservation.status == CONFIRMED THEN
   *       reservation.status = CANCELLED
   *     END IF
   *   END FOR
   *   RETURN true
   * Input: flightId - unique identifier of the flight, now - current date and time
   * Output: true if successful, false otherwise
   * Pre-condition: flightId is not null and valid, now is current valid timestamp
   * Post-condition: If successful, flight is closed and confirmed reservations are cancelled
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public boolean closeFlight(final String flightId, final Date now)
  {
    Flight flight = null;
    for (Flight f : getFlights()) {
      if (flightId.equals(f.getId())) {
        flight = f;
        break;
      }
    }
    
    if (flight == null || !flight.isOpenForBooking() || 
        flight.getDepartureTime().compareTo(now) <= 0) {
      return false;
    }
    
    flight.setOpenForBooking(false);
    
    for (Reservation reservation : flight.getReservations()) {
      if (reservation.getStatus() == ReservationStatus.CONFIRMED) {
        reservation.setStatus(ReservationStatus.CANCELLED);
      }
    }
    
    return true;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * <!-- begin-model-doc -->
   * Summary: Searches for flights matching origin, destination and date criteria
   * Algorithm:
   *   result = new List<Flight>()
   *   FOR EACH flight IN flights:
   *     IF flight.departureAirport.id == origin AND 
   *        flight.arrivalAirport.id == dest AND
   *        flight.departureTime.date == date.date AND
   *        flight.openForBooking == true THEN
   *       result.add(flight)
   *     END IF
   *   END FOR
   *   RETURN result
   * Input: origin - departure airport ID, date - departure date, dest - arrival airport ID
   * Output: List of matching Flight objects
   * Pre-condition: origin, date, dest are valid and not null
   * Post-condition: Returns all flights matching the search criteria
   * <!-- end-model-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public EList<Flight> searchFlights(final String origin, final Date date, final String dest)
  {
    EList<Flight> result = new EObjectResolvingEList<Flight>(Flight.class, this, FlightsPackage.AIRLINE__FLIGHTS);
    
    for (Flight flight : getFlights()) {
      if (flight.getDepartureAirport() != null && 
          flight.getArrialAirport() != null &&
          origin.equals(flight.getDepartureAirport().getId()) && 
          dest.equals(flight.getArrialAirport().getId()) &&
          flight.getDepartureTime() != null &&
          flight.getDepartureTime().getDate() == date.getDate() &&
          flight.getDepartureTime().getMonth() == date.getMonth() &&
          flight.getDepartureTime().getYear() == date.getYear() &&
          flight.isOpenForBooking()) {
        result.add(flight);
      }
    }
    
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case FlightsPackage.AIRLINE__FLIGHTS:
        return getFlights();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case FlightsPackage.AIRLINE__FLIGHTS:
        getFlights().clear();
        getFlights().addAll((Collection<? extends Flight>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case FlightsPackage.AIRLINE__FLIGHTS:
        getFlights().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case FlightsPackage.AIRLINE__FLIGHTS:
        return flights != null && !flights.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} // Airline
