/**
 * generated by Enhanced EcoreGen
 */
package edu.academic;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;
import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Student</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see edu.academic.AcademicPackage#getStudent()
 * @model kind="class"
 * @generated
 */
public class Student extends MinimalEObjectImpl.Container implements EObject
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Student()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AcademicPackage.Literals.STUDENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public void enrollInCourse(final Course course)
  {
    // Check if course is not null and has available quota
    if (course != null && course.getQuota() > 0) {
        // Decrease the course quota by 1 when student enrolls
        course.decreaseQuotaBy(1);
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @model annotation="http://www.ustb.edu.cn/sei/mde/EnhancedCodeGen generated='true'"
   * @generated NOT
   */
  public void dropCourse(final Course course)
  {
    // Check if course is not null
    if (course != null) {
        // Increase the course quota by 1 when student drops
        course.increaseQuotaBy(1);
    }
  }

} // Student
